### ISSUE TITLE
Install Extension fails: does not properly install node_modules into extension folder

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-vsce#100]
_From @celador on June 20, 2016 18:13_

- VSCode Version:
1.3.0
- OS Version:
Mac OS 10.11.5

Steps to Reproduce:

1. Install extension ForceCode
2. Open in Visual Studio Code - Insiders Build v. 1.3.0 while not debugging.
3. Attempt to activate extension with compile
4. Get the error 'No handler found for the command ...' An extension might be missing an activation event.

Notes:  Extension works properly when `npm install` is run in the extension directory.  When it's packaged or published and installed in the client, not all dependencies get installed, leading to "missing module" showing up in the developer console.  I've added about 30 low level dependencies, and it currently works on one of my macs and not the other, they are the same versions and OSs

_Copied from original issue: Microsoft/vscode#7897_

**Comment by joaomoreno** [comment]
_From @celador on June 20, 2016 18:56_

Looking through the Developer Tools with the extension open, I'm getting lots of "Cannot find module ..." errors.  

I am using node 6.2.1 and npm 3.9.3.

I've since switched to node 4.45 and npm 2.15.6 with the same results.

**Comment by joaomoreno** [comment]
_From @celador on June 20, 2016 19:6_

@alexandrudima  Which versions of NPM and Node are recommended to be used for development?  It seems that I have the correct Node modules in my development node_modules folder, but they are not showing up when looking at the out directory of my extension

**Comment by joaomoreno** [comment]
_From @celador on June 20, 2016 19:9_

@alexandrudima I opened up the extension and ran `npm install` in the extension folder, and the extension works properly now.

**Comment by joaomoreno** [comment]
_From @rebornix on June 21, 2016 0:32_

Here is the thing, currently vscode will not do anything after the extension bits are uploaded to the marketplace or after installing the extension to local disk, so when you publish the extension and the node_modules you referenced in the code are not included in the extension bits, they will not show in users' machine. 

A proper solution is use `.vscodeignore` to handle file inclusion/exclusion, eg, https://github.com/rubyide/vscode-ruby/blob/master/.vscodeignore

**Comment by joaomoreno** [comment]
_From @celador on June 21, 2016 2:28_

@rebornix I had a .vscodeignore file  I copied the one you linked and removed a few lines from mine, then tried to publish again, but with the same results.  The package works on one machine, but not the other.  I don't understand why some packages would install, but not others, but then when I run `npm install` in the extension folder, it installs all the packages it needs.  

I'm currently going through and bumping the version and installing package by package all the low-level packages like `glob`, `faye-websocket`, `hawk`, etc... basically dependencies of my dependencies are not getting installed.

**Comment by joaomoreno** [comment]
_From @rebornix on June 21, 2016 3:14_

Repro on my machine, only part of the npm packages are downloaded, seems not all dependencies are included into the final extension vsix. @joaomoreno any ideas?

**Comment by joaomoreno** [comment]
@celador: I cloned the ForceCode repository, ran `npm install` and ended up with 800MB of files inside `node_modules`. This is **way** too much; extensions are currently limited to 20MB.

If you need more than that, you are free to code that up in your extension's activation event.

**Comment by celador** [comment]
@joaomoreno When I run `npm install` on my folder I only get ~70mb.. still over the limit, but not 40x over the limit... regardless... Is the only solution to reduce my dependencies?  If I include the non-installing dependencies manually in the package.json, then they do get packaged and installed.  Also, the packaged vsix file is only 8mb

**Comment by joaomoreno** [comment]
@celador Actually 8MB will work. I definitely got 800MB in my `node_modules` folder which even caused `vsce` to explode, thus never even creating the package.

**Comment by celador** [comment]
@joaomoreno Which versions of npm are you using? I'm currently using 2.15.6

**Comment by joaomoreno** [comment]
3.8.3

**Comment by celador** [comment]
@joaomoreno The ultimate problem I had was that my vsce was out of date.  It missed one package (sequin) when installing, but I was able to add that manually easily enough.  So, while not perfect.. good enough..

But for future reference for anyone else having problems with node_modules not loading nested dependencies... Make sure your vsce executable is up to date with `npm install vsce -g`

**Comment by joaomoreno** [comment]
Thanks for the update @celador. The latest `vsce` release has update notifications to prevent this from happening in the future. 👍
