### ISSUE TITLE
Print warning when .vsceignore is missing or misconfigured

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-vsce#1000]
@timheuer makes some good points 

"Without knowledge that you should be using `.vscodeignore` (maybe I'm not using vscode), nor tooling that creates that for me, nor warnings or anything, `vsce`
is packaging whatever is in the folder where I run the command. docs, tests, pipelines, etc. -- transparency is one thing (the issue I saw that's a start), how can we strive for better.  
I personally hit this a few times (and even our C# Dev Kit in initial releases) that probably should be better tooling."

The open question is how to detect this case. Should we warn when `.vscodeignore` is not there. So that the user has to at least confirm the publish. Or can we see if `.vscodeignore` still has the default value. We do the same when looking at the `readme.md`

**Comment by benibenj** [comment]
I agree we should do something to make sure the user is aware of `.vscodeignore`. I think we should print a warning when we do not detect a `.vscodeignore` file. We could also request the user to confirm that he wants to proceed without `.vscodeignore` file, however I fear we would break some pipelines with that.

Also printing what is being packaged is a great idea as mentioned here [#995](https://github.com/microsoft/vscode-vsce/issues/995) and we could even provide a command to just print what would be packaged if the user runs `vsce package` or `vsce publish` so the user can see it without actually having to package the extension.

**Comment by isidorn** [comment]
Good ideas. I suggest to discuss with Joao in your next sync, since he also has thoughts on this topic.

**Comment by benibenj** [comment]
Building on the work completed in [#995](https://github.com/microsoft/vscode-vsce/issues/995), we have added a warning for users who are not using either a .vscodeignore file or the "files" property in package.json. Additionally, we have made several minor enhancements to improve the overall experience for users packaging their extensions. These changes aim to ensure that extensions are packaged as expected.

**Comment by isidorn** [comment]
Works great -> verified
For a missing license file we ask the user to confirm with a `Y`. But for a missing .vscodeignore we just print a warning, and do not prompt the user. Should we prompt?

![Image](https://github.com/user-attachments/assets/4a3328f4-382e-4598-add1-58ddd13d95db)
