### ISSUE TITLE
Add support to use federated service connections in vsce

### ISSUE THREAD

**Issue by ocallesp** [microsoft/vscode-vsce#1004]
Current command only supports Personal Access Tokens (PATs).

Adding support for Federated Service connections can have a huge impact in our infrastructure to avoid using the Secret Rotation Tool and to avoid managing secrets, tokens, passwords, etc.

**Comment by benibenj** [comment]
You can use Microsoft Entra ID for authentication with the newly added `--azure-credential` argument

**Comment by trevors20** [comment]
@benibenj , can you point me to some documentation on how to give the vsce tool the OAuth token that I have with the --azure-credential argument?

**Comment by benibenj** [comment]
@lszomoru do you have any docs on `--azure-credential` support

**Comment by lszomoru** [comment]
Not at the moment but we should create documentation for the new flag.
