### ISSUE TITLE
Verify `Categories` values on package

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-vsce#1005]
The marketplace returns the following error message on publish when an invalid category is added in the package.json file:
`Error: Specified argument was out of the range of valid values. (Parameter 'start')`

To help the user, we could validate the categories and provide a better error message when packaging the extension. Alternatively, the marketplace would return a better error message.

Related https://github.com/microsoft/vscode-vsce/issues/977

**Comment by joaomoreno** [comment]
Duplicate of https://github.com/microsoft/vsmarketplace/issues/932
