### ISSUE TITLE
Expose enabledApiProposals as a property

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-vsce#1006]
Expose enabledApiProposals as a property

**Comment by sandy081** [comment]
To verify:

- Open Developer Tools > Network Tab and filter for `extensionquery` requests
- Open Extensions View and Search for `GitHub.copilot-chat`
- In the Network tab, expand preview of `extensionquery` request and look for `Microsoft.VisualStudio.Code.EnabledApiProposals` key in `results[0].extensions[0].versions[0].properties`
- Make sure the value of this key contains all proposals copilot chat extension is using.

**Comment by TylerLeonhardt** [comment]
The value:
> extensionsAny,newSymbolNamesProvider,interactive,codeActionAI,contribCommentThreadAdditionalMenu,contribCommentsViewThreadMenus,documentFiltersExclusive,embeddings,findTextInFiles,findFiles2,textSearchProvider,terminalDataWriteEvent,terminalExecuteCommandEvent,terminalSelection,terminalQuickFixProvider,mappedEditsProvider,aiRelatedInformation,chatParticipantAdditions,defaultChatParticipant,chatVariableResolver,contribSourceControlInputBoxMenu,authLearnMore,testObserver,aiTextSearchProvider,chatParticipantPrivate,chatProvider,lmTools@2

Looks good to me!
