### ISSUE TITLE
What is a "publisher"?

### ISSUE THREAD

**Issue by Sequoia** [Microsoft/vscode-vsce#101]
```
$ vsce create-publisher Sequoia
Publisher human-friendly name: (Sequoia)
Personal Access Token: ****************************************************

Error: Failed Request: Unauthorized(401) -
```

??? What am I supposed to enter for "publisher"? I'm here spelunking the code cuz I can't figure it out. I've tried my VS org name & my name. 😦

**Comment by Sequoia** [comment]
[These docs](https://github.com/Microsoft/vscode-docs/blob/master/docs/tools/vscecli.md) should specify what is meant by "publisher", preferably continuing with the example and entering an appropriate name for Jaoa

**Comment by joaomoreno** [comment]
>@joaomoreno Yes I have one, what i don't know is what to enter for publishername. Is it my "Team" name? An arbitrary string? I just keep getting 401 with no additional info.

Ok, let's discuss it here. A publisher is the name of the identity you want to publish extensions with. It needs to be unique, no one else should have it. `vsce create-publisher PUBLISHERNAME` will let you create a new one, so you should come up with a brand new. Can you try lowercase `sequoia`?

**Comment by Sequoia** [comment]
```
$ vsce create-publisher sequoia
Publisher human-friendly name: (sequoia)
Personal Access Token: ****************************************************

Error: Failed Request: Unauthorized(401) -

$ vsce create-publisher sequoia79812460934762
Publisher human-friendly name: (sequoia79812460934762) sequoia
Personal Access Token: ****************************************************

Error: Failed Request: Unauthorized(401) -
```

**Comment by Sequoia** [comment]
Is there any other way to do this? to "create a publisher"? Honestly I'm not even clear what a "publisher" is. Is it me/my MSFT account? is it my team? If it's neither of those I wonder why one of those can't be used. Anyway thanks for your help I hope I can figure this out eventually & get my plugin up.

**Comment by Sequoia** [comment]
OK I created a new token & took care to set the "accessible accounts" as described [here](https://code.visualstudio.com/docs/tools/vscecli#_common-questions). I still have absolutely no clue what that setting means or what a publisher is, but the Magical Incantation seemed to work! :)

**Comment by cdyson37** [comment]
I can't find anything in the official docs that says exactly what a publisher name is and what it's for, only that you should create one, and it should appear in package.json.

Here it tells you how to create one, but not the properties it should have (uniqueness? whitespace allowed?) https://code.visualstudio.com/docs/extensions/publish-extension#_publishers-and-personal-access-tokens

**Comment by harry-public** [comment]
_A publisher is an identity who can publish extensions to the Visual Studio Code Marketplace. Every extension needs to include a publisher name in its package.json file._ their doc states.

you can create a publisher [here](https://marketplace.visualstudio.com/manage/createpublis).

**Comment by rediffusion** [comment]
@harry-public 

 Yes, but the correct link is [this](https://marketplace.visualstudio.com/manage/createpublisher). 🤙
