### ISSUE TITLE
Spaces in the `publisher` field

### ISSUE THREAD

**Issue by kotborealis** [microsoft/vscode-vsce#1010]
There's a bug in VSCode extensions handling - I'll probably need to report this issue to the VSCode repo, but I think there should be some more assertions in the vsce to prevent those issues.

**Bug**. If the extension's `package.json` file has a publisher field with spaces in it (like `my publisher`), vsce properly compiles extension, VSCode properly installs & loads it, but it causes a bug in the UI.
**To reproduce** this issue I've prepared a [demo repo](https://github.com/kotborealis/vsce-publisher-spaces-bug):
1. Build the extension using `npx @vscode/vsce pack`.
2. Install extension with spaces in publisher field.
3. Navigate to the extension page.
4. ![image](https://github.com/microsoft/vscode-vsce/assets/6463851/7ce03e5b-cf2c-42ac-b674-dd40900f1a2b)
5. Click the settings button.
6. ![image](https://github.com/microsoft/vscode-vsce/assets/6463851/462ece98-f1d2-4e30-b190-5c42c4f8da48)

**Expected behaviour**: after clicking the settings button, a page with the extension's settings is opened.

**Actual behaviour**: an empty page is opened.
![image](https://github.com/microsoft/vscode-vsce/assets/6463851/d0388a86-78e4-4b27-9530-9e962ae80424)

As you might see, the spaces in the extension's name are preventing VSCode from properly formatting a filter string for settings page. If you manually add quotation marks to the filter - it works just fine.
![image](https://github.com/microsoft/vscode-vsce/assets/6463851/d1c6bcf8-38a6-45cc-9e73-88f472b91b29)

Format of the publisher property is not enforced by the vsce - there's no errors and warnings - but the extension is not working correctly.
Documentation also does not say anything about the publisher field. I guess the spaces would be prohibited during publishing the extension to the vscode marketplace. 

To prevent this issue there should be an error (or a warning, at least) while compiling extension with the malformed published id. We should also address it in VSCode to make sure that the generated settings filter is always properly formatted.

Should I make a PR to add this check to vsce, or did I miss something?

**Comment by benibenj** [comment]
Verification steps:
- Try to package an extension which has a publisher name that includes a space in it
- => Error expected
