### ISSUE TITLE
--skip-duplicates flag incorrectly causes other target platforms to be skipped

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-vsce#1014]
We added the --skip-duplicates flag (from https://github.com/microsoft/vscode-vsce/pull/776) and that caused our Window-x64 vsix to be published and the 8 other platforms were incorrectly skipped for being a duplicate.

Let me know if you need more info.

**Comment by benibenj** [comment]
Could you clarify how you are using vsce to publish your extension with different targets and which vsce arguments you are using. 

Also:
- Are you signing the vsix? 
- Which vsce version are you on?
- If I understand correctly you newly added ` --skip-duplicates` the flag and haven't used it successfully before? So this is not a regression?
- Which message are you seeing? I am assuming `Version VERSION is already published. Skipping publish.`. In that case we have detected that there already exists the same version for the same target on the marketplace.

**Comment by sean-mcmanus** [comment]
@benibenj We are not signing the vsix (I wasn't aware that was possible yet, and we want to sign the vsix eventually).

We are using vsce 2.15.0.

We recently added the --skip-duplicates file. It's not a regression.

Logging is 
INFO  Publishing 'ms-vscode.cpptools (win32-x64) v1.21.1'...
...
DONE  Published ms-vscode.cpptools (win32-x64) v1.21.1.

then

INFO  Publishing 'ms-vscode.cpptools (win32-arm64) v1.21.1'...
DONE  Version 1.21.1 is already published. Skipping publish.

Our args are like

vsce package --yarn --target win32-ia32 --pre-release

then

vsce publish --noVerify --pre-release --skip-duplicate --packagePath <path>

Although we later removed --pre-release from the "publish" step since it appeared to have no effect given the flag is already used in the package step.

**Comment by benibenj** [comment]
It seems like you are using an outdated (depricated) vsce package. The newest version is 2.30.0. The package is published under [@vscode/vsce](https://www.npmjs.com/package/@vscode/vsce). You you try the newest version and check if your problem still occurs.

**Comment by sean-mcmanus** [comment]
Okay, I'll close this until we can update our vsce.
