### ISSUE TITLE
Pushing a new readme to marketplace without updating extension

### ISSUE THREAD

**Issue by skolmer** [Microsoft/vscode-vsce#102]
I want to add some more details to the readme of my extension, do I have to push a new version or is there a command that just updates the marketplace details?

**Comment by stkb** [comment]
As far as I know you have to push a new version. As the author of an extension that has had several .0.1 updates just to fix the readme, I would have appreciated such a feature too :)

**Comment by joaomoreno** [comment]
Yeah, pushing a new version is the way to go.
