### ISSUE TITLE
Using --azure-credential with service principal to publish raises an ERROR  You need to be logged in with your corporate credentials to perform this action.

### ISSUE THREAD

**Issue by trevors20** [microsoft/vscode-vsce#1023]
Hi there.  I am trying out the new changes to vsce to use a federated service connection to publish to the marketplace and use the --azure-credential switch.

It looks like I am using version 2.31.0 of the vsce toolset.

I first validated using the verify-pat command that using the federated service connection is working:
vsce verify-pat [publishid] --azure-credential
The Personal Access Token verification succeeded for the publisher '[publishid]'.

But.... When I actually try to publish some vsix's for real, I get the following error:
vsce publish --azure-credential --pre-release --packagePath package1.vsix package2.vsix package3.vsix package4.vsix

 INFO  Publishing '[publishid].package1 v1.0.0'...
 **ERROR  You need to be logged in with your corporate credentials to perform this action.**

Does anyone have any ideas as to what is preventing me from publishing to the marketplace using an SP?
Thanks much!

CC: @lszomoru

**Comment by lszomoru** [comment]
What task/version are you using to run vsce? It's interesting that verify-pat succeeds but publishing does not. 
Could you add the following line before calling `vsce` just so that we confirm that we are using the correct identity:
```
az rest -u https://app.vssps.visualstudio.com/_apis/profile/profiles/me --resource 499b84ac-1321-427f-aa17-267ca6975798
```

**Comment by trevors20** [comment]
Looks like vsce did not spit out the version.  At the time, it should have been the latest version.
Let me add a call to vsce to show the version that we are using as well as the call to "az rest" and respond back with the information.  We might not be able to attempt his until tomorrow.

**Comment by trevors20** [comment]
@lszomoru , We finally had a release and so we tried it with the additional logging. 
Not sure if you are able to see this link or not but this is the output of the logs: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10016488&view=logs&j=3c073bee-8c2e-5620-5ea2-f936c289b2ff&t=2cfe0b00-f61a-5101-2dd5-b2cfdfc8b2c7
