### ISSUE TITLE
glob 7.* is going EOL

### ISSUE THREAD

**Issue by pelikhan** [microsoft/vscode-vsce#1026]
Warning when installing on node 20

```
warning @vscode/vsce > glob@7.2.3: Glob versions prior to v9 are no longer supported
```

**Comment by plemarquand** [comment]
Aside from using an outdated glob directly, `@vscode/vsce` also depends on `tmp@^0.2.1`, which in turn relies on `rimraf` 3.0.2, which depends on `glob` 7.1.3. Updating `tmp` to 0.2.3 fixes this dependency chain.
