### ISSUE TITLE
Publisher required when only packaging an extension

### ISSUE THREAD

**Issue by renan-r-santos** [microsoft/vscode-vsce#1029]
https://github.com/microsoft/vscode-vsce/pull/1011 introduced a requirement that we should set a publisher even if we are just calling `vsce package` and have no intention to publish the artifact.
I wonder if it would be possible to reverse this behavior and allow packaging an extension without defining a publisher.

**Comment by buildwithzephyr** [comment]
Bump. This requirement was previously removed. https://github.com/microsoft/vscode-vsce/issues/328

**Comment by benibenj** [comment]
Could you elaborate on why you would like to package an extension without publisher name? I believe vscode now requires a publisher name when loading an extension from a `.vsix` file. Is this correct @sandy081? Or do you only validate the publisher if there is one present?

**Comment by lppedd** [comment]
IMO `package` should not require a `publisher` value.  
I'd leave that for commands that actually publish, or for the proposed [validate](https://github.com/microsoft/vscode-vsce/issues/1038) command/option, which would ensure the extension is ready to be published.

**Comment by benibenj** [comment]
You are right. We can allow you to package an extension which does not have a publisher. However, if you have a publisher and it is invalid, we will still throw an error as VS Code won't allow you to load it.

**Comment by lppedd** [comment]
Thanks for the fast change!
