### ISSUE TITLE
Error: EPERM: operation not permitted, open 'c:\users\chris\.vsce'

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-vsce#103]
trying to publish the jscs extension (https://github.com/microsoft/vscode-jscs)

``` bash
d:\src\vscode-jscs\jscs>vsce publish
Executing prepublish script 'cd ../jscs-server && npm run compile && cd ../jscs && npm run compile'...

> jscs-server@0.1.4 compile d:\src\vscode-jscs\jscs-server
> installServerIntoExtension ../jscs ./package.json ./src/tsconfig.json && tsc -p ./src

Copying package.json to extension's server location...
Updating server npm modules into extension's server location...

> jscs@0.1.6 compile d:\src\vscode-jscs\jscs
> tsc -p ./

Personal Access Token for publisher 'ms-vscode': ****************************************************

Authentication successful. Found publisher 'Microsoft'.
Error: EPERM: operation not permitted, open 'C:\Users\Chris\.vsce'
```

There is no .vsce file or folder in my home directory (c:\users\chris).

**Comment by joaomoreno** [comment]
Do you get it consistently? Even after a machine restart?

**Comment by chrisdias** [comment]
Worked on OSX... will test again on Windows.

**Comment by chrisdias** [comment]
I had a super old version of `vsce` on my system (0.8.1) that i had to manually delete.  I installed the latest and I can now publish on both Windows and OSX.

**Comment by chrisdias** [comment]
Initially I thought c:\users\chris\.vsce didn't exist, but it turns out it did, it was hidden. Not sure why this was but when I change the attribute publishing started to work.  Weird, but that was the issue.
