### ISSUE TITLE
Validate extension before packaging

### ISSUE THREAD

**Issue by artrz** [microsoft/vscode-vsce#1038]
Hello. Similarly to #570, I haven't found a way to validate if an extension is correctly configured before packaging / publishing which makes automation more difficult. I've only been bitten when `engines.vscode` and `@types/vscode` dep aren't compatible so I'm not aware of other constraints. Using `vsce package` leaves leftovers and using a script would require replication it in every extension repository. Is it possible to add something like `vsce validate` / `vsce package --dry-run`?

**Comment by joaomoreno** [comment]
Have you tried `vsce package -o /dev/null`?

**Comment by artrz** [comment]
Thanks for answering @joaomoreno. I'm getting `EPERM: operation not permitted, unlink '/dev/null'`
MacOS Sonoma, Node v20.11.1
