### ISSUE TITLE
CHANGELOG.md is not being included in local .vsix package

### ISSUE THREAD

**Issue by bf-software** [microsoft/vscode-vsce#1041]
When I have a `CHANGELOG.md` file in the same folder as my extension's `package.json` , `vsce package` will not include it in the `.vsix`.  `vsce ls` doesn't show it in the list of files either.

If I modify this line in the source:
https://github.com/microsoft/vscode-vsce/blob/0ec0e7f21f680566bfb9c8311b25ecd1f1d4f6c9/src/package.ts#L1652C2-L1652C57

from:
```
const notIgnored = ['!package.json', `!${readmePath}`];
```
to: 
```
const notIgnored = ['!package.json', `!${readmePath}`, '!CHANGELOG.md'];
```

then all is well:  `vsce ls` shows it, and `vsce package` includes the file in the archive as well as the correct `extension.vsixmanifest` xml entry.

(obviously having the `.vsix` include `CHANGELOG.md` is important because I want the "CHANGELOG" tab to appear in the marketplace on my extension's page.)

**Comment by benibenj** [comment]
I've tested this and it does work with my setup. Which vsce version are you running? You can see the latest verions [here](https://www.npmjs.com/package/@vscode/vsce?activeTab=versions)
- Can you check if you have a `.vscodeignore` file in your repository and make sure it does not exclude the changelog file there. 
- If you have the `files` property set in your `package.json` file you'll need to make sure to include the path to the changelog file in that case.

**Comment by bf-software** [comment]
Hi @benibenj,

You nailed it!  It was my `.vscodeignore` ignoring everything, then only allowing a few items (and not the CHANGELOG.md)

Thanks!
Bill.

**Comment by korbinianhutter** [comment]
I have the same issue. I just deleted my .vscodeignore file and want to handle everything with package.json's file property. 

However, I get the following error on `vsce package`:
```
 ERROR  The following include patterns in the "files" property in package.json do not match any files packaged in the extension:
  - D:/projects/logtraceviewer/CHANGELOG.md
Remove any include pattern which is not needed.

=> Run vsce ls --tree to see all included files.
=> Use --allow-unused-files-pattern to skip this check
```
