### ISSUE TITLE
Normalization of LICENSE path triggers unused-files-patterns check

### ISSUE THREAD

**Issue by mlasson** [microsoft/vscode-vsce#1047]
When packaging a VSCode extension with a "LICENSE" file that has no file extension, and this file is listed in the "files" directive in the manifest, the check for unused file patterns is triggered. This happens because the LICENSE file is normalized to "LICENSE.txt" within the package (and the check is implemented against the normalized path).

To continue using "LICENSE" as a filename, the only workaround seems to be using the "LICENSE*" pattern in the "files" directive.

**Comment by benibenj** [comment]
Thank you @mlasson for reporting this, this also uncovered some other bugs in the "unused-files-patterns check". I made the required fixes and added tests to make sure it works as expected.
