### ISSUE TITLE
--readme-path is ignored by the marketplace

### ISSUE THREAD

**Issue by winseros** [microsoft/vscode-vsce#1048]
Hi, I created an extension and when packaging, I specified the path to the readme file `--readme-path README.marketplace.md`. The `README.marketplace.md` got included into the `visx` package and the package manifest points to it. 

Having published the extension, I was surprised that Visual Studio Marketplace ignored the `README.marketplace.md` and shows the `README.md` from GitHub (!!) as a readme.

**Comment by benibenj** [comment]
Thanks for reporting this. Could you check both the visual studio code marketplace [website](https://marketplace.visualstudio.com/VSCode) and the marketplace inside the product and let me know if you see the wrong readme in both cases?

**Comment by winseros** [comment]
Hi, both the marketplace website and the Visual Studio Code show the wrong readme.

**Comment by benibenj** [comment]
What version are you currently using? Could you make sure you are using one of the latest versions, we made a fix in this area not to long ago, this might have fixed your case.

**Comment by benibenj** [comment]
Great, I'll have a look. In the meantime you can add `readme.md` to the `.vscodeignore` file. This will lead to it not being packaged in the extension.

**Comment by winseros** [comment]
`README.md` was not included into `visx`. Only `README.marketplace.md` was. That was surprising me especially, as the marketplace was using the readme file that was not even included into the visx.

**Comment by benibenj** [comment]
There seems to be a bug in vsce. However, the github readme file also seems to be packaged and because it is using the default readme.md filename, it is being shown on the marketplace. The marketplace does not check github repositories for readme files

**Comment by benibenj** [comment]
Need to verify with feature owner what the expected behaviour is to understand if this is a marketplace bug or a vsce bug.
related: https://github.com/microsoft/vscode-vsce/issues/905

**Comment by joaomoreno** [comment]
I suggest we reverse our decision to keep the display README.md in its original location and instead just copy its contents over the top level README.md, keeping things simple.
