### ISSUE TITLE
Add `darwin-universal` target

### ISSUE THREAD

**Issue by paulober** [microsoft/vscode-vsce#1049]
Since many binaries are currently build for macOS universal I guess also many `darwin-x64` and darwin-arm64 vsix packages are the same.
Therefore I would suggest adding a new target `darwin-universal` which would if uploaded replace the downloads for `darwin-x64` and `darwin-arm64` without using double the storage on the Microsoft servers. But it would still allow to later publish a `darwin-x64` for example which would then label the `darwin-universal` as `darwin-arm64` and upload the new package as `darwin-x64`.

**Comment by paulober** [comment]
Currently the publish command does support adding `darwin-x64` and `darwin-arm64` but package not. So if you have a platform dependent package are you supposed to package all platforms platform dependent but for macOS package universal and publish platform dependent.

**Comment by sandy081** [comment]
CC @isidorn 

This requires support in Marketplace.

**Comment by joaomoreno** [comment]
Let's not overcomplicate things here. If you have binaries that run on both OSs, please publish both the `-x64` and `-arm64` targets for the extension.

**Comment by paulober** [comment]
I overcomplicate things in publishing scripts with the current state.
