### ISSUE TITLE
vsce publish = Failed Request: Not Found(404)

### ISSUE THREAD

**Issue by pflannery** [Microsoft/vscode-vsce#105]
When trying to publish an update for https://github.com/vscode-contrib/vscode-versionlens
I see the following error

```sh
$ vsce publish
Executing prepublish script 'node ./node_modules/vscode/bin/compile'...
Publishing pflannery.vscode-versionlens@0.5.0...
Error: Failed Request: Not Found(404) -
```

**Comment by joaomoreno** [comment]
Cool extension!

I couldn't reproduce... I was also able to successfully publish it under my own publisher.

Do you have vsce's latest version (1.7.0)?

**Comment by pflannery** [comment]
Yes was using 1.7.0.

Will try again when I get home tonight.

**Comment by pflannery** [comment]
@joaomoreno 
I found the problem. When I try to upload the vsix via the website I was told the package is too big (currently 52mb). 
Seems related to this https://github.com/Microsoft/vscode-vsce/issues/92

After playing around I discovered that I had to add `.vscode-test/**` folder to the [.vscodeignore](https://github.com/vscode-contrib/vscode-versionlens/blob/master/.vscodeignore) file which reduced the package size to around 5mb.

Thanks for your help and comments

**Comment by joaomoreno** [comment]
Thanks for letting us know!

**Comment by jpoon** [comment]
We also hit the same problem. Would be great to return a more debuggable message :)
