### ISSUE TITLE
Pre release tags not ignored

### ISSUE THREAD

**Issue by harrydowning** [microsoft/vscode-vsce#1052]
According to the [docs](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions)

> We only support major.minor.patch for extension versions, semver pre-release tags are not supported. So, if you publish a major.minor.patch-tag release to the Marketplace, it will be treated as major.minor.patch, and the tag will be ignored

However, this is contradicted by the behaviour of the `vsce` tool. For instance I got the following error when trying to publish `1.1.0-beta`
![image](https://github.com/user-attachments/assets/f99f2cf1-5877-415f-9e2c-ee3d4295e28e)

I've created a PR to update the docs if this is not intended to be supported see https://github.com/microsoft/vscode-docs/pull/7593

**Comment by benibenj** [comment]
Thank you for reporting and creating the PR!
