### ISSUE TITLE
Fail to update extension 

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-vsce#107]
_From @Lonefy on July 18, 2016 8:14_

- OS Version: win 10
- vsce Version:1.7.0

When i run `vsce publish`,  it suggest `Successfully published`.However, the extension version is not updated correctly, but the `last update time` is right.

_Copied from original issue: Microsoft/vscode#9431_

**Comment by joaomoreno** [comment]
What do you mean with the `last update time`? Can you show me a screenshot?

**Comment by joaomoreno** [comment]
_From @Lonefy on July 18, 2016 8:35_

@joaomoreno 
screenshot
![image](https://cloud.githubusercontent.com/assets/7921431/16909471/86b33cfe-4d05-11e6-8fb0-b2c1b1549077.png)

**Comment by joaomoreno** [comment]
cc @hamenon @modigrv

**Comment by hamenon** [comment]
@joaomoreno is the version information updated in the json? We pick up the version information directly from there as far as I know. We don't enforce that the version has to be different during the publish.

**Comment by Lonefy** [comment]
I've updated the vsersion to 0.1.5 in `package.json`
screenshoot
![tt](https://cloud.githubusercontent.com/assets/7921431/16910169/c757d702-4d09-11e6-8d2e-89616756b7c4.jpg)

**Comment by hamenon** [comment]
@Lonefy Could you let us know what the latest version number was that you tried to update to? Is it 0.1.32? I'll have someone look it up on our end.

**Comment by Lonefy** [comment]
@hamenon i think I've got your point.i tried to update it to 0.1.5 which seems to be a lower version num than 0.1.31.

**Comment by joaomoreno** [comment]
So, using a number _greater_ than 0.1.31 works?

**Comment by Lonefy** [comment]
@joaomoreno yeah, it works. Sorry for this simple issue. :)

**Comment by hamenon** [comment]
@Lonefy @joaomoreno Glad to hear it's working. Just an FYI though, the number doesn't necessarily have to be _greater_ it's just that it has to be _unique_. In this case it looks like a version with number 0.1.5 already existed. Though it is always better to increment version number as it's easier to keep track.

**Comment by hamenon** [comment]
Sorry quick update, seems we did add a check recently to disallow moving to a lower version number recently. So updating to a _greater_ version number is required.
