### ISSUE TITLE
vsce package always asks for a token

### ISSUE THREAD

**Issue by Netzeband** [microsoft/vscode-vsce#1076]
Hello

I'm just a VSCode user and not an extension developer.
However, I found a bug in one of the extensions I use and saw inside the code, that it is a one line change, which needs to be done here.
So my idea was to just clone the repository, do the change, create an VSIX file locally and install it in my VSCode installation. Of course I also tell the author of the extension about the bug, but before I get this fix, it may take some time.

However, every time when I execute `vsce package` it asks me for an personal access token to Azure. I really don't want to publish anything, I don't have an Azure account, I don't need an Azure account, therefore I don't have a token. I don't want to have an account or token.

I cannot find any option to tell vsce to just create the VSIX file for me. I just found similar topics here in the repro like:
https://github.com/microsoft/vscode-vsce/pull/487 and https://github.com/microsoft/vscode-vsce/issues/328 but they don't have a real solution to that.

So how can I just create the VSIX files to manually install the extension to my local VSCode installation?

**Comment by Netzeband** [comment]
Hello, I did this, but then `vsce` complains, that the key `publisher` is not defined.

**Comment by benibenj** [comment]
Are you using the latest [@vscode/vsce](https://www.npmjs.com/package/@vscode/vsce?activeTab=versions) version? What version are you using?

**Comment by Netzeband** [comment]
Thanks a lot, the question for the version was good. It pointed me to the fact that the vsce version I'm using was quite old. I updated it to 3.2.1 and now it works without the publisher key in. Thanks for helping me.
