### ISSUE TITLE
Support for displaying project information on Marketplace

### ISSUE THREAD

**Issue by hamenon** [Microsoft/vscode-vsce#108]
We've added support for displaying GitHub project details and Badges on the item details page on the marketplace. But for the page to display the details we need changes to the way the tool packages the vsixmanifest. The new experience is as follows

![github-proj](https://cloud.githubusercontent.com/assets/13758921/16943265/7bc7ce6e-4db8-11e6-89d2-9eb78e6a3dcc.png)

Following are the changes required:

- If the repository type is "Git", change the link type to Microsoft.VisualStudio.Services.Links.GitHub as opposed to Microsoft.VisualStudio.Services.Links.Repository

- We now have support for an additional badges section:

![](https://cloud.githubusercontent.com/assets/19949257/16112871/04620ec0-33d7-11e6-85d9-3aad7e1914f8.png)

which needs to be translated to badges section as highlighted below

![manifest-changes](https://cloud.githubusercontent.com/assets/13758921/16943337/d474689c-4db8-11e6-8d79-c7a012b03037.png)

**Comment by joaomoreno** [comment]
This is really cool. I can start up a PR and let you review it, what do you say?

I assume that when you say

> If the repository type is "Git", change the link type to 

you meant _if the repository is hosted on github_.

PS: Did I just see Notepad++ in your screenshot? 😲

**Comment by hamenon** [comment]
That sounds great! Yup I meant if  the repository is hosted on github. 

PS: That screenshot was sent to me by someone in the team. Don't worry I'm in the process of converting him :smiley:
