### ISSUE TITLE
Simple publishing not working

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-vsce#110]
**Versions**
vsce version - 1.7.0 (latest)
node version - 4.1.2
OS - OS X 10.11.2

**What I am seeing**
```bash
➜  ext-git-blame git:(master) ✗ vsce publish
Executing prepublish script 'node ./node_modules/vscode/bin/compile'...
Error: Command failed: /bin/sh -c node ./node_modules/vscode/bin/compile
```

**What I have tried**
- uninstalled and reinstalled vsce
- logged out and logged back in
- logged out, revoked PAT and created a new one, and logged back in with new PAT

**Comment by joaomoreno** [comment]
@waderyan Odd.

What's the output of `node ./node_modules/vscode/bin/compile`?

**Comment by joaomoreno** [comment]
Possible duplicate of #104, in which the user has failed to provide more info.

**Comment by waderyan** [comment]
Looks like I had a syntax error (shame). 

```zsh
➜  ext-git-blame git:(master) node ./node_modules/vscode/bin/compile
src/extension.ts(91,1): error TS1005: '}' expected.
```

Fixed the error and was able to publish!
