### ISSUE TITLE
Error: Failed Request: Internal Server Error(500) - The supplied tag '' is not a valid tag. It must not be empty or start with a special character (!,@,#,$,%,^,&,*).

### ISSUE THREAD

**Issue by rtorr** [Microsoft/vscode-vsce#114]
I am seeing this error when trying to publish following the docs and using ` vsce publish 272.0.0`. Am I missing something? I see no mention of tags.

**Comment by joaomoreno** [comment]
Can you show me the contents of your `package.json`?

**Comment by joaomoreno** [comment]
Oh, found it: https://github.com/rtorr/vscode-flow

**Comment by joaomoreno** [comment]
Great catch, fix published with `vsce@1.8.1`.

**Comment by rtorr** [comment]
It worked, thanks!
