### ISSUE TITLE
images with relative paths in extension's README.md aren't shown in the extension manager

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-vsce#120]
_From @nadako on August 29, 2016 21:20_

- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1. Have an extension which has a README with images with relative path, e.g. https://raw.githubusercontent.com/vshaxe/vshaxe/master/README.md
2. Open extension manager, click on that extension - images aren't shown:

![](http://i.imgur.com/iqmry3h.png)

Note that those images are shown in Marketplace, on Github and when using VSCode's Markdown Preview feature.

_Copied from original issue: Microsoft/vscode#11136_

**Comment by joaomoreno** [comment]
@nadako I can't reproduce this on latest. Can you update to the latest `vsce`? `npm install -g vsce`

**Comment by nadako** [comment]
Actually, I just checked - images are shown in the UI when installing (or already installed) a package from the marketplace, but they aren't shown if your extension is in development mode (i.e. simply cloned into `.vscode/extensions`). This is inconvenient if you want to check how it'll look in the extension manager before packaging.

**Comment by joaomoreno** [comment]
Oh OK! That is something else, I can take a look at that.

**Comment by joaomoreno** [comment]
Let's handle it in Microsoft/vscode#11136 then
