### ISSUE TITLE
Create a new asset type for the Changelog file

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-vsce#126]
Similar to the Details asset type

**Comment by joaomoreno** [comment]
@XVincentX you can also contribute to getting this done.

Check out how VSCE maps README.md into the Details asset type. We gotta make the same for the CHANGELOG.md.

**Comment by XVincentX** [comment]
@joaomoreno Cool - I'll have a look later on. Stay tuned!

**Comment by XVincentX** [comment]
@joaomoreno 
From a quick view I'd say that [this](https://github.com/Microsoft/vscode-vsce/blob/9871b82a4237db00f0ba8abf3d094ee259ec283e/src/package.ts#L249) is our guy to modify; probably on the same way I did in the previous PR - that is - generalise it as a `Markdown` processor and probably provide a property where you could set the regexp to find the files.

Does that make sense for you?

**Comment by joaomoreno** [comment]
Spot on. 👍

**Comment by joaomoreno** [comment]
Thanks @XVincentX !
