### ISSUE TITLE
Upgrade libraries!

### ISSUE THREAD

**Issue by XVincentX** [Microsoft/vscode-vsce#127]
Different libraries over here had several upgrades; I think it would be worth try to give a round of updates especially for major version (see lodash and mocha)

**Comment by XVincentX** [comment]
Note: I tried to update it by myself and so far the only breaking change would be `lodash 4`
All the other deps (included the dev ones) work correctly.

**Comment by joaomoreno** [comment]
Done.

**Comment by XVincentX** [comment]
Cool...I made the same thing but I was not able to get tests passing...still I made the same changes in the code for lodash... 😱
