### ISSUE TITLE
Package properties file(s) & executables

### ISSUE THREAD

**Issue by riteshatsencha** [Microsoft/vscode-vsce#128]
Hi,

Is it possible to package properties file(s) & executable(s) with the extension? We have an extension that uses properties file and spins up an executable to do few things within an extension. Need to know how to package these files using VSCE. 

Is it even possible? 

Thank you,

Ritesh

**Comment by joaomoreno** [comment]
`vsce ls` lists all the files that will be packaged. Don't those files show up?

**Comment by riteshatsencha** [comment]
Executing ``` vsce ls ``` I run into error below.
```
Executing prepublish script 'node ./node_modules/vscode/bin/compile'...
Error: Command failed: node ./node_modules/vscode/bin/compile
```
Also, when packaging using ``` vsce ``` these files are not packaged with the extension.

**Comment by joaomoreno** [comment]
Can you update to the latest `vsce`? `npm install -g vsce`. The latest will print out the error message that your compile script returns.

**Comment by riteshatsencha** [comment]
I have the latest version installed. (1.12.0). Running ```vsce ls``` returns the same error as above.

**Comment by joaomoreno** [comment]
What does `node ./node_modules/vscode/bin/compile` return?

**Comment by riteshatsencha** [comment]
```
error TS17012: Too many JavaScript files in the project. 
Consider specifying the 'exclude' setting in project configuration to limit included source folders. 
The likely folder to exclude is '/users/ritesh.patel/code/vscode-extjs/test/'. 
To disable the project size limit, set the 'disableSizeLimit' compiler option to 'true'.
```

**Comment by joaomoreno** [comment]
Yeah!
