### ISSUE TITLE
vsce should add node_modules executables to path

### ISSUE THREAD

**Issue by gabelevi** [Microsoft/vscode-vsce#130]
In my package.json, I have something like

``` JavaScript
{
  ...
  "scripts": {
    "vscode:prepublish": "./compile.sh",
     "compile": "./compile.sh",
  }
}
```

And in `compile.sh` I have something like

```
babel ./lib --out-dir=./build --source-maps $@
```

`npm run compile` will use `node_modules/.bin/babel`. `vsce package` will use `/usr/local/bin/babel`.

I think you should run the `vscode:prepublish` script with the same environment that you run other scripts.

This caused me trouble recently, since running an extension via the debugger used one version of babel, but publishing used another.

**Comment by joaomoreno** [comment]
Fixed in 1.16.0
