### ISSUE TITLE
Changelog should be set as its own asset type

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-vsce#132]
`Microsoft.VisualStudio.Services.Content.Changelog`

**Comment by XVincentX** [comment]
That should be fairly easy.

**Comment by XVincentX** [comment]
Also - @joaomoreno I can see you changed some of my code after PR was merged.
I would have appreciated comments on my PR and iterate - don't be afraid to tell me that the thing is wrong.

**Comment by joaomoreno** [comment]
I'm not, I just don't think it was important to note. Your code was flawless. 👍  If I change on top of it it's just pure personal preference.
