### ISSUE TITLE
VSCE 1.17 not publishing project details on Mac

### ISSUE THREAD

**Issue by akamud** [Microsoft/vscode-vsce#140]
I just updated VSCE and I'm trying to publish my extension with the project details explained [here](https://blogs.msdn.microsoft.com/visualstudiomarketplace/2016/11/14/add-buildproject-details-to-your-extension-page-on-marketplace/).

I'm not sure if this is a VSCE problem, but even though all the info needed are there, the project details do not show up on the extension page.

[package.json](https://github.com/akamud/vscode-theme-onedark/blob/master/package.json)
[Extension page](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark)

Is this a VSCE issue?

**Comment by joaomoreno** [comment]
@hamenon Here's the XML generated from VSCE 1.17.0 for @akamud's extension.

As per #108, the `Microsoft.VisualStudio.Services.Links.GitHub` property is set, instead of the `Microsoft.VisualStudio.Services.Links.Repository` property.

What is wrong here?

```xml
<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011" xmlns:d="http://schemas.microsoft.com/developer/vsx-schema-design/2011">
  <Metadata>
    <Identity Language="en-US" Id="vscode-theme-onedark" Version="0.2.13" Publisher="akamud"/>
    <DisplayName>Atom One Dark Theme</DisplayName>
    <Description xml:space="preserve">One Dark Theme based on Atom</Description>
    <Tags>atom,theme,dark,one dark,color-theme</Tags>
    <Categories>Themes</Categories>
    <GalleryFlags>Public</GalleryFlags>
    <Badges><Badge Link="https://marketplace.visualstudio.com/items/akamud.vscode-theme-onedark" ImgUri="http://vsmarketplacebadge.apphb.com/version/akamud.vscode-theme-onedark.svg" Description="Extension version" /><Badge Link="https://marketplace.visualstudio.com/items/akamud.vscode-theme-onedark" ImgUri="http://vsmarketplacebadge.apphb.com/installs/akamud.vscode-theme-onedark.svg" Description="Extension installs" /><Badge Link="https://marketplace.visualstudio.com/items/akamud.vscode-theme-onedark" ImgUri="http://vsmarketplacebadge.apphb.com/rating/akamud.vscode-theme-onedark.svg" Description="Extension Rating" /></Badges>
    <Properties>
      <Property Id="Microsoft.VisualStudio.Code.Engine" Value="^0.10.1" />
      <Property Id="Microsoft.VisualStudio.Code.ExtensionDependencies" Value="" />
      
        <Property Id="Microsoft.VisualStudio.Services.Links.Source" Value="https://github.com/akamud/vscode-theme-onedark" />
        <Property Id="Microsoft.VisualStudio.Services.Links.Getstarted" Value="https://github.com/akamud/vscode-theme-onedark" />
        
          <Property Id="Microsoft.VisualStudio.Services.Links.GitHub" Value="https://github.com/akamud/vscode-theme-onedark" />
        
      
      <Property Id="Microsoft.VisualStudio.Services.Links.Support" Value="https://github.com/akamud/vscode-theme-onedark/issues" />
      <Property Id="Microsoft.VisualStudio.Services.Links.Learn" Value="https://github.com/akamud/vscode-theme-onedark" />
      <Property Id="Microsoft.VisualStudio.Services.Branding.Color" Value="#282C34" />
      <Property Id="Microsoft.VisualStudio.Services.Branding.Theme" Value="dark" />
      <Property Id="Microsoft.VisualStudio.Services.GitHubFlavoredMarkdown" Value="true" />
    </Properties>
    <License>extension/LICENSE.txt</License>
    <Icon>extension/icon.svg</Icon>
  </Metadata>
  <Installation>
    <InstallationTarget Id="Microsoft.VisualStudio.Code"/>
  </Installation>
  <Dependencies/>
  <Assets>
    <Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true" />
    <Asset Type="Microsoft.VisualStudio.Services.Content.Details" Path="extension/README.md" Addressable="true" /><Asset Type="Microsoft.VisualStudio.Services.Content.Changelog" Path="extension/CHANGELOG.md" Addressable="true" /><Asset Type="Microsoft.VisualStudio.Services.Content.License" Path="extension/LICENSE.txt" Addressable="true" /><Asset Type="Microsoft.VisualStudio.Services.Icons.Default" Path="extension/icon.svg" Addressable="true" />
  </Assets>
</PackageManifest>
```

**Comment by hamenon** [comment]
We do see an issue where a few extensions are not seeing the project details section. I have someone from the team looking into it now. Will update this thread as soon as learn more.

**Comment by hamenon** [comment]
@joaomoreno @akamud Just pulled the manifest contents from the db and I'm still seeing the Links.Repository field being used for the extension (I'm checking the current publisher version 0.2.13). Could you check the version of vsce that you are using?

`<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011" xmlns:d="http://schemas.microsoft.com/developer/vsx-schema-design/2011">
  <Metadata>
    <Identity Language="en-US" Id="vscode-theme-onedark" Version="0.2.13" Publisher="akamud" />
    <DisplayName>Atom One Dark Theme</DisplayName>
    <Description xml:space="preserve">One Dark Theme based on Atom</Description>
    <Tags>atom,theme,dark,one dark,vscode,__market</Tags>
    <Categories>Themes</Categories>
    <GalleryFlags>Public</GalleryFlags>
    <Properties>
      <Property Id="Microsoft.VisualStudio.Services.Links.Source" Value="https://github.com/akamud/vscode-theme-onedark" />
      <Property Id="Microsoft.VisualStudio.Services.Links.Getstarted" Value="https://github.com/akamud/vscode-theme-onedark" />
      <Property Id="Microsoft.VisualStudio.Services.Links.Repository" Value="https://github.com/akamud/vscode-theme-onedark" />
      <Property Id="Microsoft.VisualStudio.Services.Links.Support" Value="https://github.com/akamud/vscode-theme-onedark/issues" />
      <Property Id="Microsoft.VisualStudio.Services.Links.Learn" Value="https://github.com/akamud/vscode-theme-onedark" />
      <Property Id="Microsoft.VisualStudio.Services.Branding.Color" Value="#282C34" />
      <Property Id="Microsoft.VisualStudio.Services.Branding.Theme" Value="dark" />
    </Properties>
    <License>extension/LICENSE.txt</License>
    <Icon>extension/icon.svg</Icon>
    <PublisherDetails>
      <DisplayName>Mahmoud Ali</DisplayName>
    </PublisherDetails>
  </Metadata>
  <Installation>
    <InstallationTarget Id="Microsoft.VisualStudio.Code" />
  </Installation>
  <Dependencies />
  <Assets>
    <Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true" />
    <Asset Type="Microsoft.VisualStudio.Services.Content.Details" Path="extension/README.md" Addressable="true" />
    <Asset Type="Microsoft.VisualStudio.Services.Content.License" Path="extension/LICENSE.txt" Addressable="true" />
    <Asset Type="Microsoft.VisualStudio.Services.Icons.Default" Path="extension/icon.svg" Addressable="true" />
  </Assets>
</PackageManifest>`

**Comment by akamud** [comment]
I just double checked the version I'm using:

<img width="329" alt="screen shot 2016-11-16 at 08 10 13" src="https://cloud.githubusercontent.com/assets/954102/20343194/90ff1074-abd4-11e6-8553-0678a96ef54b.png">

I just tried publishing a new version again and I saw that the manifest file now had the GitHub node and the project info is now being displayed.
I'm sure I had VSCE 1.17 before, because I didn't update it now and I checked before I opened the issue. 
What I think might have happened is that I did not restart my terminal after updating. Does this make sense?

**Comment by joaomoreno** [comment]
Hm... it could also have been some Marketplace cache issue. @hamenon ?

**Comment by hamenon** [comment]
I doubt it's a cache issue, since the details page will always read from the latest version of the extension.  Not sure how the older version of manifest ended up there.

**Comment by akamud** [comment]
I have two more extensions on the marketplace that I'll be updating in the upcoming days. I'll report back if this issue happens again so we can investigate.

Thanks for the help.
