### ISSUE TITLE
While Publishing Csharp snippet getting error 

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-vsce#141]
> from @rahulsahay19

- VSCode Version: 1.7.1
- OS Version: Win 10. 64 Bit (Pro Edition)

Steps to Reproduce:

1. I have attached two files. Package.json and csharp.json.
2.  I am using vsce commands to publish the same.

package.json link:- [package.json](https://gist.github.com/rahulsahay19/216476659e713082ed8a6c85725e9d88)
csharp.json link:- [csharp.json](https://gist.github.com/rahulsahay19/d3e27b3720de1efed27be4d2e725adf3)

I am executing command vsce publish. All pre-requisties with vsce publish, I have already done. 
Error coming:- C:\>vsce publish
glob error { Error: EPERM: operation not permitted, scandir 'C:\Documents and Settings'
    at Error (native)
  errno: -4048,
  code: 'EPERM',
  syscall: 'scandir',
  path: 'C:\\Documents and Settings' }
Error: EPERM: operation not permitted, scandir 'C:\Documents and Settings'

Kindly correct me if I am doing any mistake. This is I am doing for 1st time. Thanks in advance. 

Thanks,
Rahul

**Comment by joaomoreno** [comment]
@rahulsahay19 Where in your computer is located the parent folder of `package.json`?

**Comment by rahulsahay19** [comment]
Its located c drive directly as package.json. Here only vsce publish command is expecting the file

**Comment by joaomoreno** [comment]
Can you show me the *exact* full file path of `package.json`?

**Comment by rahulsahay19** [comment]
C:\package.json. This is it.

**Comment by joaomoreno** [comment]
Please create an empty folder, put `package.json` and `csharp.json` inside and run `vsce publish` from there.

**Comment by rahulsahay19** [comment]
Thanks. Done! You can close the ticket!
