### ISSUE TITLE
Error: Failed Request: Not Found(404) when publishing an extension.

### ISSUE THREAD

**Issue by markbrocato** [Microsoft/vscode-vsce#145]
I followed the steps here, https://code.visualstudio.com/docs/tools/vscecli, but get the following when trying to publish:

```bash
Marks-MBP:vscode-extjs mbrocato$ vsce publish
Executing prepublish script 'npm run vscode:prepublish'...

> vscode-extjs@1.0.0 vscode:prepublish /Users/mbrocato/Code/vscode-extjs
> tsc -p ./

Couldn't detect the repository where this extension is published. Images might be broken in its README.
Publishing sencha.vscode-extjs@1.0.0...
Error: Failed Request: Not Found(404) - 
```

**Comment by joaomoreno** [comment]
Did you go through the FAQ?

https://github.com/Microsoft/vscode-docs/blob/master/docs/tools/vscecli.md#common-questions

**Comment by markbrocato** [comment]
I did.  In fact the first time I didn't select "all accessible accounts" and vsce was nice enough to specifically tell me that was the issue.  Once I corrected that I started getting the 404 I mentioned above.

**Comment by markbrocato** [comment]
Might it be the size of our extension?  It's 29 mb.  I tried uploading via the website and it said there is a limit of 20 mb.  That seems nearly impossible to reach given the bloat you get from npm these days.  Please tell me you can bump up that limit.

**Comment by joaomoreno** [comment]
Unfortunately, it is really limited to 20MB for now. 😢  You gotta try to reduce those dependencies.

ping @hamenon

**Comment by markbrocato** [comment]
At least 4mb of that is the vscode package itself.  I've tried moving that from dependencies to devDependencies, but then none of my extension's commands work.  Any idea how I can debug this?  Does vscode produce any kind of a log file that would contain information about why an extension is not being activated?

**Comment by joaomoreno** [comment]
Well you should be able to [debug it](https://code.visualstudio.com/docs/extensions/example-hello-world#_debugging-your-extension).

If you have dependencies which are only dev-time, you should definitely move them there.

**Comment by wojciechsura** [comment]
The generator created node_modules folder, which is quite big (44 Mb). All these modules has been created by the tool, not me. I use 2 of them (excluding vscode). How can I remove unnecessary modules?

**Comment by joaomoreno** [comment]
@wojciechsura `vsce` should only pick up the `dependencies`, not `devDependencies`. Are all those MB real (non dev) dependencies?
