### ISSUE TITLE
Can I publish a specific vsix file, rather than rebuild?

### ISSUE THREAD

**Issue by markbrocato** [Microsoft/vscode-vsce#146]
I'd strongly prefer to publish a specific vsix build from our CI that has been tested rather than creating a new build during publishing.  Is that possible?

**Comment by joaomoreno** [comment]
`vsce help publish` will lead you to `vsce publish --packagePath VSIX_FILE`

**Comment by roonyh** [comment]
`vsce publish --help` worked for me
