### ISSUE TITLE
Improve documetation: the --packagePath option is hard to discover

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/vscode-vsce#147]
I only found it by delving into the source code (here: https://github.com/Microsoft/vscode-vsce/blob/master/src/main.ts#L73)

The docs here:

https://code.visualstudio.com/docs/tools/vscecli

Do not mention it.

And I tried using commands like `vsce --help publish` also without much luck.

**Comment by joaomoreno** [comment]
`vsce publish --help` works. Created #149.

**Comment by Tyriar** [comment]
I just hit this, I expected `vsce help publish` to show me. My thinking was if `--help` wasn't supported properly then `vsce publish --help` could have possibly published something.

**Comment by joaomoreno** [comment]
@Tyriar We can make `vsce help COMMAND` work too, wanna make a PR?
