### ISSUE TITLE
vsce package command not including node_modules directory

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-vsce#150]
_From @indiejames on January 12, 2017 15:14_

- VSCode Version: 1.8.1
- OS Version: OS X Sierra

Steps to Reproduce:

1. Create extension
2. Run npm install to create node_modules directory
3. Run vsce package in extension directory
4. unzip .vsix file
5. No node_modules

_Copied from original issue: Microsoft/vscode#18455_

**Comment by joaomoreno** [comment]
@indiejames What's inside your `.vsceignore` file?

**Comment by indiejames** [comment]
Yeah, that's the problem:

node_modules/**/*

I don't recall creating a `.vsceignore` file. Does that get created by default?

**Comment by joaomoreno** [comment]
I don't think so.

**Comment by fgodoy** [comment]
Hi, I don't have .vsceignore and I tried everything but my node_modules never was included in the VSIX package. I'm using vsce package command. 
Maybe this folder be always ignored?

**Comment by joaomoreno** [comment]
Is your dependency listed in `package.json`?

**Comment by fgodoy** [comment]
Yes, like a screenshot

![sc](https://cloud.githubusercontent.com/assets/2242629/25132588/6953a7aa-2420-11e7-866d-5b0ba2f10b55.png)

**Comment by joaomoreno** [comment]
Well, if it's a `devDependency` why should it be included along with the extension?

**Comment by fgodoy** [comment]
Maybe I missed something. There are another place to put this dependency? I tested installing the extension and doesn't work, than I checked the installation path of extension and copy manually the node_modules (electron_edge), than extension works.

**Comment by fgodoy** [comment]
Now works. I changed package.json (see image below). Thanks a lot for help. ;)

![image](https://cloud.githubusercontent.com/assets/2242629/25138787/ceff9d5a-2431-11e7-8195-b104010b1ec2.png)
