### ISSUE TITLE
Publishing from Windows strips Linux file-system execute bit for embedded scripts

### ISSUE THREAD

**Issue by DavidAnson** [Microsoft/vscode-vsce#152]
Please see https://github.com/DavidAnson/vscode-markdownlint/issues/4 for more details.

Briefly:

* Extension `vscode-markdownlint` depends on a package that includes a script it executes on Linux
* That file needs its `execute` bit set during extraction for the OS to be able to execute it
* Building and packaging on Windows does not preserve the `execute` bit for the file

One option is for `vsce` to support this workflow. Another - for the specific scenario in the issue above - is for VS Code to provide a [complex command](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands) to open a URL in the default browser.

Thanks for your consideration.

**Comment by joaomoreno** [comment]
How can `vsce` support this workflow? The file about to be packaged is in fact in an NTFS fs, it doesn't have the `execute` bit to begin with.

If you want to open a URL in the default browser, just use https://github.com/sindresorhus/opn.

**Comment by DavidAnson** [comment]
Per the linked issue, the `opn` package is the one that triggered this problem in the first place!

The situation today is that publishing the exact same extension from Windows vs. Linux gives different behavior.

It would be nice if extension authors were not required to discover this independently. Perhaps a note could be added to the documentation?

**Comment by joaomoreno** [comment]
I don't understand. You want to add to `vsce`'s documentation that Linux file system attributes don't work on Windows file systems?

**Comment by DavidAnson** [comment]
One of the key rules of a build/packaging system is that it produce reliable output. This issue means that vsce does not do that, outputting extensions with different behavior based on the OS on which it was run. I view that as a problem, though I grant that it only affects a subset of all extensions. My ideal scenario would be for vsce to package reliably, but that was rejected and so I proposed a documentation change to raise awareness.

The claim that this is not a vsce issue is one I disagree with; it is the official tool for packaging extensions and it could be modified to handle this scenario correctly on Windows by packaging from dependency archives instead of the file system (for example). (Archives include the relevant bit which is how this scenario works for npm and from Linux.)

**Comment by joaomoreno** [comment]
Doesn't the issue start once the file gets placed in the Windows file system, thus losing whatever POSIX flags it once had, and not at the time vsce packages it?

**Comment by DavidAnson** [comment]
Agreed. Were this to be fixed (and I'm not sure it's a common enough problem to require that), one approach might be to populate the extension package from files extracted directly from npm tarball (which includes the execute bit), bypassing the file system entirely. Alternatively, the tarball could be used only to identify files that need this bit set (and setting it), and the rest of the packaging process left unchanged. Finally, a different kind of approach could be to change the packager to strip the execute bit when running on Linux, thereby breaking scripts regardless of platform.

**Comment by joaomoreno** [comment]
Got it. I've documented this in our docs:

https://github.com/Microsoft/vscode-docs/commit/aaced51d5dfc430d293af8a88dd1fc8e8e99daba

**Comment by DavidAnson** [comment]
Beautiful, thank you!
