### ISSUE TITLE
Missing Changelog link in Marketplace

### ISSUE THREAD

**Issue by mirao** [Microsoft/vscode-vsce#155]
I've published an extension containing CHANGELOG.md in root folder. I can see the correct changelog in VSCode: the tab `Extensions -> Changelog`, but there is missing link to changelog in Marketplace in Resources.

URL: https://marketplace.visualstudio.com/items?itemName=mirao.mads, version 0.0.3

I know that I published the extension with some older version of vsce tool (I got an info about new version after I published it).

Any idea?

**Comment by joaomoreno** [comment]
You have to update to the latest `vsce`.

**Comment by mirao** [comment]
Great, republishing with new version (`1.18.0`) helped. Thank you.
