### ISSUE TITLE
Link to Documentation in ReadMe.md is invalid

### ISSUE THREAD

**Issue by PaulStubbs** [Microsoft/vscode-vsce#164]
The link to the documentation returns a 404. This is the invalid url https://github.com/Microsoft/vscode-docs/blob/master/docs/tools/vscecli.md

I looked but couldn't find it in the https://github.com/Microsoft/vscode-docs repo.

**Comment by joaomoreno** [comment]
Thanks @PaulStubbs 

cc @gregvanl
