### ISSUE TITLE
Cannot publish an extension to the VSCode marketplace

### ISSUE THREAD

**Issue by Jarrio** [Microsoft/vscode-vsce#166]
Attempting to run `vsce publish` results in `Error: Access Denied: <vscode username> needs the following permission(s) on the resource /jarrio to perform this action: Publish new extensions to an existing publisher`

![creatingtoken](https://cloud.githubusercontent.com/assets/748557/25235404/f16d5dda-25dc-11e7-841b-5b77e20e4139.png)

I definitely created the access token with the recommended setting and I have even tried creating multiple others while selecting individual scope(s) of `marketplace (publish)`.  Some advice would be much appreciated

**Comment by joaomoreno** [comment]
cc @hamenon

**Comment by hamenon** [comment]
cc @gaurav42
@Jarrio Could you check the username (email) that you are using to generate the login. The publisher id on the Marketplace is owned by an live.uwe.ac.uk address. But our logs show that the failed requests were all coming from an googlemail.com address. You need to login to VSTS with the same address (ie the live one) to generate the PAT.

**Comment by gaurav42** [comment]
@Jarrio it is important that when did you create the PAT. If you created PAT, when you logged in using live id and accessed jarrio.visualstudio.com, then it won't work. 

Log in to jarrio.visualstudio.com using your gmail id and then create the PAT again. Using this new PAT, you should be able to publish the extension.

**Comment by Jarrio** [comment]
I was not logged into the live id when creating the PAT. The live id does not have any PAT's on the account, but just to be sure I tried doing everything again from an incognito window.

![image](https://cloud.githubusercontent.com/assets/748557/25309519/b9ece154-27c7-11e7-8684-1fb958965f94.png)

I am logged into the `googlemail.com` account and created a new PAT key which yields the same error message. Maybe the error message is referring to something else?

**Comment by gaurav42** [comment]
You need to add your google email to the publisher as owner.
1. Go to https://marketplace.visualstudio.com/manage/publishers/jarrio 
2. Click on publisher name and select 'Edit publisher' option from dropdown
3. Select 'Role' and add your google email with role as owner

After this try publishing extension.

**Comment by Jarrio** [comment]
![image](https://cloud.githubusercontent.com/assets/748557/25335231/158b26f6-28ea-11e7-8350-05ba36560d6e.png)
The user is already in the list

**Comment by gaurav42** [comment]
Can you still follow above steps and try? Our DB suggests that only live id had access to jarrio publisher.

**Comment by Jarrio** [comment]
Trying to add it to `Owner` results in an error message saying `Sorry, we couldn't find that user. Please try a different email address.`

As a side-note the live address shouldn't even be involved anymore as jarrio has been deleted from that account and it no longer appears under the "Accounts pending deletion" dropdown

**Comment by gaurav42** [comment]
Try following steps:
1. Open incognito window and visit https://marketplace.visualstudio.com/manage/publishers/jarrio
2. Log in using '@live.uwe.ac.uk' email id
3. If you see following dropdown and 'Microsoft Account' is selected in it, then change it to other option in the dropdown:
![image](https://cloud.githubusercontent.com/assets/13743203/25337957/4681999e-291b-11e7-8908-5ba539b1ce45.png)

4. Now again click on publisher name and select 'Edit publisher' option from dropdown
5. Add '@googlemail.com ' email id.

If it still fails, then we will grant permissions explicitly.

**Comment by Jarrio** [comment]
That worked! One additional question though, is there any way to completely remove control from the live account? I won't have access to this email address once university has finished which is why I never wanted to create the account on there in the first place

**Comment by gaurav42** [comment]
To delete the publisher, again go to 'Edit Publisher' dialog. On hovering over the publisher row, you will see remove button like this:
![image](https://cloud.githubusercontent.com/assets/13743203/25341443/718e773c-2926-11e7-8946-49bec62e7376.png)

Just click on remove button and save.

**Comment by Jarrio** [comment]
Thank you for all your help!
