### ISSUE TITLE
Packager corrupts electron module

### ISSUE THREAD

**Issue by RationalCoding** [Microsoft/vscode-vsce#168]
I am trying to spawn an `electron` process from an extension. Everything works fine in the Extension Host, but when I package and publish to the marketplace, the downloaded extension has been changed. It seems the electron install is the only affected module.

1. The size of the `Electron.app` contained within the module is significantly smaller, suggesting a lot has been removed. `185.8mb` vs `115.7mb`

2. Many alias within the app contents have been removed, breaking some important symlinks. Some alias have been converted into their target files.

**Correct Install**:
<img width="204" alt="screen shot 2017-04-23 at 2 02 32 pm" src="https://cloud.githubusercontent.com/assets/14932492/25316042/a80588a4-282d-11e7-8537-3b4d0efa1fd6.png">

**Install after packaging**:
<img width="204" alt="screen shot 2017-04-23 at 2 02 27 pm" src="https://cloud.githubusercontent.com/assets/14932492/25316043/b376119a-282d-11e7-9554-8b7e0c2d8aa3.png">

Because of this, the extension crashes immediately due to several Electron binaries being missing.

Why does the packager modify the contents of modules so significantly? Manually replacing the corrupted Electron.app with the original one works fine.

**Comment by joaomoreno** [comment]
Other than symlinks, what is missing?

Overall this seems like a pretty bad idea, though. Remember that users can install your extension on Linux, Windows and macOS. You can't ship Electron for all those platforms in an extension, simply because of the extension file limit (100MB).

What is your extension trying to achieve?

**Comment by RationalCoding** [comment]
You're right. I ended up just using existing Electron installs on the system or installing it if none exists.

Going to close this because I doubt anyone else will have this issue, but it's still strange that the packager modifies the extension like this.
