### ISSUE TITLE
EPERM: operation not permitted, scandir

### ISSUE THREAD

**Issue by leninalbertolp** [Microsoft/vscode-vsce#169]
Hi guys, I'm getting the following error when I try to upload the update from my published extension in the marketplace, if anyone can guide me to that it should.

C:\Users\myname>vsce publish
glob error { Error: EPERM: operation not permitted, scandir 'C:\Users\myname\Configuración local'
    at Error (native)
  errno: -4048,
  code: 'EPERM',
  syscall: 'scandir',
  path: 'C:\\Users\\myname\\Configuración local' }
Error: EPERM: operation not permitted, scandir 'C:\Users\myname\Configuración local'

**Comment by joaomoreno** [comment]
Did you check permissions on that folder? Can your user access it?

**Comment by leninalbertolp** [comment]
@joaomoreno Yes, I can access perfectly

**Comment by joaomoreno** [comment]
I can't seem to reproduce here. If you could build vsce in your machine and debug it, woudl you do it? I could write up a guide of how to do this.

**Comment by leninalbertolp** [comment]
how sorry but I'm a noob and not be as do what I asked

**Comment by leninalbertolp** [comment]
I solved the issue, what I did was run console from the folder with the extension files and ran smooth as silk. I've already updated smoothly. You can close this ticket
