### ISSUE TITLE
[theme] Workbench button.foreground doens't work

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode-vsce#170]
The workbench theme key `button.foreground` doesn't change the buttons foreground that still remain white `#FFFFFF`

PS: Could be awesome to have also `button.hoverForeground`, not only `button.hoverBackground`

**Comment by joaomoreno** [comment]
Did you intend to file this in [the vscode repository](https://github.com/Microsoft/vscode/issues)?

**Comment by equinusocio** [comment]
Oh sorry. Thanks
