### ISSUE TITLE
500 when publish a new version

### ISSUE THREAD

**Issue by zjhmale** [Microsoft/vscode-vsce#171]
Hi, when I released a new version of my extension https://github.com/zjhmale/vscode-idris, there will be a `Failed request` stands there, and there is no error log I can check out, it works for the previous version, any ideas to fix this? Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/6234553/25732447/3d17041a-3182-11e7-941c-e0ad65da844a.png)

**Comment by joaomoreno** [comment]
@zjhmale Which version do you have?

cc @modigrv

**Comment by zjhmale** [comment]
Hi, @joaomoreno I'm currently using version 1.20.0, I think it is the latest release.

**Comment by joaomoreno** [comment]
```
du -hs Idris-0.9.6.vsix
102M	Idris-0.9.6.vsix
```

The Marketplace has a 100MB limit on extensions. Do you really need 102MB for your extension? The `images` folder alon in your repository has 107MB.

**Comment by zjhmale** [comment]
@joaomoreno Thanks! I will add them to `.vsceignore` and move the `FEATURES` page to GitHub wiki probably 😅
