### ISSUE TITLE
vsce package command hangs when run during a publish hook

### ISSUE THREAD

**Issue by dsifford** [Microsoft/vscode-vsce#172]
### How to reproduce

Create a `package.json` similar to below:

```json
{
  "scripts": {
    "build": "vsce package -o ./bin/extension.vsix",
    "vscode:prepublish": "npm run build"
  }
}
```

Run any command that triggers the `vscode:prepublish` hook. (`vsce ls` works fine for this example).

### What happens

The command hangs forever

### What I expected

The command to package an extension and exit without hanging.

**Comment by dsifford** [comment]
Ah, I think I see what's happening... I cant add `vsce package` to the prepublish hook because calling `package` also calls `prepublish` so it results in an infinite loop.

Any workaround here?

**Comment by joaomoreno** [comment]
Work around what? What do you want to achieve with this?

**Comment by dsifford** [comment]
@joaomoreno The ideal situation for what I was looking to do was to just be able to optionally skip the prepublish hook step for the package command. 

The "why" for this is because I think it would be nice to be able to add the package step into the prepublish hook itself. That way I can build the extension locally as many times as necessary while working on it and only call the package command when publishing version changes. 

By doing it that way, after publishing, all I need to do is create a github release and drag and drop the matching `vsix` binary onto it without having to think about it.

This is arguably moot and probably won't save that much time or effort, but I think it would still be a nice little option to have.

Thanks for considering! 😄

**Comment by joaomoreno** [comment]
I'd just not use the `vscode:prepublish` script and instead of optionally skipping it, I'd optionally run it. :)
