### ISSUE TITLE
Flag or command to print all files that will be included in package

### ISSUE THREAD

**Issue by adamvoss** [Microsoft/vscode-vsce#175]
It would be useful if there were either a flag to `vsce package` (`--dry-run`??) or a separate command that would print the files that would be included in the package without actually creating the package.

This would be helpful in trying to debug/correct `.vscodeignore` would out needing to generate the package only to inspect the contents.

I have already had two situations where I needed to do this debugging.  One was in expecting `.vscodeignore` to have the same semantics as `.gitignore` and then finding files I thought should be excluded ended up in my package.  The other was using `files:` in `package.json` (not realizing it wasn't applicable) and then finding files missing from my package.

**Comment by joaomoreno** [comment]
`vsce list`
