### ISSUE TITLE
Support version bump for package-lock.json when publishing

### ISSUE THREAD

**Issue by JimiC** [Microsoft/vscode-vsce#180]
For those using `npm 5`, `package-lock.json` is added in the project, which also contains a `version` property.

Whenever publishing an extension, the version should be bumped in `package.json` and `package-lock.json` to keep them in sync.

**Comment by joaomoreno** [comment]
Wanna try submitting a PR?

**Comment by JimiC** [comment]
Yeah, I tried looking at the code but didn't felt confident tampering with it. I believe @robertohuertasm has more experience with it and maybe he can assist.

**Comment by felixfbecker** [comment]
Why is it vsce's responsibility to bump versions? Why not use `npm version`?

**Comment by JimiC** [comment]
@felixfbecker Because `vsce` is bumping the `package.json` version on publish (https://github.com/Microsoft/vscode-vsce/blob/83060c333a56aac26019df204af4ae948c041326/src/publish.ts#L87)

**Comment by felixfbecker** [comment]
I understand that vsce provides this feature, but I am questioning whether it should be as it is already provided by npm itself

**Comment by JimiC** [comment]
@felixfbecker Could you please elaborate? I'm not so familiar with `npm 5` and its features, as it's fairly new and still evolving.

**Comment by JimiC** [comment]
@felixfbecker No need to elaborate. I figured out what you want to say. Still though, although you can bump the version of `package.json` and `package-lock.json` with `npm version`, `vsce` provides the ability to bump the version from the tool. And while the tool does bump the version of `package.json` it should take into consideration the existence of `package-lock.json` file as well.

**Comment by felixfbecker** [comment]
Imo the functionality should just be deprecated. `npm version` is guaranteed to always work with all lockfiles and shrinkwrap, it can also commit and tag the new version. So vsce doesn't add value here, but inevitably will have bugs like this issue that need work over time to fix

**Comment by JimiC** [comment]
@felixfbecker That's an entirely new proposal. Maybe you should open an issue and promote it.

/cc @joaomoreno

**Comment by joaomoreno** [comment]
I have to agree with @felixfbecker. We should reuse as much as possible. We might just deprecate this behaviour from vsce altogether.

Closing this issue as it becomes obsolete.

**Comment by JimiC** [comment]
Good to know. Precious development time saved.
