### ISSUE TITLE
Error: SVGs can't be used as icons

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode-vsce#181]
After upgrade from 1.22 to 1.26, it says that

```
Error: SVGs can't be used as icons: images/foo.svg
```

I think at least there should be a notice since it is a 'breaking' change. Which kind of icon is supported? Which size is it should be?

**Comment by xconverge** [comment]
It looks like this:

https://github.com/Microsoft/vscode-vsce/commit/7cf67ddb52021a9ae055365f2bb25c10eaff0a01

I have the problem of a slack badge now is a non trusted source

**Comment by eamodio** [comment]
I'm running into the same -- why was this changed?

**Comment by joaomoreno** [comment]
Changes are indeed coming on the SVG support in the Marketplace. More information in the upcoming release notes: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_14.md#changes-for-extension-authors

**Comment by eamodio** [comment]
@joaomoreno does that mean that extensions can't have any SVG resources? Or only in the marketplace resources?

**Comment by joaomoreno** [comment]
Only in the Marketplace resources. 👍
