### ISSUE TITLE
Error: SVGs cannot be used as icons

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-vsce#183]
Just wanted to a release a new version of PHP IntelliSense, but the build broke:
https://travis-ci.org/felixfbecker/vscode-php-intellisense/builds/247593000#L917

I have been using an SVG as an icon forever and that has always worked fine:
https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense

**Comment by LaurentTreguier** [comment]
I am experiencing that issue as well. The message looks like it's intentional though (`Error: SVGs are restricted in README.md; please use other file image formats, such as PNG`)... But forbidding SVG's while they didn't pose any problem before seems like a weird decision to me.

**Comment by felixfbecker** [comment]
yeah, especially since
- this was not a major release
- SVGs are just objectively better than PNGs

**Comment by LaurentTreguier** [comment]
So [this commit](https://github.com/Microsoft/vscode-vsce/commit/e0dff61012b5d2bb8c088b9c799bd4ad0e68dcec) is responsible, somebody asked why and got no answer =/
Only trusted sources are allowed now apparently

**Comment by joaomoreno** [comment]
The same answer from #181:

Changes are indeed coming about SVG support in the Marketplace. More information in the upcoming release notes: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_14.md#changes-for-extension-authors

It's a sad restriction but a necessary one.

**Comment by felixfbecker** [comment]
Instead of throwing an error, how about silently converting the SVG to a PNG with https://www.npmjs.com/package/svg-to-png?

**Comment by luanpotter** [comment]
Hey... github actions generates a svg badge and there is no way to get a PNG badge:
https://github.community/t/png-image-for-actions-badge/18178
In fact, there is one in this repo's readme! (which of course is not a vscode plugin)

Can't we support at least badges as svgs, or convert, or just ignore them instead of the error (I don't care a lot for a build sucess badge on the store page but I do care about it on my project repo)?

Otherwise I can't see how to cleanly interop github actions and vscode...

**Comment by ipatalas** [comment]
@luanpotter same here. This is still not fixed. I can't add GH Actions badge because it's SVG :/

**Comment by joaomoreno** [comment]
The VS Marketplace now has an open issue tracker, feel free to submit this feature request over there: https://github.com/microsoft/vsmarketplace

**Comment by SNDST00M** [comment]
Is `help-wanted` on this?
