### ISSUE TITLE
When vsce publish fails, version still gets bumped

### ISSUE THREAD

**Issue by idleberg** [microsoft/vscode-vsce#187]
When running `vsce publish <major|minor|patch>` and something goes wrong, e.g. `vscode:prepublish` throwing an error, the version numbers still get bumped.

**Example**:

```bash
$ vsce publish major
Executing prepublish script 'npm run vscode:prepublish'...
Error: Command failed: npm run vscode:prepublish
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-package@1.0.0 vscode:prepublish: `tsc -p ./`
npm ERR! Exit status 1 

# after fixing the error
$ vsce publish major
Executing prepublish script 'npm run vscode:prepublish'...

>  my-package@2.0.0 vscode:prepublish /path/to/my-package
```

Note that after the first publish command, the version gets bumped to `1.0.0`. After fixing the error that caused prepublish script to exit, the version gets bumped to `2.0.0`. The expected behaviour is to bump to 1.0.0, since it failed earlier.

I should also mention, that the version in `package.json` remains unchanged after the failed publish command.

**Comment by TheColorRed** [comment]
It would be nice if an error occurs that vsce would rollback to the previous version. I pushed some code it was supposed to be `0.0.12`, but it didn't work. By the time it worked it pushed as `0.0.14` and now my `CHANGELOG.md` is wrong.
