### ISSUE TITLE
vsce fails to finish with node 8

### ISSUE THREAD

**Issue by Jason3S** [Microsoft/vscode-vsce#194]
Trying to publish my extension: [vscode spell checker](https://github.com/Jason-Rev/vscode-spell-checker) fails to complete when using node 8.

## Info
```
vsce -V
1.29.0
```

## Steps:

1. `nvm use 8`
2. `vsce publish`

The process clearly run all the pre-publish steps:
```
Executing prepublish script 'npm run vscode:prepublish'...

> code-spell-checker@1.3.0 vscode:prepublish /Users/jason/projects/vscode-spell-checker/client
> npm run clean-build


> code-spell-checker@1.3.0 clean-build /Users/jason/projects/vscode-spell-checker/client
> npm run clean && npm run build


> code-spell-checker@1.3.0 clean /Users/jason/projects/vscode-spell-checker/client
> rimraf out


> code-spell-checker@1.3.0 build /Users/jason/projects/vscode-spell-checker/client
> tsc -p ./
```

but then it hangs with node using 100% cpu for 1 thread.

## Workaround
Use Node 7

1. `nvm use 7`
2. `vsce publish`
 
Every thing worked, extension published.

**Comment by JimiC** [comment]
Just used `vsce package` on `vscode-icons`, with `vsce v1.29.0`, `nvm use 8.2.1` which includes `npm v5.3.0` and had no issues. Maybe `node v8` had issues that since then were resolved.

**Comment by Jason3S** [comment]
Thank you. My version of `npm` was older.  I'll try with `5.3.0` soon.

**Comment by Jason3S** [comment]
This seems to be fixed.
