### ISSUE TITLE
Report non-SemVer version during publishing

### ISSUE THREAD

**Issue by JustusAdam** [Microsoft/vscode-vsce#195]
Version numbers for extensions must use the format `x.z.y`. 
Common derivatives and shorthands such as `1` for `1.0.0` or `2.0` for `2.0.0` do not work and lead to the extension not being installable. 
Even when searching for it in the extension tab it reports `Invalid version ...` and does not show the page.
It does however work on the website!

I suggest adding a check in the `vsce` publishing tool to confirm that the version of an extension specified in `package.json` conforms to the `x.y.z` format and otherwise reject the upload.
I maintain the `language-haskell` extension and it has happened to me twice now that I moved to a new minor/major release and I wanted to use the shorthand `x.y` and ended up publishing a broken package.

**Comment by joaomoreno** [comment]
Actually this should be happening:

https://github.com/Microsoft/vscode-vsce/blob/master/src/validation.ts#L30

And I do see the validation when running `vsce package`:

```
banana master* → vsce package
Error: Invalid extension version '0.5'
```

**Comment by JustusAdam** [comment]
Oh. I'm running `0.8.1`

**Comment by joaomoreno** [comment]
Get that guy bumped up 👍

**Comment by JustusAdam** [comment]
Dang ... I just updated to `1.29.0`. I didn't realize I was so far behind 🙈

**Comment by joaomoreno** [comment]
No worries... we do have an update mechanism in there... might've been added a bit after 0.8.1.
