### ISSUE TITLE
What is "Invalid Resource" Error?

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode-vsce#198]
vsce: 1.22.0
node: 8.2.1
mac: 10.12.5

As I try to publish my theme ([market place](https://marketplace.visualstudio.com/items?itemName=karyfoundation.theme-karyfoundation-themes) / [repo](https://github.com/karyfoundation/kf-theme-vscode)) I get this output:

```
Publishing karyfoundation.theme-karyfoundation-themes@15.0.0...
Error: Invalid Resource
```

And I checked `vsce`'s source code and there was no such string as "Invalid Resource".
Why is this? what is this? how can I sent you memory dump or anything to help?

**Comment by joaomoreno** [comment]
A small search would've led you here: #196

This is likely the issue:

> This error is being thrown because the PAT used for publishing is no longer valid. 
You can create a new PAT to authenticate the publish - https://www.visualstudio.com/en-us/docs/setup-admin/team-services/use-personal-access-tokens-to-authenticate#create-personal-access-tokens-to-authenticate-access
You can pass PAT as a parameter in the publishing step via a -p or -pat option in the vsce tool.

**Comment by pmkary** [comment]
I searched both within google and github and even quoted, might have been of my bad luck. However thanks a lot for your time and answering it.

**Comment by joaomoreno** [comment]
Let me know if the suggestion doesn't fix it. 👍 

Also, I'll make sure we display a better message in this case, since it seems people are hitting it quite a bit lately.

**Comment by pmkary** [comment]
Thanks a lot! that was the case and it's now fixed! thanks again for your time.
