### ISSUE TITLE
invalid resource when publishing

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-vsce#200]
I'm trying to publish an update to the [vscode-azure-pack](https://github.com/microsoft/vscode-azure-pack) extension.  I can package fine, but when I try to publish I get an "Invalid Resource" error.

``` console
~/src/vscode-azure-pack$ vsce package
Created: /Users/chris/src/vscode-azure-pack/vscode-azureextensionpack-0.0.5.vsix
~/src/vscode-azure-pack$ vsce publish
Publishing ms-vscode.vscode-azureextensionpack@0.0.5...
Error: Invalid Resource
~/src/vscode-azure-pack$
```

**Comment by joaomoreno** [comment]
Hi @chrisdias, check these out: #198 #196

**Comment by chrisdias** [comment]
I searched the code but I didn't search the repo!  Yes, getting a new PAT fixed this issue, thanks.
