### ISSUE TITLE
Improving "vsce --help" output documentation

### ISSUE THREAD

**Issue by volosovich** [Microsoft/vscode-vsce#201]
When developer use vsce --help he/she has this output for command:

    ls                                   Lists all the files that will be published
    package [options]                    Packages an extension
    publish [options] [<version>]        Publishes an extension
    unpublish [options] [<extensionid>]  Unpublishes an extension. Example extension id: microsoft.csharp.
    list <publisher>                     Lists all extensions published by the given publisher
    ls-publishers                        List all known publishers
    create-publisher <publisher>         Creates a new publisher
    delete-publisher <publisher>         Deletes a publisher
    login <publisher>                    Add a publisher to the known publishers list
    logout <publisher>                   Remove a publisher from the known publishers list`

I didn't find any information, about: What is possible options I can use for package, publish and unpublish command. I think need to add this information to "Publishing Extensions" page and to output for command `vsce -h`

**Comment by joaomoreno** [comment]
Have you tried `vsce publish --help`?
