### ISSUE TITLE
can't find personal access token

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode-vsce#204]
had read https://code.visualstudio.com/docs/extensions/publish-extension

but not found 
![image](https://user-images.githubusercontent.com/227713/29954018-43808992-8f07-11e7-8577-5c5cd5f9d626.png)

**Comment by joaomoreno** [comment]
You're in the wrong page.

https://atian25.visualstudio.com/_details/security/tokens

**Comment by atian25** [comment]
thanks, but where is the menu to jump this url ?

can't find the menu metioned at https://code.visualstudio.com/docs/extensions/publish-extension

![image](https://user-images.githubusercontent.com/227713/29962048-3e57c9a8-8f34-11e7-98ea-41079bbc93d1.png)

![image](https://user-images.githubusercontent.com/227713/29962054-45f64518-8f34-11e7-8cbd-db3a1d115d47.png)
