### ISSUE TITLE
Preserve existing indentation in package.json

### ISSUE THREAD

**Issue by gilmoreorless** [Microsoft/vscode-vsce#206]
Using `vsce publish <version>` is clobbering the existing indentation in `package.json` and forcing it to always be 4 spaces. This differs from the default 2-space indentation generated by `npm init`, and can make git diffs rather messy.

I know `npm` has code to detect the indentation of `package.json` and preserve it when installing/updating/removing dependencies or publishing a new version. Ideally `vsce` would do the same.

I’ve been able to quickly get the same functionality working for `vsce` locally (using the same module as `npm` for consistency). I’d be happy to create a PR for it, but I also saw in #180 that `vsce` might be moving away from custom `package.json` updates completely. So before I clean up the code and write tests for it, is this a PR that’s worth doing, or should I just wait until `vsce` uses `npm publish` under the covers?

**Comment by joaomoreno** [comment]
I'm more in favour of having vsce just spawn npm.

**Comment by gilmoreorless** [comment]
Fair enough, I’ll leave it alone then. 😃

**Comment by JimiC** [comment]
@joaomoreno So how to think this should be implemented? Using `npm` unofficial API or spawning a child process and executing the `npm` command?

**Comment by JimiC** [comment]
Looking at the code I concluded that `child process` is preferred.
