### ISSUE TITLE
[question] how to develop vscode extensions locally with inter dependencies

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-vsce#207]
From https://github.com/Microsoft/vscode/issues/35458 cc @dakaraphi 

> I'm attempting to develop extensions which have a common dependency.
> I use `npm link` to satisfy the dependency locally.
> 
> The problem is that I can't package the extension because `vsce` will fail due to `npm` saying there are extraneous modules.  This is due to both modules requiring `vscode`.
> 
> The annoying work around is to uninstall the `vscode` from the common module before I package/publish.  But this is an annoying workflow.
> 
> Is there a way to make this work properly?

**Comment by guw** [comment]
@dakaraphi Sorry for hijacking this thread but I'm having a similar issue. I don't even get the code compiled when defining a dependency from one extension to another extension. Thus, I was wondering for your setup to reproduce the issue you are seeing.

I've created [a Stackoverflow post](https://stackoverflow.com/questions/48221762/error-compiling-vs-code-extension-with-dependency-on-another-extension) with details and a [repo for reproducing the compile issue](https://github.com/guw/import-cost).

**Comment by dakaraphi** [comment]
@guw posted a response on Stackoverflow.
This is related to https://github.com/Microsoft/TypeScript/issues/6496#issuecomment-351435136
