### ISSUE TITLE
Improve "Invalid Resource" error message in case of expired/invalid PAT

### ISSUE THREAD

**Issue by mlewand** [Microsoft/vscode-vsce#209]
While attempting to publish a package after a long time of inactivity I today I got:

> Error: Invalid Resource

Luckily this issue has been already discussed here, so I was able to quickly find the answer for the problem (#196, #198, #200). IMHO the message is vague, and it should simply say that invalid token is provided.

I saw [@joaomoreno comment](https://github.com/Microsoft/vscode-vsce/issues/198#issuecomment-318289074) and I checked issues for an issue about fixing this message, but with no luck. It might be possible that I have missed it, in case it was not yet fixed we could track it here.

**Comment by joaomoreno** [comment]
Fixed in 1.31.1

**Comment by jpoon** [comment]
Thanks @joaomoreno. Ran into this just now and the error message was helpful :)

Why not use an `aka.ms` url instead of http://tinyurl.com/y8djp2nl?

**Comment by joaomoreno** [comment]
Oh yeah... I actually did [this](https://www.bing.com/search?q=microsoft+tinyurl&qs=n&form=QBLH&sp=-1&ghc=1&pq=microsoft+tinyurl&sc=6-15&sk=&cvid=36CDCA992C264A7AA8199EF2E392D4C1) but that yielded nothing interesting...
