### ISSUE TITLE
Add trusted badge providers

### ISSUE THREAD

**Issue by mxschmitt** [Microsoft/vscode-vsce#212]
Hello,

i already tried to find something in the wiki etc. what the requirements are to be added as a trusted SVG badge provider. In my current project I use the untrusted SVG sources from:

- [godoc](https://godoc.org/github.com/maxibanki/golang-url-shortener?status.svg)
- [goreportcard](https://goreportcard.com/badge/github.com/maxibanki/golang-url-shortener)
- [coveralls](https://coveralls.io/repos/github/maxibanki/golang-url-shortener/badge.svg?branch=master)
- [waffle.io](https://badge.waffle.io/maxibanki/golang-url-shortener.png?columns=all)
- [bintray](https://api.bintray.com/packages/maxibanki/golang-url-shortener/travis-ci/images/download.svg?version=0.1)

Is is possible, that I just can create a PR and add these? Or depends it on something like how many users they are using etc.

I'm not sure if this is the correct place to create such an issue, this issue should add providers to the markdown engine. (maybe move the issue)

Best regards

Max

**Comment by joaomoreno** [comment]
Sure, fire up a PR!

**Comment by maxibanki** [comment]
I also added the one from deepscan.io as request in Microsoft/vscode#32917.
