### ISSUE TITLE
feature: ability to lookup extension on Marketplace via command line

### ISSUE THREAD

**Issue by raix** [Microsoft/vscode-vsce#214]
It would be nice if the cli could be used to lookup extension metadata from Marketplace.

I'm interested in know last version of my package in order for me to automate publishing new versions eg. via semantic-release on CI.

I could use the api directly as vscode - but it would be nice with an official way to do this.

Idea:
```bash
$ vsce show foo.my-extension # Show human readable format

# or in json:

$ vsce show foo.my-extension --json # better integration with other tools
# {
#   "extensionName": "my-extensnion",
#   "publisher": {
#     "pblisherName": "foo",
#     ...
#   }
#}

```

I don't mind creating a pr for it to get it rolling.

**Comment by joaomoreno** [comment]
PR would be awesome.

**Comment by raix** [comment]
@joaomoreno I've created an initial pr #215

**Comment by raix** [comment]
@joaomoreno this is already implemented

**Comment by joaomoreno** [comment]
🤦‍♂️ Thanks!
