### ISSUE TITLE
vsce show on powershell/cmd prints unknown characters

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-vsce#221]
**Repo steps**
1. In windows powershell or cmd
2. Run `vsce show eamodio.gitlens`

**bug**
The stars and download symbol are printed as unknown characters

![capture](https://user-images.githubusercontent.com/12821956/33625634-06eeea46-d9ad-11e7-850e-d4bcd3337784.PNG)

**Comment by raix** [comment]
@mjbvz thanks - the pretty unicode stars seem to break on windows powershell - is this also an issue in `cmd`?

**Comment by mjbvz** [comment]
Yes, same thing happens on cmd

**Comment by raix** [comment]
Thanks @mjbvz I'll investigate

**Comment by raix** [comment]
It seems to be an issue with encoding or missing font glyphs, I'm looking into safer glyphs or/and a fallback if it's on a system without the fancy icons
