### ISSUE TITLE
vsce show prints __tags

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-vsce#222]
**repo**
1. Run `vsce show CristianRengifo.informix4gl`

**bug**
The following tags are printed: 

```
  __ext_4gl, __ext_per, 4GL, Informix, Informix 4GL
```

I don't know where these double underscore tags are coming from. Probably file extension support?

Here's the package.json on the marketplace:

![screen shot 2017-12-05 at 11 31 39 am](https://user-images.githubusercontent.com/12821956/33626688-2d62e2e2-d9b0-11e7-9d9f-cbe662626326.png)

**Comment by raix** [comment]
Thanks @mjbvz I'll do a fix for it filtering out `__ext_*` tags
