### ISSUE TITLE
VSCE Show - Windows output hard to read

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode-vsce#224]
Testing https://github.com/Microsoft/vscode/issues/39586

Two minor issues:
1. The Windows shell struggles with the font for ratings and download
2. Perhaps we should state that extension names can be case sensitive (I know they are meant to be all lower case but some are not)

![image](https://user-images.githubusercontent.com/1051190/33675251-c9b416b4-da66-11e7-8bb7-d2b63949811c.png)

**Comment by raix** [comment]
Thanks @seanmcbreen 

I agree the quick fix would be to add a note that it's case sensitive,

If the unique identifier is case sensitive - I don't believe it is eg.: 
https://marketplace.visualstudio.com/items?itemName=seanmcbreen.mdtools
https://marketplace.visualstudio.com/items?itemName=seanmcbreen.MDTools
*(Both reference the same extension)*

I'll take a look

--

The icon issue is tracked in #221 *encoding/missing font glyphs*
