### ISSUE TITLE
mailto links in README.md don't work with "vsce package"

### ISSUE THREAD

**Issue by tgriff** [microsoft/vscode-vsce#228]
Repro steps:
1. Add mailto link in README.md, e.g. \[Email me!](mailto:me@website.com?Subject=Repro).
2. Run "vsce package"
3. I get the following error:
Error: Couldn't detect the repository where this extension is published. The link 'mailto:me@website.com?Subject=Repro' will be broken in README.md. Please provide the repository URL in package.json or use the --baseContentUrl and --baseImagesUrl options.

If I run "vsce package --baseContentUrl" it ends up adding "true/" to the link like so:
\[Email me!](true/mailto:me@website.com?Subject=Repro)

I would expect vsce to ignore mailto links such that they actually work when the package is installed and the user views the readme.

**Comment by joaomoreno** [comment]
Wanna attempt a PR?

**Comment by tgriff** [comment]
I was planning on looking into it as I have time.  I've got some other higher priority items on my plate but wanted to file an issue to make sure it's being tracked.

**Comment by samrat-gavale** [comment]
I can give this a try. What is the right solution for this? Currently, while packaging, the MarkdownProcessor tries to add a prefix to all the relative links in the markdown. The mailto links are being detected as relative link. So changing the [markdownPathRegex ](https://github.com/microsoft/vscode-vsce/blob/master/src/package.ts) to leave out the mailto links should be good enough, right?
