### ISSUE TITLE
I forgot my personal access token generated by publish my extension.

### ISSUE THREAD

**Issue by jtjoo** [Microsoft/vscode-vsce#231]
Hi,

I used to use my access token to login by vsce-cli, to publish my developed extension.
But after months I had to re-install my mac and now logged in vsce-cli is gone, but I don't have previously used personal access token to login.

I re-generated my personal acesss token but I cannot login by vsce-cli.
How can I re-login by new token and access to my extension and publish?

**Comment by joaomoreno** [comment]
#232

**Comment by tsdmrfth** [comment]
I solved same problem by reading vsce package codes and i found that vsce-cli is storing token variables in a text file which can be found at $(HOME_DIR)/.vsce
