### ISSUE TITLE
I forgot my personal access token generated by publish my extension.

### ISSUE THREAD

**Issue by jtjoo** [Microsoft/vscode-vsce#232]
Hi,

I used to use my access token to login by vsce-cli, to publish my developed extension.
But after months I had to re-install my mac and now logged in vsce-cli is gone, but I don't have previously used personal access token to login.

I re-generated my personal acesss token and set it to access all scopes but I cannot login by vsce-cli.
How can I re-login by new token and access to my extension and publish?

**Comment by joaomoreno** [comment]
Use `vsce login PUBLISHER_NAME` to re-login with VSCE.

**Comment by Broken-Admin** [comment]
Hey, this is closed, but I can't seem to find the setting to regenerate the tokens. Could anyone lend me a hand?

**Comment by jtjoo** [comment]
You can regenerate token on dashboard of your live.com/outlook.com account.

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs/extensions/publish-extension
