### ISSUE TITLE
upload with icon image failed

### ISSUE THREAD

**Issue by timoxue** [Microsoft/vscode-vsce#233]
Hi could anyone help with this?
command: vsce publish

package.json:
   "icon": "images/hanasql.png"

image location: ./images/hanasql.png
error: Error: The specified icon 'extension/images/hanasql.png' wasn't found in the extension.

is the default "extension" path included as hard coded?

Thanks

**Comment by joaomoreno** [comment]
Can you show me the extension's repository, so I take a look?

**Comment by ilariaventurini** [comment]
Hi, I have the same problem.
