### ISSUE TITLE
Bad error message when package is too large

### ISSUE THREAD

**Issue by mariorodeghiero** [Microsoft/vscode-vsce#234]
I can use my tokem to create and login, but when I run the command "vsce publish". This message: expired tokem

<img width="762" alt="screen shot 2018-01-24 at 08 22 07" src="https://user-images.githubusercontent.com/24671133/35327726-7c407cbe-00e1-11e8-9eb7-4aba85046041.png">

**Comment by joaomoreno** [comment]
Have you tried getting a new PAT?

**Comment by mariorodeghiero** [comment]
Yes, I created another(3) and also I can log in, but I can't publish

<img width="964" alt="screen shot 2018-01-24 at 09 29 54" src="https://user-images.githubusercontent.com/24671133/35330107-6722b89e-00e9-11e8-8f36-095aee051c5b.png">

**Comment by mariorodeghiero** [comment]
After some tests, has been solved ignore gifs added, the **VSIX** file was with **74 MB**, but the error presented was **"tokem expired"**.

I tried to load the file in the marketplace Web site, where he reports that the file must be less than **100 MB**, but the **.VSIX** file **74 MB** uploaded, either of error presented **"timeout"**

After the file get 7 KB, run the command "vsce publish" and up normally. 
Thanks

**Comment by joaomoreno** [comment]
Got it.

cc @viradhamMS @pkuma-msft Could we get a better error message from the service other than `Invalid Resource` for when the extension package is too large?

**Comment by viradhamMS** [comment]
Thanks for reporting. Will fix it to be more actionable

**Comment by pkuma-msft** [comment]
Wanted to provide an update that we're looking at this issue. We (from an application pov) are throwing the right exception and error message but the framework seems to convert it into a generic 500 - Internal Server Error in its uber exception handler. I'll provide an update as soon as we have a fix ready.

**Comment by pkuma-msft** [comment]
Update: The fix in framework has been merged into our master branch. And it should make it out to prod in about 3-4 weeks.

**Comment by joaomoreno** [comment]
Excellent! Closing this for now. Thanks for the updates @pkuma-msft!
