### ISSUE TITLE
Interactive repository warning breaks gulp workflow

### ISSUE THREAD

**Issue by benrr101** [Microsoft/vscode-vsce#235]
The addition of an interactive warning when the repository field has been omitted breaks gulp workflows. Running `vsce` from a gulp task, the `vsce` command will hang when there the repository field has been omitted. This causes the entire gulp task to hang, which can be a major annoyance when running package as part of an automated build.

Obviously the end user solution is to just assign a repository field, but in the context of CI builds, this might cause the build to fail via timeout, which takes much longer than a CI build should take to fail. 

My suggestion would be to either just emit the warning as a warning and continue, or allow for a warnings as errors command line argument. Alternatively, you could follow the pattern of `yum` and have a `-y`/`-n` argument to bypass and yes/no interactive questions.

**Comment by joaomoreno** [comment]
Makes sense. Let's check for a TTY, print the warning and accept a `Y`, since it's just a warning.

**Comment by joaomoreno** [comment]
Fixed in 1.36.2
