### ISSUE TITLE
Unable to update vsce for last week (stays on 1.35.0 after claiming to update to 1.36.3)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-vsce#239]
For the last week  or so `vsce` has been telling me there are updates, but it never seems to update when I run the command (I've never had any issues in the past):

```text
The latest version of vsce is 1.36.3 and you have 1.35.0.
Update it now: npm install -g vsce

M:\> npm install -g vsce
C:\Users\danny\AppData\Roaming\npm\vsce -> C:\Users\danny\AppData\Roaming\npm\node_modules\vsce\out\vsce
+ vsce@1.36.3
updated 1 package in 13.862s

M:\> vsce --version
1.35.0
```

**Comment by joaomoreno** [comment]
There is something wrong in your system. Check what command is run when you run `vsce` in the command prompt. Do you have multiple node/npm versions installed?

**Comment by DanTup** [comment]
> Check what command is run when you run vsce in the command prompt.

Here's the paths of node/npm/vsce:

```
PS M:\Coding> get-command vsce

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     vsce.cmd                                           0.0.0.0    M:\Apps\Node\vsce.cmd


PS M:\Coding> get-command node

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     node.exe                                           8.9.4.0    M:\Apps\Node\node.exe


PS M:\Coding> get-command npm

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     npm.cmd                                            0.0.0.0    M:\Apps\Node\npm.cmd
```

> Do you have multiple node/npm versions installed?

Not as far as I know. I did upgrade it recently, but the installer pre-filled the previous path and I installed it there.

The contents of `vsce.cmd` look like this:

```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\vsce\out\vsce" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\node_modules\vsce\out\vsce" %*
)
```

Which makes me suspicious about the path that was output during the upgrade. I'll wipe them out and start over; seems like npm wants to be in my profile so having it in the nodejs install folder seems wonky.

**Comment by DanTup** [comment]
Sorted. Somehow there's an npm in the nodejs folder, but that seems to now call the one in the profile. All seems super wonky, but I'm no longer getting cmd files in M:\Apps\Node they're all going in the profile, so the version being run and the version being updated match.
