### ISSUE TITLE
Trusted svg badge provider

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode-vsce#240]
Hi, i noticed that **[opencollective.com](https://opencollective.com/)** is now a [trusted badge provider](https://github.com/Microsoft/vscode-vsce/blob/d478c021394c7be0d8ec2df3aae10c5c35799559/src/package.ts#L138) but i get this error when i publish my extension:

```
Error processing 'Equinusocio.vsc-material-theme' SVG reference in file '/extension/README.md'. Your reference to the SVG image ‘https://opencollective.com/vsc-material-theme/contributors.svg?width=890’ is not supported. Please see https://aka.ms/vsmarketplace_badge for more details.
```

Also opencollective.com doesn't appear here:
https://docs.microsoft.com/it-it/vsts/extend/develop/manifest#supported-badge-services

Using the vsce release.

**Comment by joaomoreno** [comment]
Apparently, the Marketplace is also doing checks on the badges.

@viradhamMS @pkuma-msft Can we whitelist the following domains?

- https://github.com/Microsoft/vscode-vsce/commit/b3b198f0f7c7e65efb06c81d62e03afa76822960
- https://github.com/Microsoft/vscode-vsce/commit/75f7d2ffcb1706e59cc9796b1e36e298b55dbf4a
- https://github.com/Microsoft/vscode-vsce/commit/b25a7701456d7bcd8273e7e84ca9b656e7a1d74c

cc @mjbvz As far as I understood, these were the ones recently added.

**Comment by pkuma-msft** [comment]
@equinusocio Sorry for the inconvenience, I'll add these domains to our whitelist and update this thread.

**Comment by pkuma-msft** [comment]
We have made the change at our end, the publish should go through now. Please try and let us know if you still see any issues.

**Comment by joaomoreno** [comment]
Thanks @pkuma-msft! 🍻
