### ISSUE TITLE
Allow manually version setting for package command

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode-vsce#250]
If I was directly publishing my plugins to the marketplace, `vcse publish` allows setting a full version number manually. However, I want to be able to run `vsce package` on a build server, and manually decide which ones to push. However, `package` does not allow passing in a version number, so my current solution is to actually have my build script modify my package.json before building. This should not be required, and `package` should accept a version.

**Comment by joaomoreno** [comment]
You can use `npm version` to bump the version number.
