### ISSUE TITLE
Allow publishing version without changing package.json version

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode-vsce#251]
It should be possible to do a non invasive publish with a specified version, where the package gets published without changing the version in package.json.

**Comment by joaomoreno** [comment]
No, I don't think it should. If your extension has changes, a version bump is required.

http://blog.npmjs.org/post/162134793605/why-use-semver

**Comment by ThadHouse** [comment]
Well the releases are semver, but I have an external system to handle versioning, because it's part of a larger package with the version generated at build time. But I'll just keep having an external program manually modify the file if that is what you guys are are going to stick with.
