### ISSUE TITLE
Cannot create new auth token

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode-vsce#252]
I tried to publish changes to my extension from a different machine then where I do this usually. However, I haven't set a valid publisher auth token there so I got the `Error: Failed Request: Unauthorized(401) -` error.

I followed the link to either add another token or use the one I have already, but cannot since the web page looks now completely different compared to [what the docs say](https://code.visualstudio.com/docs/extensions/publish-extension#_get-a-personal-access-token):

<img width="777" alt="bildschirmfoto 2018-03-30 um 11 59 28" src="https://user-images.githubusercontent.com/2398704/38134117-02753c8a-3412-11e8-9d16-73c8fb25e2d4.png">

In general we could need a simpler way to have the authentication implemented. Almost every time I try to publish I first have to solve an issue. This is pretty annoying. It's obvious the current process is too error prone and the docs can't keep up with the changes in VSTS.

**Comment by joaomoreno** [comment]
I believe you're in the wrong page. Go to https://mike-lischke.visualstudio.com/_details/security/tokens

**Comment by mike-lischke** [comment]
Thanks @joaomoreno, indeed the correct link is that. However, isn't it a usability nightmare if the doc shows a different layout and there are actually **two** `Security` entries? In fact I find the entire page  a nuisance, given that all I need is the security token for vscode extensions. Why am I forced to see all this unrelated noise? That **calls** for misunderstandings.

**Comment by mike-lischke** [comment]
It's so "great", now the publication fails because of a Marketplace problem, as described in #253 . Some more stability and better usability would certainly be good.

**Comment by joaomoreno** [comment]
You can always provide feedback to Visual Studio Team Services right here:

<img width="582" alt="screen shot 2018-04-03 at 09 48 55" src="https://user-images.githubusercontent.com/22350/38236372-3dbb8424-3724-11e8-8762-594ef14d00dc.png">
