### ISSUE TITLE
Source code file name contains Unicode character publish failure

### ISSUE THREAD

**Issue by htwx** [microsoft/vscode-vsce#254]
## 源码文件名包含Unicode字符时使用命令打包是可以通过的，插件安装后也可以正常运行（win系统）:
When the source file name contains Unicode characters, it can be passed by command package. After plug-in installation, it can also run normally (win system).

 > vsce package

### 成功截图 Successful screenshot

![1](https://user-images.githubusercontent.com/6562192/38223394-3e281d84-371d-11e8-9f5f-9d209167c535.jpg)

但在发布的时候，因为文件名包含Unicode字符，致使发布失败：
But when publishing, because the file name contains Unicode characters, the publication fails.

> vsce publish

### 失败截图 Failure screenshot

![2](https://user-images.githubusercontent.com/6562192/38223114-adcfe3ee-371b-11e8-9e42-9b2ed2432d33.jpg)

这里的错误提示很不明确 The Error hints here are not clear

**Comment by joaomoreno** [comment]
I suggest to only use ASCII-like characters for file names.

**Comment by htwx** [comment]
如果只允许ASCII字符作为文件名称，那应该对非ASCII字符的文件名抛出错误消息。
If only ASCII characters are allowed as file names, you should throw an error message to the file name of a non-ASCII character

**Comment by nobodxbodon** [comment]
Got some findings and workaround when working on the same issue [here](https://github.com/program-in-chinese/vscode_english_chinese_dictionary/issues/5).

It's feasible to use unicode (Chinese in this case) in file names and still publish successfully. This error seems to only occur when there are two or more file names having the same number of charactors. For the example @htwx gave above, `工具.ts`, `日志.ts` and `进程.ts` all have two charactors. Also, the error will also occur if the files exist in two folders that have the same number of charactors. For example, `功能/通用.ts` and `工具/辅助.ts` would also cause the error.

Last but not least, if you still get the error after making sure all the file names have different number of charactors, try clearing out the folder defined in the "outDir"  field of `tsconfig.json`. As `vsce publish` doesn't seem to clear the folder, and the JS files compiled from the old TS files would cause this error always.

**Comment by sceext2** [comment]
It seems that no-ASCII chars have been replaced by `?`

**Comment by joaomoreno** [comment]
Closing this as won't fix.
