### ISSUE TITLE
Extension package contains invalid characters

### ISSUE THREAD

**Issue by tboby** [Microsoft/vscode-vsce#256]
When I try to publish I get the error "Extension package contains invalid character(4, 36). Error: XML Document-'<', hexadecimal value 0x3C, is an invalid attribute character. Line 4, position 36.".
The package seems to install fine locally and 7zip has no problems opening the file.

What does this error actually mean?

```
PS C:\Users\Thomas\git\CWToolsExtensionLSP> vsce publish patch --pat
Executing prepublish script 'npm run vscode:prepublish'...

> cwtools-vscode@0.4.20 vscode:prepublish C:\Users\Thomas\git\CWToolsExtensionLSP
> tsc -p ./

Publishing tboby.cwtools-vscode@0.4.20...
Error: Extension package contains invalid character(4, 36). Error: XML Document-'<', hexadecimal value 0x3C, is an invalid attribute character. Line 4, position 36.
PS C:\Users\Thomas\git\CWToolsExtensionLSP>
```

**Comment by tboby** [comment]
@joaomoreno 

You won't be able to run my entire build process, so I've made a commit with the artifacts ready.

[This commit](https://github.com/tboby/cwtools-vscode/tree/df8692daf4dc493f20e35bc60ca523ec63e85fb8).

If I clone that commit then:
1. `npm install`
2. (optionally) `vsce package`
3. `vsce publish --pat mykey`

then I get the same error, on a different machine.

**Comment by joaomoreno** [comment]
I was able to publish successfully. Can you run `vsce package`, rename the `vsix` file to a `zip` file, extract it and send me the `extension.vsixmanifest` within?

**Comment by tboby** [comment]
I was able to publish last night, as far as I could tell unchanged package,
[extension.vsixmanifest.txt](https://github.com/Microsoft/vscode-vsce/files/1931710/extension.vsixmanifest.txt)
 
Could it have been a serverside issue? It did seem to be delayed by roughly the upload time.

**Comment by joaomoreno** [comment]
Yup, sure sounds like it. Good to know it works now.
