### ISSUE TITLE
As a part of the pre-deployment checks, check version in package.json and CHANGELOG

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode-vsce#257]
Hey, I'd like to suggest that as a part of the pre-deployment checks, CHANGELOG is searched for the current version from `package.json` and if it doesn't contain it, an error is thrown.

Unfortunately, the reverse check, where the top CHANGELOG header value would be checked against `package.json`'s `version` field, I don't think can be safely provided as people format CHANGELOG in different ways.

Also, if `package.json`'s `version` is the same as the currently published version, an error should be thrown, but I think that may already be the case.

**Comment by joaomoreno** [comment]
You can write that check for your own extension and call it as a part of the `vscode:prepublish` step.
