### ISSUE TITLE
vsce not support travis CD for login with excrypted token

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode-vsce#259]
Hello, 

I have encrypted the PAT in travis and pasted in travis file.
https://github.com/shanalikhan/code-settings-sync/blob/master/.travis.yml
Following is the script `printf $VSCE_TOKEN | vsce login "Shan"`

The problem is when Travis paste the `[secure]` instead of script and vsce think of it as invalid resource.

when i tried to set simple ( not encrypted ) env. variable in travis and tried the above command it worked - but PAT shows in logs.

Is this a problem from Travis side or VSCE side

**Comment by joaomoreno** [comment]
> `printf $VSCE_TOKEN | vsce login "Shan"`

VSCE doesn't support this way of invocation.

**Comment by shanalikhan** [comment]
is there any way using VSCE to publish using travis without showing the access token. 
or currently VSCE doesnt support CD using travis

**Comment by joaomoreno** [comment]
VSCE uses `~/.vsce` as a store for credentials. Its format should be a JSON file containing an array of publishers. A publisher is a tuple of name and PAT. So, you should be able to generate that file before invoking VSCE.

Something like this:

```
echo "[{\"name\":\"Shan\",\"pat\":\"$VSCE_TOKEN\"}]" > ~/.vsce
vsce publish
```

**Comment by shanalikhan** [comment]
i have tried this way, as willbe using travis encrypted environment variable for `$VSCE_TOKEN`
It still says `Error: Invalid Resource`

**Comment by joaomoreno** [comment]
Is $VSCE_TOKEN decrypted when used?

**Comment by shanalikhan** [comment]
When travis decrypted it on using.
When i ignore encryption for token in Travis, it works fine.
upon decryption there is an issue.

**Comment by joaomoreno** [comment]
Travis says

> The variables are stored encrypted in our systems, and get decrypted when the build script is generated.

https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

I think this is a user configuration issue, not a VSCE issue, so I'm closing it.
