### ISSUE TITLE
Support for packagePath and version options together

### ISSUE THREAD

**Issue by ivanovit** [microsoft/vscode-vsce#261]
Currently, when both options are provided we got the following error:  `Not supported: packagePath and version.`

We have internal builds and we use pre-release part of the version for build information. We want to remove the pre-release part from a version before publishing specific `.vsix` that has been tested without rebuilding the package.

Could you add support to change only the version before publishing specific `.vsix`?

**Comment by joaomoreno** [comment]
With https://github.com/microsoft/vscode-vsce/issues/596, you will be able to publish using `--no-update-package-json`. This means you can provide any version at publish time and that will work in-memory: you don't have to change `package.json` beforehand.
