### ISSUE TITLE
Allow multiple publishers?

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode-vsce#264]
Hi. I'm a maintainer of some extensions and want to give someone else permission to publish the extensions as well so we can both do releases. Is this a possibility? I really can't find anything regarding this.

**Comment by joaomoreno** [comment]
cc @viradhamMS @pkuma-msft

**Comment by viradhamMS** [comment]
@SamVerschueren : Yes, this is possible. Please use the 'Add' button in the below snip and you can grant others the appropriate permissions to manage your extensions.

![image](https://user-images.githubusercontent.com/11805676/40910067-cd2f358c-6808-11e8-8822-8d45568d003d.png)

**Comment by joaomoreno** [comment]
@viradhamMS Very cool, I wasn't aware it was that simple. Thanks!

**Comment by SamVerschueren** [comment]
The thing is that I don't want the other person to be able to manage ALL my extensions, I want him to have publish access to a single extension like you can setup on npm. That doesn't seem possible.

**Comment by viradhamMS** [comment]
Got it. That workflow is not possible through our manage portal yet. Please send us a mail to vsmarketplace@microsoft.com with the details of the publisher you want to grant owner access to and the extension you want to grant access for. I will get that done at our backend.
