### ISSUE TITLE
“vsce package” leaves out the “out” folder

### ISSUE THREAD

**Issue by JackKCWong** [Microsoft/vscode-vsce#266]
I was packaging a extension locally and everything was fine when I was using vsce 1.39. Then once I upgraded to 1.42, the “out” folder which contains the tsc output js files disappeared in the vsix file ever since. I tried downgrading to 1.39 and reinstalling vsce but the issue persists.

I have the right info in the “main” of package.json and don’t have a .vsceignore file. My OS is Win7. Any help is much appreciated.

**Comment by joaomoreno** [comment]
What does `vsce ls` return?

**Comment by JackKCWong** [comment]
files under node_modules, package.json, readme.md

**Comment by joaomoreno** [comment]
Can you give me a pointer to the git repo, so I can reproduce it?

**Comment by JackKCWong** [comment]
my bad. I had a line in .vscodeignore that excluded the folder. I thought it was for vscode only. 

But launching a extension debug session in vscode does not honor this file, that's why it surprised me when the final package didn't work.

**Comment by wilhelmklopp** [comment]
Just ran into the exact same thing. Same problem, same solution. Thanks so much for documenting your solution @JackKCWong ❤️
