### ISSUE TITLE
How to publish extension when we're using yarn?

### ISSUE THREAD

**Issue by ritwickdey** [Microsoft/vscode-vsce#267]
I can build the package using `vsce package --yarn`, but when I can't do `vsce publish --yarn`. 

I'm switching to yarn for https://github.com/Microsoft/vscode-vsce/issues/246

**Comment by joaomoreno** [comment]
Wanna contribute a PR?

**Comment by ritwickdey** [comment]
Yep! sure

**Comment by JimiC** [comment]
This issue should be closed.

**Comment by joaomoreno** [comment]
Thanks!
