### ISSUE TITLE
README not being published

### ISSUE THREAD

**Issue by u2berggeist** [Microsoft/vscode-vsce#270]
Pretty much identical to #53 , but none of those solutions are working.

My README is:
A) In my publishing directory, 
B) on the Repository, 
C) Not in the `.vscodeignore` file

And it still isn't showing up. no idea what's happening with it.

[Here's my repo](https://github.com/u2berggeist/ANSYS_CFX)

**Comment by joaomoreno** [comment]
I see your README both in the Marketplace and in the product:

![image](https://user-images.githubusercontent.com/22350/41957977-ef36f07e-79e8-11e8-9008-ece0632cb9d0.png)

**Comment by u2berggeist** [comment]
Huh. It's showing up on mine now too. I waited for about an hour, but it wasn't loading. 

Sorry for the false alarm. Thanks for checking all the same.
