### ISSUE TITLE
PAT expired

### ISSUE THREAD

**Issue by arafkarsh** [Microsoft/vscode-vsce#272]
HI,

VSC Plugin
https://marketplace.visualstudio.com/items?itemName=MetaMagic.amexio

My PAT is expired and I am not able to create a new token.

I am not able to log into the following account neither i am able to reset the password.
https://metamagic.visualstudio.com/

Amexio: https://amexio.tech/amexio-plugins-1 

Thanks and regards,

Karsh

**Comment by arafkarsh** [comment]
issue resolved

**Comment by joaomoreno** [comment]
@arafkarsh How?
