### ISSUE TITLE
[Proposal] Introduce addition of integrity checksum in package.json

### ISSUE THREAD

**Issue by JimiC** [microsoft/vscode-vsce#275]
For some time now we are struggling with an issue, where the extension is downloaded and installed on the editor, just to find out that the extraction ended to a corrupted installation. Of course, there is the ability to re-install the extension but this action is not always clear to the end user, resulting in repeated user support from the extension's maintainers.

This proposal tries to resolve that issue at its source, by:
 1. Introducing an integrity field in `package.json` using [ssri](https://github.com/zkat/ssri) (just like `npm` does for the registered packages).
  2. Implement an integrity verification mechanism in the editor upon extension installation with notifications.

Step 2 is something that needs to be done at the [vscode](https://github.com/Microsoft/vscode) repo, of course, after step 1 is completed.

If the proposal gets accepted I can provide a PR for it.

**Comment by joaomoreno** [comment]
@sandy081 Weren't you considering to work on this soon?

**Comment by sandy081** [comment]
It was discussed but not on cards and we are not receiving any issues related to corrupted installation

**Comment by JimiC** [comment]
@sandy081 Because `Reinstall Extension` is used as a workaround (https://github.com/vscode-icons/vscode-icons/issues/1353).  I'm in the process to implement our own integrity checker but I wanted to check with you guys first before I get into coding.

**Comment by sandy081** [comment]
@JimiC Can you please file an issue in VS Code repository if you think there is a corrupted installation. Also please provide any information that is available to investigate.

- Is it the files are missing or files are downloaded but they are empty?

**Comment by JimiC** [comment]
@sandy081 That's the thing. It's not about a corrupted `vscode` installation, rather a corrupted extension downloading or inflation. I have no more information to provide other than those posted on our repo issue. Personally, I have never come across that issue but the support requests come in from time to time.

The proposal is more of a precaution than an actual solution to a confirmed issue.

**Comment by sandy081** [comment]
> rather a corrupted extension downloading or inflation

I think extension downloading should be complete otherwise it would cause corrupted vsix file error and we cannot open it at all.

If it is an issue with VSCE then this should affect all users installing that extension.

So, I would not suspect on download or inflation.

I would like to understand the issue and where it is before implementing the solution

**Comment by JimiC** [comment]
@sandy081 Yeah, that's my issue too. I have yet to identify the issue and the info provided by the users are not helpful. 

@joaomoreno  Can we at least keep this issue open for 90 days, to see if it gathers any attention?

**Comment by JimiC** [comment]
To resolve any future issues I created [nsri](https://www.npmjs.com/package/nsri). We will be using it as integrity checker for [vscode-icons](https://github.com/vscode-icons/vscode-icons)
