### ISSUE TITLE
createVSIX api endpoint doesn't support yarn

### ISSUE THREAD

**Issue by aaomidi** [Microsoft/vscode-vsce#278]
Hi,

The api endpoint to create a VSIX:

https://github.com/Microsoft/vscode-vsce/blob/d7734cd10ba382d295949f420b63020affe6686f/src/api.ts#L101-L103

Doesn't support the option of using Yarn instead of npm.

**Comment by joaomoreno** [comment]
Wanna submit a PR? 👍

**Comment by aaomidi** [comment]
https://github.com/Microsoft/vscode-vsce/pull/279
