### ISSUE TITLE
Verify PAT belongs to provided publisher name

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-vsce#289]
_From @GabrielBB on September 7, 2018 0:46_

Hi, if i use "publisher" instead of my publisher name ("GabrielBB") when publishing extensions it says i'm logged in as this guy: @MarxJiao. It doesn't matter if the token was mine, it says i'm him.

Here an image:

![Logged in as [MarxJiao](https://github.com/MarxJiao)](https://user-images.githubusercontent.com/8752823/45192206-01db3280-b215-11e8-9316-b188e2a367cf.PNG)

Try it 🐙 

_Copied from original issue: Microsoft/vscode#58134_

**Comment by joaomoreno** [comment]
_From @vscodebot[bot] on September 7, 2018 0:46_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [Extensions: Allow for multiple publishers in extension / display on Marketplace (#23801)](https://www.github.com/Microsoft/vscode/issues/23801) 
- [Improve Linux product build (#52819)](https://www.github.com/Microsoft/vscode/issues/52819) 
- [vsce create-publisher (publisher name) (#55630)](https://www.github.com/Microsoft/vscode/issues/55630)

**Comment by joaomoreno** [comment]
_From @mjbvz on September 7, 2018 1:15_

Have you tried performing any operations as this user? I think that vsce lets you "login" as them but once I actually try making requests as them, I get 401s

**Comment by joaomoreno** [comment]
_From @samueldaviddelacruz on September 7, 2018 2:14_

it is still a leak of private information even if you can't do operations on it.

**Comment by joaomoreno** [comment]
_From @pkuma-msft on September 7, 2018 13:18_

Hi @GabrielBB, thank you for taking time to report this.

'vsce login {publishername} {PAT}' is sort of a misnomer in the sense that it is not really logging you in, it is just validating whether the PAT you specified is valid or not. vsce does this by invoking marketplace's get publisher api - which is an authenticated API - no permission checks are done here, you just need to be signed-in to invoke this api.
HTTP GET https://marketplace.visualstudio.com/_apis/gallery/publishers/{publishername}

If vsce gets a positive response for the above api call, it assumes that it belongs to the publisher and displays a message that says 'you are logged in as <publishername>'

There is no leak of private information here since the publisher names and publisher internal names are already available publicly on https://marketplace.visualstudio.com

As @mjbvz pointed out, any subsequent operations you try to perform, like upload an extension, would fail since the permission checks would fail.

**Comment by joaomoreno** [comment]
_From @pkuma-msft on September 7, 2018 13:21_

To make this experience better, perhaps vsce could show a different message rather than saying 'you are logged in' or use an API that checks for permissions of the PAT on the supplied publisher name. (cc: @joaomoreno )

**Comment by joaomoreno** [comment]
@pkuma-msft Can you recommend an API call VSCE could make?

**Comment by pkuma-msft** [comment]
I will get back to you on this @joaomoreno (hopefully in a day or two)

**Comment by MarxJiao** [comment]
I think I should revoke my tokens.

**Comment by joaomoreno** [comment]
@MarxJiao No need. There is no security problem here. It's just a UI issue.
