### ISSUE TITLE
Offer to set publisher in package.json if not present

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-vsce#293]
to make the extension authoring smoother for first time users, I changed our code to no longer require the 'publisher' to be filled out, see https://github.com/Microsoft/vscode/issues/59730

I'll update the yo code generator to no longer ask for the publisher once that fix is in.

It would be great if vsce could help filling in the provider

**Comment by joaomoreno** [comment]
Released in 1.51.1 by https://github.com/Microsoft/vscode-vsce/commit/fae9b7d1259a5601a5817e7e76ee5cba4827593e
