### ISSUE TITLE
Support to ignore keyword list length warning

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-vsce#296]
With a `VSCE_IGNORE_KEYWORD_LENGTH` env variable.

From Microsoft/vscode#60214

**Comment by fabiospampinato** [comment]
`VSCE_IGNORE_KEYWORD_LENGTH` sounds like it has something to do about the number of characters used, maybe `VSCE_IGNORE_KEYWORDS_LENGTH` would me more appropriate 🤔.

**Comment by pflannery** [comment]
@joaomoreno 

Would be nice to see this and the 5 keyword limitation documentation with the [keywords field](https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_fields)

Also might be worth mentioning in the documentation that for more than 5 keywords we can use a comma delimited string like ```"cats, dogs, chickens"```. This is what I currenlty have to do for my [extenstion]( https://github.com/vscode-contrib/vscode-versionlens)

**Comment by fabiospampinato** [comment]
@pflannery I'm not sure how this is handled internally, but `"cats, dogs, chickens"` might just be considered a single tag.

**Comment by joaomoreno** [comment]
@pflannery https://github.com/Microsoft/vscode-docs/commit/15fdff3f7ebd212346b7983de03f7ac015c2d3cb

Also: https://github.com/Microsoft/vscode-vsce/issues/301

**Comment by fabiospampinato** [comment]
@pflannery interesting, it looks like you don't need to do that to get them displayed in the marketplace: see [here](https://github.com/fabiospampinato/vscode-todo-plus/blob/caf84e5dc157ab5d7c5a2baca594cac812c16bbc/package.json#L869-L877) and [here](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus). I wonder if the 5 keywords limit is actually implemented properly 🤔
