### ISSUE TITLE
Review public gallery API access 

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-vsce#297]
From @damccorm

> @joaomoreno this generally looks fine to me, a couple thoughts though.
> 
> 1. We use queryParams to encode variables into the url instead of passing them in the request as data. Not sure if the API is ok accepting them both ways or not, but the recommended way for [all of these REST API's](https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1) is through the url. So with your parameters our requests end up looking like: {base_url}/_apis/public/gallery/extensionQuery?pagenumber={pagenumber}&pageSize={pageSize}&flags.a={flags.a}&flags.b={flags.b}&etc...
> 2. Similarly, we encode the extensionId as a [route value](https://github.com/Microsoft/azure-devops-node-api/blob/8b877def56f58a581edb29debd8c7c6f4b37d481/api/GalleryApi.ts#L1635), which means it gets placed in the url like: {base_url}/_apis/public/gallery/extensionQuery/**{extensionId}**?{queryValues}. Again, not really sure whether the API can accept it the way you're sending it/will support that going forward, but that is at least how we do it and our code is generated directly from the REST endpoint.

**Comment by raix** [comment]
@joaomoreno maybe we also need to fix this in vs code?

**Comment by joaomoreno** [comment]
@sandy081 for comments.

**Comment by sandy081** [comment]
@joaomoreno VS Code also uses `data` to send parameters. If query parameters is the suggested way then it is also needed to be fixed in VS Code.

**Comment by raix** [comment]
@joaomoreno should we make a new npm package for the public api or just patch the existing code?

**Comment by joaomoreno** [comment]
@raix Let's just patch.

@sandy081 Created https://github.com/Microsoft/vscode/issues/61095

**Comment by joaomoreno** [comment]
Closing as noop

**Comment by raix** [comment]
@joaomoreno why a noop?

**Comment by joaomoreno** [comment]
They seem to be recommendations only. Let's change it once it breaks.
