### ISSUE TITLE
Exclude `package-lock.json` from extension when it only has `devDependencies`

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode-vsce#317]
1. Create hello world extension
1. `package.json` doesn't have any `dependencies`, only `devDependencies`

```json
"devDependencies": {
    "typescript": "^3.1.4",
    "vscode": "^1.1.25",
    "@types/node": "^8.10.25",
    "@types/mocha": "^2.2.42"
}
```
3. Package Extension
4. Packaged with `package-lock.json` 
**60Kb** - the entire extension folder
**56Kb**  of them - `package-lock.json`)

**Comment by usernamehw** [comment]
Since `package-lock.json` is usually kind of big file 60-100+ Kb it would be nice if `vsce` excluded `dev`:

```json
"@types/node": {
    "version": "8.10.39",
    "resolved": "https://registry.npmjs.org/@types/node/-/node-8.10.39.tgz",
    "integrity": "sha512-rE7fktr02J8ybFf6eysife+WF+L4sAHWzw09DgdCebEu+qDwMvv4zl6Bc+825ttGZP73kCKxa3dhJOoGJ8+5mA==",
    "dev": true
},
```
All records that have `"dev": true`.

**Comment by usernamehw** [comment]
Are those files `package-lock.json`/`yarn.lock` even being used by extension installer? 
When unzipped - there's already a `node_modules` folder with installed dependencies 🤷‍♂️ .

**Comment by usernamehw** [comment]
Also, what about ignoring other common types of files?:

* `.editorconfig`
* `.npmrc`
* `.yarnrc`
* `.gitattributes`
* `*.todo`
* `tslint.yaml`
* `tslint*.js`
* `.eslintrc*`
* `.babelrc*`
* `ISSUE_TEMPLATE.md`
* `CONTRIBUTING.md`
* `PULL_REQUEST_TEMPLATE.md`
* `.github`
* `.travis.yml`
* `appveyor.yml`
* ...

**Comment by joaomoreno** [comment]
VSCE invokes `npm` or `yarn` to know which modules are not dev dependencies and excludes them while packaging.

I've added pretty much all those patterns to the default ignore list. Thanks!

**Comment by usernamehw** [comment]
@joaomoreno, what about `yarn.lock`?

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode-vsce/commit/13006f04bb280abe67157195c7d82da9b9db08b8

Feel free to submit PRs.
