### ISSUE TITLE
Error: getaddrinfo ENOTFOUND app.market.visualstudio.com app.market.visualstudio.com:443

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Microsoft/vscode-vsce#32]
Looks like any command which is trying to call marketplace server is not working. I was publishing plugin few hours ago and everything was OK.

![image](https://cloud.githubusercontent.com/assets/5427083/11150480/7f9d6a02-8a28-11e5-9548-936b520b6ee2.png)

**Comment by Purus** [comment]
I am facing this issue in the recent build too which was downloaded today. I have setup the required proxy settings. Any fix planned or I am missing anything?

**Comment by joaomoreno** [comment]
@Purus this issue is about the command line tool `vsce`. Are you talking about that or VS Code itself?

**Comment by Purus** [comment]
Oh. This is about VS Code app in Windows.
