### ISSUE TITLE
URL rewriting sometimes gets it wrong

### ISSUE THREAD

**Issue by angelo-mollame** [microsoft/vscode-vsce#322]
**Repro steps:**

1) `git clone https://github.com/angelo-mollame/batch-replacer.git`
2) (if it's not the last commit anymore) `git checkout 046f6597de1eeb5900f3e3d4a88649756332bbe8`
3) `vsce package`
4) open the generated VSIX, open the README file in it, and compare it with the README file in the source code

Bottom part in the source code:

```
name = "\w+"
type = "[\w\.]+"
type = "%[type](?:<\w+(?:, \w+)*>)?"
type = "%[type](?:\[\])?"
type = "%[type](?: \| %[type])?"
parameter = "%[name]: %[type]"
parameters = "(?:%[parameter](?:, %[parameter])*)?"

replace-regex "(%[name])\((%[parameters])\): (%[type])"
with "$1: ($2) => $3"
```

Bottom part in the README in the VISX:

```
name = "\w+"
type = "[\w\.]+"
type = "%[type](https://github.com/angelo-mollame/batch-replacer/blob/master?:<\w+(&:, \w+)*>)?"
type = "%[type](https://github.com/angelo-mollame/batch-replacer/blob/master?:\[\])?"
type = "%[type](https://github.com/angelo-mollame/batch-replacer/blob/master?: \| %[type])?"
parameter = "%[name]: %[type]"
parameters = "(?:%[parameter](https://github.com/angelo-mollame/batch-replacer/blob/master?:, %[parameter])*)?"

replace-regex "(%[name])\((%[parameters])\): (%[type])"
with "$1: ($2) => $3"
```

**Comment by Wastus** [comment]
I just tried to include pictures encoded in base64 to my readme.md because other measures aren't working in our environment. But the URL rewriting will also rewrite those and break them in the process, which leaves me with no images regardless of what I try:
`![Demo2](data:image/gif;base64,R0lGODlhkAagA...)`

**Comment by joaomoreno** [comment]
@angelo-mollame Please use `--no-rewrite-relative-links`

@Wastus Will fix this by avoiding rewriting `data:` URLs.
