### ISSUE TITLE
Relative image paths should be allowed when using vsce package instead of publish

### ISSUE THREAD

**Issue by SoftwareApe** [microsoft/vscode-vsce#327]
When packaging extensions I only want to distribute locally (inside the company) it would be very helpful to be able to specify just relative paths (they work in Bitbucket). Right now VSCE just fails asking for an https URL. This should only be packaged locally in the VSIX and need no repostiory URL at all.

If this already is possible the message should mention what I'm supposed to do.

**Comment by bkelley13** [comment]
I've had this issue to, at least I don't have to upload whole project, just the images.  ie, I work around this by uploading my screenshots only to a github location,then just referencing a relative path to it in the packages.json.    Then for vsce time, I did a : vsce package --baseImagesUrl=https://raw.githubusercontent.com/bkelley13/oracle-jet-images/master/    As long as the path to the local icon file is same as the path to the one in the --baseImagesUrl, then I was able to build.  I didn't have to upload my whole project to github, just the images.  I would totally like to see the issue fixed as well.

**Comment by ngAtesz** [comment]
Currently I ran into the same problematic scenario. I didn't want to make my repository public but because of this issue I had to. Is there any plan to make it possible to choose relative path?

Another issue came up when I tweaked with packaging: by default the  `--baseImagesUrl` is referring to `master` branch which has changed this year to `main`. My workaround was passing my main branch link as `baseImagesUrl`.

**Comment by joaomoreno** [comment]
Adding `--no-rewrite-relative-links` option to `vsce package`.

**Comment by nealkruis** [comment]
I know this is long closed, but I'm trying to understand more about the implementation. In my experience, the extension's Marketplace page's contents appear to load directly from the README in the installed extension root directory, but it does not recognize image paths relative to the extension's root directory. Is the Marketplace page using a different working directory, or am I missing something?

**Comment by joaomoreno** [comment]
The Marketplace only serves a few specific assets via their webserver, images not included. For that reason, vsce _patches_ image links (and others) to point directly to GitHub's raw content server, so a rendered README.md render fine in the Marketplace.

**Comment by nealkruis** [comment]
Thanks for the explanation @joaomoreno. I feel that the image links should point to the version of the image at the time of release (and not the latest on the default branch). It would be nice if the relative paths could be automatically linked to the git reference at the time of packaging. Maybe this is already possible?

**Comment by joaomoreno** [comment]
Yeah you're right, to some extent. But it hasn't really been a problem so far. Also, you might hit other issues, as in people invoking vsce before comitting (you'd be surprised). For that reason, we felt it was less error prone to simply link to `main`.

**Comment by gismail** [comment]
> Adding `--no-rewrite-relative-links` option to `vsce package`.

It works very well , especially  for closed projects (inside company in which GitHub is GitHub enterprise and most organization are private and not accessible to all members )
