### ISSUE TITLE
vsce package should not check for publisher

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-vsce#328]
Repro:

- Clone a sample from https://github.com/Microsoft/vscode-extension-samples
- Run `vsce package`
- `vsce` should not check for `publisher` for generating the VSIX

**Comment by bkelley13** [comment]
For extension packs, too.

**Comment by bclinthall** [comment]
I'm having this issue too.

**Comment by bsed** [comment]
For extension packs, too.

**Comment by Supitto** [comment]
You can solve this by adding a 'publisher' field in package.json, vsce will generate the package with no problems

**Comment by SimoneRichetti** [comment]
I agree with the issue too. If I use a private npm repository to share my extension only with my colleagues I don't want to create an Azure organization. This check should be done when I publish to the public marketplace, not when I generate the vsix package.

**Comment by sergeiudris** [comment]
Yes, very sad, cannot build a vsix file locally, with even with a publisher field - `Error: Invalid publisher name` 
Is there a workaround/fork/alternative or *earlier version* (?) to build a .vsix file without publisher? (while this issue is being resolvled)

**Comment by SimoneRichetti** [comment]
Hi @sergeiudris, I had that error for two reasons:
1. My publisher name was not correct: only letters, numbers and hyphens are allowed;
2. I put local images in the README of the extension, which is not allowed, you can only put https links.

Maybe these tips are helpful. I link you the issue that I opened on another repo but correlated to this problem: https://github.com/joelspadin-garmin/vscode-private-extension-manager/issues/40#issuecomment-797697694

**Comment by sergeiudris** [comment]
@SimoneRichetti

> My publisher name was not correct: only letters, numbers and hyphens are allowed;

that solves it, thank you

**Comment by SimoneRichetti** [comment]
You are welcome!
I think that a lot of people are falling into this error. Maybe a mention of that should be added to the documentation? I mention @joaomoreno as the assignee of the issue.
