### ISSUE TITLE
Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED

### ISSUE THREAD

**Issue by faustinoaq** [Microsoft/vscode-vsce#332]
Hi @joaomoreno 

Latest version 1.55.0 prints this warning:

```
$ vsce list faustinoaq
(node:28011) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
javac-linter @ 1.3.1
```

This overwrites expected output (I have 3 extensions published, see: https://marketplace.visualstudio.com/publishers/faustinoaq)

My pc setup:

```
$ node -v
v11.6.0
$ npm -v
6.6.0
$ vsce -V
1.55.0
$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        18.0.2
Codename:       Illyria
```

Maybe Related? https://github.com/Microsoft/vscode-vsce/issues/320

I don't want to unpublish my packages, I see this warning everytime I use `vsce` to request some information from microsoft servers.

**Comment by joaomoreno** [comment]
What does `echo NODE_TLS_REJECT_UNAUTHORIZED` return?

**Comment by faustinoaq** [comment]
@joaomoreno Hi, do you mean `echo $NODE_TLS_REJECT_UNAUTHORIZED` ? :sweat_smile: 

I just updated it again to latest version and I still have this issue

```
$ echo NODE_TLS_REJECT_UNAUTHORIZED
NODE_TLS_REJECT_UNAUTHORIZED
$ echo $NODE_TLS_REJECT_UNAUTHORIZED

$ vsce list faustinoaq    
(node:4793) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
javac-linter @ 1.3.1
$ node -v
v11.6.0
$ npm -v
6.7.0
$ vsce -V
1.56.0
```

Also,  I tried to setup `export NODE_TLS_REJECT_UNAUTHORIZED=1` and even executing `NODE_TLS_REJECT_UNAUTHORIZED=1 vsce list faustinoaq` and still getting this warning.

**Comment by joaomoreno** [comment]
Yes I mean that!

**Comment by faustinoaq** [comment]
Still same warning :sweat_smile:  

```
$ NODE_TLS_REJECT_UNAUTHORIZED=0 vsce list faustinoaq
(node:6214) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
javac-linter @ 1.3.1
```

Maybe `NODE_TLS_REJECT_UNAUTHORIZED` is hardcoded somewhere else?

**Comment by joaomoreno** [comment]
Definitely not in VSCE... :thinking:

**Comment by faustinoaq** [comment]
Hi, I just updated to 1.57.0 and this warning is still showing.

All other functions (publishing, login) work fine :+1:

**Comment by selfrefactor** [comment]
I can also report that I have this issue.

**Comment by verde79** [comment]
I'm also experiencing it while doing `vsce login` or `vsce publish`

**Comment by DanTup** [comment]
I'm seeing this too when publishing:

```
Publishing Dart-Code.dart-code@2.26.1...
(node:8379) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
 DONE  Published Dart-Code.dart-code@2.26.1
```

I don't have this variable set:

```
$ echo $NODE_TLS_REJECT_UNAUTHORIZED

$ 
```

**Comment by joaomoreno** [comment]
There is nothing in VSCE which sets this variable. No idea what is going on.

**Comment by DanTup** [comment]
You have a dependency on `vso-node-api` which seems to have this in:

<img width="549" alt="Screenshot 2019-05-02 at 18 32 17" src="https://user-images.githubusercontent.com/1078012/57094510-a19b8280-6d08-11e9-92b2-93aef65ad685.png">

`typed-rest-client` has the same (looks like a copy of the same function).

Seems like an MS package, but npm says it's deprecated. It's not clear what the status is (or why they'd be doing this, it seems dangerous to be setting it for everyone in the way they are?).

🤔

**Comment by DanTup** [comment]
FWIW, looks like it was removed from `typed-rest-client` here:

https://github.com/Microsoft/typed-rest-client/pull/7

I don't know how that relates to `vso-node-api` though.

**Comment by joaomoreno** [comment]
I'm currently working on moving these dependencies forward.

**Comment by gurulinggaidhankar** [comment]
where is this line 
NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by HenokAddis** [comment]
One of our customers and one team member began hitting this on 1.40.0 when they attempted to upgrade their WAVE extension. Was this resolved? Sending the issue to them so they can also follow-up.

Error Message

> Unable to update the WAVE extension. (node:10124) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
> (node:10124) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification. Installing extensions...
> Extension 'c8acb7e1-6ab4-44c4-97c4-3c9b466e0ae9.vsix' was successfully installed.

**Comment by joaomoreno** [comment]
@HenokAddis What extension is that?

![image](https://user-images.githubusercontent.com/22350/68571512-76d27980-0463-11ea-80ed-d716f2cdd489.png)

Note that this is about VSCE. The problem was found in a dependency of it, so very likely it will be found in a dependency of that WAVE extension, so please give them an issue.

**Comment by jmullings** [comment]
Have you set the NODE_TLS_REJECT_UNAUTHORIZED to int, or the required "0" string...?

**Comment by bghita** [comment]
You have to set it as 1.
