### ISSUE TITLE
Recommend bundling extension

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-vsce#333]
When publishing vsce should count the files that end up in the bundle and recommend bundling. We see extensions that load very slow (30-40 seconds) and when bundled they usually load 10 times faster. Also installing benefits a lot from this and therefore its time to spread the news!

**Comment by joaomoreno** [comment]
Yeah good point. But we should probably also update the docs: https://code.visualstudio.com/api/working-with-extensions/publishing-extension

**Comment by jrieken** [comment]
We are tracking that here: https://github.com/Microsoft/vscode-docs/issues/2254#issuecomment-463718248
