### ISSUE TITLE
Check for webpack

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-vsce#334]
VSCE should check to see if an extension is webpack'd and if not, print out a link to the (forthcoming) documents on how to webpack an extension.  this will help the ecosystem keep/make VS Code fast.

**Comment by alefragnani** [comment]
That’s a great idea 👍 

I would suggest to add webpack option/configuration on [Yeoman generator](
https://github.com/Microsoft/vscode-generator-code) as well.
