### ISSUE TITLE
The specified icon 'extension/icon.png' wasn't found in the extension.

### ISSUE THREAD

**Issue by true0r** [microsoft/vscode-vsce#341]
I use snap for install node on Ubuntu 19.04. This causes a problem that I found only when debugging because the error message leads to a false way. 

This issue concerns node.js and there the question has already been raised and left unanswered (https://github.com/nodesource/distributions/issues/663). It is necessary providing a true error message to save time for those who have this problem.

```
$ vsce package

 ERROR  The specified icon 'extension/icon.png' wasn't found in the extension.
```
Below code is never called.

https://github.com/microsoft/vscode-vsce/blob/f4a3d0d356fabe1128b35643c3aa9b06083c9dae/src/package.ts#L526-L534

Call child_process.exec("only snap package") returns stdout and stderr as empty strings without error. 
https://github.com/microsoft/vscode-vsce/blob/f4a3d0d356fabe1128b35643c3aa9b06083c9dae/src/npm.ts#L55-L61

Call collectAllFiles() returns empty array.
https://github.com/microsoft/vscode-vsce/blob/f4a3d0d356fabe1128b35643c3aa9b06083c9dae/src/package.ts#L722-L733
Call processor.onFile() will not happen.
https://github.com/microsoft/vscode-vsce/blob/f4a3d0d356fabe1128b35643c3aa9b06083c9dae/src/package.ts#L761

Similar issue  #233.

**Comment by xontab** [comment]
I encountered the same issue ... The Snap version of NodeJS does not output the stdout when the following commands are used
```
cp.exec("npm....
cp.exec("node....
cp.exec("yarn....
```

Thus I managed to find a workaround by redirecting the output via `echo` (attached patch below).  However this workaround is not compatible with other systems and operating systems.

```
diff --git a/src/npm.ts b/src/npm.ts
index 6137a3c..456c111 100644
--- a/src/npm.ts
+++ b/src/npm.ts
@@ -23,7 +23,8 @@ function exec(command: string, options: IOptions = {}, cancellationToken?: Cance
        return new Promise((c, e) => {
                let disposeCancellationListener: Function = null;
 
-               const child = cp.exec(command, { ...options, encoding: 'utf8' } as any, (err, stdout: string, stderr: string) => {
+               // Added echo as a workaround for snap nodejs support
+               const child = cp.exec(`echo $(${command})`, { ...options, encoding: 'utf8' } as any, (err, stdout: string, stderr: string) => {
                        if (disposeCancellationListener) {
                                disposeCancellationListener();
                                disposeCancellationListener = null;
```

**Comment by paleo** [comment]
@xontab 
I didn't understood what we have to do. Should I reinstall Node.js without snap?

**Comment by xontab** [comment]
Yes, using Docker is even better :)  Maybe we should build a vsce docker image to avoid dependency issues.

**Comment by iamjameswalters** [comment]
I just encountered this issue on Ubuntu 20.04, node snap version 14.17.5 (latest stable at time of writing), while executing `npx vsce publish`. Has any progress been made toward a solution?

**Comment by joaomoreno** [comment]
This seems more like an issue with Node's snap package than VSCE, unfortunately. Nothing we can do here, but learn the workarounds.

**Comment by gerson-henrique** [comment]
Hi guys, I managed to work around the problem by dragging my icon to the theme development git, and simply pointing the filename in "icon": "logo.png". inside the .json package

**Comment by meghasinghal1** [comment]
Hi,

Can somebody please provide the resolution for above issue. I read above thread but couldn't get the resolution as I am still getting same error even with most recent version of VSCE.

![image](https://user-images.githubusercontent.com/13881466/180796225-7346af68-8b7d-4840-9c3f-cead1df8dab5.png)

Thanks

@true0r , @paleo , @gerson-henrique for the urgent help.

**Comment by joaomoreno** [comment]
What does `vsce ls` return?

**Comment by meghasinghal1** [comment]
Getting this when running vsce ls command.

![image](https://user-images.githubusercontent.com/13881466/181182112-b1853953-faeb-4ef2-9ca6-59fcd4095f0a.png)

**Comment by joaomoreno** [comment]
I don't see the icon listed there.

**Comment by jeff-hykin** [comment]
I hit this issue on MacOS (`vsce ls` always returns nothing)

```
npm --version          
7.1.1

node --version
v16.15.0

vsce --version
2.13.0
```

Changing the vsce version doesnt seem to fix anything, however downgrading node fixes the issue
This setup works:

```
npm --version          
7.1.1

node --version
v14.17.0

vsce --version
2.13.0
```

**Comment by ctjlewis** [comment]
Everyone who worked on the Microsoft teams that built the extensions API should not only be fired but tried at the Hague.

**Comment by ssbarnea** [comment]
@ctjlewis Frustrated? how about https://github.com/microsoft/vscode-vsce/pull/858 where fix was already approved by 4 people from community but no core bothered to merge it. Open-source is hard, especially for those that have  a long track of closed-source.
