### ISSUE TITLE
Recommend adding .vscodeignore

### ISSUE THREAD

**Issue by adamwatters** [microsoft/vscode-vsce#351]
Related to [Recommend adding .vscodeignore](https://github.com/microsoft/vscode-vsce/issues/333)

New extension developers might have extensions with lots of files even after bundling because they haven't added a .vscodeignore file (speaking from personal experience 🤣- my extension had 23409 separate files and took about a minute to install)

The message `This extension consists of ${files.length} separate files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension.` could be updated to include something like `You should also exclude unnecessary files by adding them to your .vscodeignore: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#.vscodeignore`

**Comment by joaomoreno** [comment]
Wanna submit a PR?
