### ISSUE TITLE
how to update a publisher to new PAT

### ISSUE THREAD

**Issue by lae0901** [microsoft/vscode-vsce#353]
running  vsce publish.  Getting errorAccess Denied: The Personal Access Token used has expired."  
 I ran "regenerate" in Azure DevOps against the PAT and got a new key.  

How to apply new key to the publisher?

I ran "vsce delete-publisher" and got the same "PAT used has expired" error.

**Comment by lae0901** [comment]
I run  vsce login pubName and get ERROR failed request 401.   How to find out the actual error?

$ vsce login Stevexxxx
Publisher 'Stevexxxx' is already known
Do you want to overwrite its PAT? [y/N] y
Personal Access Token for publisher 'Stevexxxx': ****************************************************

 ERROR  Failed request: (401)

**Comment by lae0901** [comment]
was able to publish directly on the manager publishers and extensions web page ...
https://marketplace.visualstudio.com/manage/publishers/Stevexxxx

**Comment by joaomoreno** [comment]
You can use `vsce login PUBLISHER_NAME` and then input your new PAT. Did you paste the correct new PAT?

**Comment by lae0901** [comment]
I get the same Failed request: (401)

in visualStudio.com I go to the personal access tokens page.  https://stephenxxxx.visualstudio.com/_usersSettings/tokens

There is one active token in my organization. Token name is my publisher name.  stevexxxx  I click the regenerate button.  Then copy to the clipboard. 

in vscode, at the command line, run "vsce login stevexxxx".  Get prompted for PAT.  paste it from clipboard. Get error: Failed request: (401)

I am up to date on the version of vsce.

**Comment by espresso3389** [comment]
I got the same with the newly created PAT with 1 year duration:(

**Comment by joaomoreno** [comment]
cc @viradhamMS @pkuma-msft Some help?

**Comment by smadala** [comment]
@espresso3389 @lae0901 
Did you create PAT with "All accessible organizations"? 

![VSCodePAT](https://user-images.githubusercontent.com/4337332/58455744-0d261380-8140-11e9-8d1d-5e45c64d29e5.PNG)

**Comment by espresso3389** [comment]
@smadala 
On the first try, I created another PAT with only Marketplace access as explained on [the article](https://code.visualstudio.com/api/working-with-extensions/publishing-extension) and got 401.
The second try with the all accessible organizations, but it also resulted in 401. 

I'm suspecting some kind of server side error because this is not the first time renewal of PAT token. I had done the same things successfully several times in the past.

**Comment by smadala** [comment]
@espresso3389 Can you share your publisher ID?

**Comment by smadala** [comment]
Never mind, Got it(same as your username)

**Comment by smadala** [comment]
@espresso3389 @lae0901 
We couldn't identify any error in our telemetry for your requests. Can you please send following information to VSMarketplace@microsoft.com?

1. Screenshots of PAT creation.
2. Fiddle trace of vsce command.

**Comment by lae0901** [comment]
it is working now.  able to publish an extension by running "vsce publish".

I changed the organization of the PAT to "all accessible organizations"

**Comment by self-creative** [comment]
**my publisher token is missing. how can i change my pat for publisher.**
`
vsce login myaccount
Personal Access Token for publisher 'myaccount': ****************************************************
 ERROR  {"$id":"1","customProperties":{"Descriptor":null,"IdentityDisplayName":null,"Token":null,"RequestedPermissions":0,"NamespaceId":"00000000-0000-0000-0000-000000000000"},"innerException":null,"message":"Access Denied: The Personal Access Token used has expired.","typeName":"Microsoft.VisualStudio.Services.Security.AccessCheckException, Microsoft.VisualStudio.Services.WebApi","typeKey":"AccessCheckException","errorCode":0,"eventId":3000}
`

**Comment by ngarg-panw** [comment]
Same here. I have lost the existing token. The person who generated the token first time is no longer with the team. How can I associate a new token from a new account to existing publisher?
I tried creating a token from new account and it says:
 ERROR  Access Denied: abcxyzteam needs the following permission(s) on the resource /Pxxxxx to perform this action: View user permissions on a resource
Any pointers are helpful.

**Comment by DanielAtKrypton** [comment]
I am having the following errror with the generated PAT with access to all organizations:
```bash
 ERROR  Access Denied: Microsoft.IdentityModel.Claims.ClaimsIdentity;0003000038AF1F2A@Live.com needs the following permission(s) on the resource /MachineAtKrypton to perform this action: View user permissions on a resource
```

**Comment by PeterWone** [comment]
> @espresso3389 @lae0901
> Did you create PAT with "All accessible organizations"?
> 
> ![VSCodePAT](https://user-images.githubusercontent.com/4337332/58455744-0d261380-8140-11e9-8d1d-5e45c64d29e5.PNG)

This is the answer. The token has to be validated with one organisation and used with another. 

Why have people voted this down? Because they don't like the fact that it's true?

**Comment by Blaiski** [comment]
I'm getting the exact same error after my PAT expired and I generated a new one. I did select 'All accessible Organizations' and have repeated and examined three times... had to resort to publishing manually through your publisher portal.
![Screen Shot 2023-07-18 at 3 40 45 PM](https://github.com/microsoft/vscode-vsce/assets/31612240/48885151-81e1-44fc-9309-aaa31cea459a)

**Comment by Blankeos** [comment]
Happening for me as well.

```

{"$id":"1","customProperties":{"Descriptor":null,"IdentityDisplayName":null,"Token":null,"RequestedPermissions":0,"NamespaceId":"00000000-0000-0000-0000-000000000000"},"innerException":null,"message":"Access Denied: The Personal Access Token used has expired.","typeName":"Microsoft.VisualStudio.Services.Security.AccessCheckException, Microsoft.VisualStudio.Services.WebApi","typeKey":"AccessCheckException","errorCode":0,"eventId":3000}
```
