### ISSUE TITLE
Relative paths in READMEs are being directed at raw instead of rendered contents

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode-vsce#36]
I'm not sure whether this is a `vsce` issue or a gallery issue.

Relative paths from READMEs are being redirected to GitHub, which is nice, but they appear to be redirected to /raw which looks pretty bad – seems they can be directed to the normal GitHub page instead which renders content in the expected way (e.g. As markdown):

Current:
https://github.com/Microsoft/vscode-go/raw/master/src/debugAdapter/Readme.md

Expected:
https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/Readme.md

**Comment by lukehoban** [comment]
I'm now seeing the path be rewritten to:

https://github.com/Microsoft/vscode-go/src/debugAdapter/Readme.md

But that path 404s - the expected path is:

https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/Readme.md

**Comment by joaomoreno** [comment]
Fixed in `0.8.1`. Can you give it a try?
