### ISSUE TITLE
How about showing up an ASCII flavoured banner?

### ISSUE THREAD

**Issue by jamesgeorge007** [microsoft/vscode-vsce#360]
![Screenshot from 2019-06-12 16-13-21](https://user-images.githubusercontent.com/25279263/59345338-82dbd300-8d2d-11e9-9e6b-1a06cc73f50c.png)

**Comment by jamesgeorge007** [comment]
@joaomoreno Thoughts: thinking:

**Comment by jamesgeorge007** [comment]
@joaomoreno Thoughts :thinking:

**Comment by jamesgeorge007** [comment]
There is a [node-banner](https://npmjs.com/package/node-banner) package for the purpose.

**Comment by joaomoreno** [comment]
Although cool :sunglasses:, I think this isn't really necessary...

**Comment by jamesgeorge007** [comment]
@joaomoreno Well, do you plan to include it in the future :thinking: 
Are you just worried about the dependency tree as given above?

**Comment by joaomoreno** [comment]
> @joaomoreno Well, do you plan to include it in the future :thinking: 

Not really, closing this.
