### ISSUE TITLE
[Question] How to integrate vsce publish to an azure pipeline

### ISSUE THREAD

**Issue by Raagh** [microsoft/vscode-vsce#361]
So I created an azure build pipeline for packaging my vscode extension into a vsix. I have uploaded that vsix as an artifact so it can be used in a release pipeline.

but know I dont know how could I use vsce publish inside a release pipeline. do you guys have any idea how the release pipeline would look like for publishing and extension?

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/api/working-with-extensions/continuous-integration#azure-pipelines

**Comment by Raagh** [comment]
Hi @joaomoreno thanks for your response, already read that unfortunately only covers the part about CI, not the CD. CI was not the problem. The problem was how to make a release pipeline upload the extension to the marketplace using proper publisher id and personal access token.

in case somebody comes here and its interested I manage to solve it by after a build pipeline that publish the packaged vsix as an artifact. Adding 2 artifact references(github repo and packaged vsix) to the release pipeline and having 2 tasks on my release pipeline, one npm for installing vsce globaly and a command line for running vsce publish -p {{PERSONAL ACCESS TOKEN}}.

**Comment by moshfeu** [comment]
And in case your extension is public and you don't want to expose PAT to the world, follow this answer: https://stackoverflow.com/q/58192624/863110

**Comment by joaomoreno** [comment]
Thanks for that @Raagh and @moshfeu, I'll update the guide with extra steps for publishing.
