### ISSUE TITLE
Does not create .vsx file or throw warnings.  

### ISSUE THREAD

**Issue by jm06487** [microsoft/vscode-vsce#362]
Does not throw warnings or create .vsix file.  Just hangs. 
![4279FF7F-2B15-44A0-9AA2-CE4DE530C325](https://user-images.githubusercontent.com/10539923/59511396-27702900-8e84-11e9-8132-cbc7d06d3770.png)

**Comment by joaomoreno** [comment]
What happens if you run `npm run vscode:prepublish` yourself?

**Comment by jm06487** [comment]
I have a webpack configured as the bundler. When I run "npm run vscode:prepublish" package.json script is "webpack --mode production", it bundles - then hangs.  If I change the bundler to just typescript it will create the .vsix file.  I have attached a zip with all the config files to help diagnose the issue. 
[commitmessagemanager.zip](https://github.com/microsoft/vscode-vsce/files/3313412/commitmessagemanager.zip)

**Comment by joaomoreno** [comment]
> When I run "npm run vscode:prepublish" package.json script is "webpack --mode production", it bundles - then hangs. 

You have to figure out why that hangs. Once you fix that, VSCE won't hang as well. Try asking a question in StackOverflow about why your webpack project hangs.
