### ISSUE TITLE
Don't use WARNING for message about version

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode-vsce#367]
>  **WARNING** The latest version of vsce is 1.64.0 and you have 1.63.0.
Update it now: npm install -g vsce

Could you please use INFO level?

**Comment by joaomoreno** [comment]
PR?

**Comment by atsutton** [comment]
Hey @joaomoreno, can I take a crack at this?

**Comment by atsutton** [comment]
Great, I'll get working on this.

**Comment by atsutton** [comment]
Hey @joaomoreno, I just sent pr #369 regarding this issue.
