### ISSUE TITLE
Publish error :  ERROR  Missing publisher name.

### ISSUE THREAD

**Issue by RufusWein** [microsoft/vscode-vsce#368]
Well, Yesterday I did my first extension and today when I going to publish it doesn't work.

**vsce create-publisher rufuswein**
[OK]

**vsce login rufuswein**
[OK]

**vsce ls-publishers**
rufuswein [OK]

**vsce publish**
ERROR  Missing publisher name. Learn more: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions [WTF!]

**vsce package**
ERROR  Missing publisher name. Learn more: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions [WTF!]

**vsce -V**
1.64.0[OK]

**node --version**
v10.16.0[OK]

**npm --version**
6.9.0[OK]

**git --version**
git version 2.21.0.windows.1

All post about a like issue it has not helped me to solve this.
https://github.com/Microsoft/vscode-vsce/issues/110
https://github.com/Microsoft/vscode-vsce/issues/86

My Git repositorie:
https://github.com/RufusWein/saveall

**Comment by joaomoreno** [comment]
From https://code.visualstudio.com/api/working-with-extensions/publishing-extension#create-a-publisher

> A publisher is an identity who can publish extensions to the Visual Studio Code Marketplace. Every extension needs to include a publisher name in its package.json file.

Eg:

```json
	"publisher": "rufuswein"
```

**Comment by RufusWein** [comment]
Ok João is that, thank you very much.

**Comment by tweakimp** [comment]
It would be better if the error message told us **WHERE** it is missing.

**Comment by spartanroger** [comment]
Also, the yeoman vscode ext generator could bring this by default

**Comment by ORESoftware** [comment]
this error is not good. it should say:

```
missing "publisher" field in package.json
```

very dumb error message

**Comment by jfthuong** [comment]
> Also, the yeoman vscode ext generator could bring this by default

I have created an issue for yeoman generator: https://github.com/microsoft/vscode-generator-code/issues/200

**Comment by aeschli** [comment]
Maybe vsce can prompt for a publisher (or suggest the logged-in user) and update `package.json`?

We removed the `What your publisher` prompt from `yo code` as it confused a lot of new users. It's better to start worry about the publisher once you are ready to publish.

**Comment by HansUXdev** [comment]
I published an extension in the past and didn't need this. I don't get why any coder or company would introduce a breaking change and not update the docs especially a big company like Microsoft... I'd be happy to get paid the salary they get paid and finish the job I'm getting paid to do...

**Comment by augwu-thortech** [comment]
The issue seems to be that a user gets orphaned when they hit this step. The page which is link makes the solution non-obvious, is buried in the page, and links to an even more generic doc.

**Comment by waseemhnyc** [comment]
I see this issue is closed. I am visiting here because the error message did not give me an idea of where I should include the publisher name. I like @ORESoftware idea

> this error is not good. it should say:
> 
> ```
> missing "publisher" field in package.json
> ```
> 
> very dumb error message
