### ISSUE TITLE
vsce ls does not show any files

### ISSUE THREAD

**Issue by Revilotom** [microsoft/vscode-vsce#374]
Running 
```
$ vsce ls 
```
Does not show any files for me. 
What am I doing wrongly?

**Comment by joaomoreno** [comment]
What is your full project structure?

**Comment by Revilotom** [comment]
The reason there is a "dist" as well as an "out" folder is because I was planning to use webpack for production (dist folder) and the default build system for development (out folder)

```
$ tree -L 2
.
├── dist
│   ├── extension.js
│   └── extension.js.map
├── node_modules
..........
├── out
│   ├── extension.js
│   ├── extension.js.map
├── package.json
├── package-lock.json
├── README.md
├── src
│   ├── extension.ts
├── tsconfig.json
├── tslint.json
└── webpack.config.js

```
I have simplified by removing unrelated files and a modules directory from the "src" folder

**Comment by joaomoreno** [comment]
Do you have a `.vscodeignore` file?

**Comment by Revilotom** [comment]
Yes but it is empty

**Comment by joaomoreno** [comment]
If you remove it, does vsce list any files? Which version of vsce do you have?

**Comment by Revilotom** [comment]
I tried removing it but it made no difference for me.

```
$ vsce --version
1.65.0
```
You can access the root directory of the extension code by doing:

```
git clone https://github.com/conjure-cp/conjure
cd conjure
git checkout loadcore
cd ide
```

**Comment by joaomoreno** [comment]
I can't reproduce. I've cloned it and ran those steps. I've also run `npm install`. Then, running `vsce ls` gives me the following output: https://gist.github.com/joaomoreno/9762b05760193c5df265680c28a2232a

What platform are you on?

**Comment by Revilotom** [comment]
Trying it on another system it seems to work fine just like you said..😕
The system it doesn't work on has the following environment:
```
$ uname -a 
Linux mai 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ npm -v
6.10.0

$ node --version
v10.14.2
```

**Comment by joaomoreno** [comment]
How fast does `vsce ls` run? `time vsce ls`

**Comment by Revilotom** [comment]
```
$ time vsce ls
 ERROR  { Error: Command failed: npm show vsce version

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 243,
  signal: null,
  cmd: 'npm show vsce version' }

real    0m3.532s
user    0m5.011s
sys     0m0.348s
```

**Comment by xontab** [comment]
@Revilotom Are you using the Snap NodeJS version or deb?  

I have encountered issues with the Snap version and looks like this issue is related to https://github.com/microsoft/vscode-vsce/issues/341

**Comment by Revilotom** [comment]
@xontab Unfortunately I no longer have access to the PC that had this issue so I cant be sure but yes I think I was using Snap.
