### ISSUE TITLE
Having a dedicated command to show up local environment information

### ISSUE THREAD

**Issue by jamesgeorge007** [microsoft/vscode-vsce#377]
As in #372 there was a need to know the local environment information of the user to better understand the issue. IMO there should be a dedicated command for the purpose. 

## Proposed API

`vsce info`

> We could utilize [envinfo](https://npmjs.com/package/envinfo)

**Comment by jamesgeorge007** [comment]
cc @joaomoreno

**Comment by joaomoreno** [comment]
Let's not build this into vsce. People can simply use envinfo directly.
