### ISSUE TITLE
vsce finding wrong files without `--yarn` option

### ISSUE THREAD

**Issue by flimberger** [microsoft/vscode-vsce#381]
When packaging my extension, vsce failed with the following error message:

    $ vsce package
    This extension consists of 20743 separate files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension. You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
     ERROR  invalid relative path: extension/../../../../lib/nodejs/lib/node_modules/generator-code/.azure-pipelines.yml

Running `vsce` reveals that it tries to pack up the whole global node_modules directory of my user:

    $ vsce ls
    ../../../../lib/nodejs/lib/node_modules/generator-code/.azure-pipelines.yml
    ../../../../lib/nodejs/lib/node_modules/generator-code/generators/app/env.js
    [... 20737 more lines ...]
    ../../../../lib/nodejs/lib/node_modules/yo/node_modules/wrap-ansi/node_modules/ansi-regex/package.json
    ../../../../lib/nodejs/lib/node_modules/yo/node_modules/wrap-ansi/node_modules/ansi-regex/readme.md

Adding the `--yarn` flag produces the expected behaviour and works in the current directory:

    $ vsce ls --yarn
    CHANGELOG.md
    language-configuration.json
    LICENSE
    Makefile
    package.json
    README.md
    syntaxes/blueprint.tmLanguage.json
    $ vsce package --yarn
     DONE  Packaged: /home/flimberger/devel/plugins/vscode/android-system-tools/android-system-tools-0.0.2.vsix (9 files, 5.17KB)

My extension doesn't contain any code, therefore I expected the packaging progess to be agnostic to whether npm or yarn is used.

Platform: Ubuntu 18.04
Version: 1.66.0
Environment:

    NPM_CONFIG_PREFIX="$HOME/lib/nodejs"
    NPM_CONFIG_USERCONFIG="$HOME/lib/config/npmrc"
    NODE_PATH="$NPM_CONFIG_PREFIX/lib/node_modules:/usr/lib/nodejs"
    PATH="$NPM_CONFIG_PREFIX/bin:$PATH"

NPM configuration:

    global=true

**Comment by joaomoreno** [comment]
> My extension doesn't contain any code, therefore I expected the packaging progess to be agnostic to whether npm or yarn is used.

Does it have a `package.json`? Does it have any dependencies? Can you show me the sources of your extension?

**Comment by flimberger** [comment]
The extension is [here](https://github.com/flimberger/android-system-tools), the `package.json` in question was mainly generated by yeoman, with some additional info by myself:

    {
        "name": "android-system-tools",
        "displayName": "Android System Tools",
        "description": "Syntax support for file formats used in Android system development.",
        "version": "0.0.2",
        "publisher": "flimberger",
        "repository": {
            "type": "git",
            "url": "git+https://github.com/flimberger/android-system-tools.git"
        },
        "license": "BSD-2-Clause",
        "engines": {
            "vscode": "^1.36.0"
        },
        "categories": [
            "Programming Languages"
        ],
        "contributes": {
            "languages": [{
                "id": "blueprint",
                "aliases": ["Android Blueprint", "blueprint"],
                "extensions": [".bp"],
                "configuration": "./language-configuration.json"
            }],
            "grammars": [{
                "language": "blueprint",
                "scopeName": "source.bp",
                "path": "./syntaxes/blueprint.tmLanguage.json"
            }]
        }
    }

**Comment by joaomoreno** [comment]
This packages just fine for me. Do you have more files in your local copy of that repository? Any symlinks?

**Comment by flimberger** [comment]
No symlinks in the repo, but I've moved the npm stuff with the `NPM_CONFIG_PREFIX` environment variable from the default locations. I will test without these redirections.

**Comment by justinfagnani** [comment]
I'm having the same problem in a monorepo that does have symlink to the sibling packages, but where I'm trying to ignore them by including `node_modules` in the .vscodeignore file. It seems like the `node_modules` isn't working, _or_ the "invalid relative path" error is being emitted before ignoring files.

**Comment by acccrop** [comment]
I also have the same problem. is there a solution to this?

**Comment by flimberger** [comment]
I cannot reproduce the issue anymore with vsce version 2.7.0 and node version v16.15.0 installed from snap on Ubuntu 20.04.

**Comment by flimberger** [comment]
That assessment was too soon, running `vsce package` asks if it should continue, since no license file can be found. If I continue, the package does not contain the `extension` directory. So unfortunately the issue is *not* fixed.

**Comment by redonkulus** [comment]
Was getting this same issue and `--yarn` worked for me until recently, I noticed using the `--no-dependencies` option avoided this issue as well.

**Comment by nagilson** [comment]
Experiencing the same issue because of npm links, might be related to https://github.com/microsoft/vscode-vsce/issues/308

**Comment by vindicatorr** [comment]
Yeah, I don't know why this is still closed...
https://github.com/dotnet/vscode-dotnet-runtime
`./Documentation/contributing-workflow.md`

`$ cd ../vscode-dotnet-runtime-extension`

Without yarn (fail):
```
$ vsce package --ignoreFile ../.vscodeignore --no-yarn
<...>
INFO  Files included in the VSIX:
vscode-dotnet-runtime-2.4.1.vsix
├─ [Content_Types].xml 
├─ extension.vsixmanifest 
└─ extension/
   ├─ .npmrc.bak [0.09 KB]
   ├─ LICENSE.txt [1.1 KB]
   ├─ changelog.md 
   ├─ package-lock.json.bak [174.14 KB]
   ├─ package.json [10.45 KB]
   ├─ readme.md 
   ├─ tsconfig.json [0.3 KB]
   ├─ ../
   │  └─ vscode-dotnet-runtime-library/
   │     └─ node_modules/ (5778 files) [146.26 MB]
   ├─ dist/
   │  ├─ DotnetCoreAcquisitionId.d.ts [0.09 KB]
   │  ├─ DotnetCoreAcquisitionId.js [0.58 KB]
   │  ├─ DotnetCoreAcquisitionId.js.map [0.18 KB]
   │  ├─ extension.d.ts [0.28 KB]
   │  ├─ extension.js [960.63 KB]
   │  ├─ extension.js.LICENSE.txt [1.18 KB]
   │  ├─ extension.js.map [4.06 MB]
   │  ├─ distro-data/
   │  │  └─ distro-support.json [28.14 KB]
   │  └─ install scripts/
   │     ├─ determine-linux-distro.sh [0.85 KB]
   │     ├─ install-linux-prereqs.sh [7.36 KB]
   │     └─ interprocess-communicator.sh [1.88 KB]
   └─ images/
      └─ dotnetIcon.png [4.72 KB]

=> Run vsce ls --tree to see all included files.

 ERROR  invalid relative path: extension/../vscode-dotnet-runtime-library/node_modules/@types/chai-as-promised/package.json
```

With yarn (success):
```
$ vsce package --ignoreFile ../.vscodeignore --yarn
<...>
 INFO  Files included in the VSIX:
vscode-dotnet-runtime-2.4.1.vsix
├─ [Content_Types].xml 
├─ extension.vsixmanifest 
└─ extension/
   ├─ .npmrc.bak [0.09 KB]
   ├─ LICENSE.txt [1.1 KB]
   ├─ changelog.md 
   ├─ package-lock.json.bak [174.14 KB]
   ├─ package.json [10.45 KB]
   ├─ readme.md 
   ├─ tsconfig.json [0.3 KB]
   ├─ dist/
   │  ├─ DotnetCoreAcquisitionId.d.ts [0.09 KB]
   │  ├─ DotnetCoreAcquisitionId.js [0.58 KB]
   │  ├─ DotnetCoreAcquisitionId.js.map [0.18 KB]
   │  ├─ extension.d.ts [0.28 KB]
   │  ├─ extension.js [960.63 KB]
   │  ├─ extension.js.LICENSE.txt [1.18 KB]
   │  ├─ extension.js.map [4.06 MB]
   │  ├─ distro-data/
   │  │  └─ distro-support.json [28.14 KB]
   │  └─ install scripts/
   │     ├─ determine-linux-distro.sh [0.85 KB]
   │     ├─ install-linux-prereqs.sh [7.36 KB]
   │     └─ interprocess-communicator.sh [1.88 KB]
   └─ images/
      └─ dotnetIcon.png [4.72 KB]

 DONE  Packaged: /<pathTo>/vscode-dotnet-runtime/vscode-dotnet-runtime-extension/vscode-dotnet-runtime-2.4.1.vsix (21 files, 1.35 MB)
```

The key thing I see is `node_modules/ (5778 files) [146.26 MB]` without yarn (fail) being excluded with yarn.
Yet `yarn.lock` gives: `"vscode-dotnet-runtime-library@file:../vscode-dotnet-runtime-library":<...>` dependencies.
`.vscodeignore` gives: `node_modules/**`, so it shouldn't be getting included in the no-yarn build? And the library module dependencies would get folded into `extension.js`?
