### ISSUE TITLE
Package command suggested bundling hyperlink is broken

### ISSUE THREAD

**Issue by jsnee** [microsoft/vscode-vsce#384]
Just something I noticed, when packaging a large extension, vsce suggests bundling, but the link that is provided includes the period at the end of the sentence as part of the hyperlink making the link not work properly.
![image](https://user-images.githubusercontent.com/2386345/63173693-02c03b00-c006-11e9-82a5-1c0d92a963ec.png)

**Comment by joaomoreno** [comment]
That's actually an issue with the terminal you're using, but sure we can remove the dot.
