### ISSUE TITLE
create-publisher error TF400813

### ISSUE THREAD

**Issue by flpgdn** [microsoft/vscode-vsce#386]
When I try to create my publisher I get the following error:

```
{ 
    "$id": "1", 
    "innerException": null, 
    "message": "TF400813: Resource not available for anonymous access. Client authentication required.", 
    "typeName": "Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server", 
    "typeKey": "UnauthorizedRequestException", 
    "errorCode": 0, 
    "eventId": 3000 
}
```
![PAT](https://user-images.githubusercontent.com/15850008/64223076-e008a000-cea8-11e9-938e-586d21ee2920.PNG)
![Prompt](https://user-images.githubusercontent.com/15850008/64223077-e008a000-cea8-11e9-9662-f5b0b3c7792d.png)

**Comment by joaomoreno** [comment]
Are you sure you entered your Personal Access Token? The character `*` should appear as you type/paste it.

**Comment by flpgdn** [comment]
I was copying and pasting PAT, for some reason the paste didn't work.

Many security cases do not display the characters entered, I thought it was that way, so I ended up not typing and figured it was correct.

I'm sorry for this.

**Comment by qb20nh** [comment]
Check if any whitespace characters are included when you copy

**Comment by mao-santaella-rs** [comment]
Same thing is happening to me rn
