### ISSUE TITLE
vsce package cannot package that I did change？

### ISSUE THREAD

**Issue by gitHber** [microsoft/vscode-vsce#393]
I already vsce package version 0.0.1. 
And I code something change, So I package again, But I install new package, There is no change,
I have to change version and package to make It work.
Package just for test，why did I have to change my version？

**Comment by joaomoreno** [comment]
When you run `vsce package`, does the .vsix file not get overwritten?

**Comment by wingyplus** [comment]
@joaomoreno I found the same issue on my extensions (https://github.com/wingyplus/emacsplus). And the step is: 

1. I installed extension that I wrote myself with version 0.1.0 (refer to commit https://github.com/wingyplus/emacsplus/commit/eb9b1a735c9e9f5d051636fbee27dd59f80e5598).
2. I found a bug on my extensions. Fixing it and build my extension to with `vsce package` (refer to commit https://github.com/wingyplus/emacsplus/commit/dec2b458801687c26a866ec8bd51571bd4d3686c, still be on version 0.1.0). 
3. I remove my extension from vscode ui. And install it via by `Install from VSIX` command in vscode. 
4. I see that my extensions not work as expected. 

After I explore what is going on, I found that:

1.  My extension inside `~/.vscode/extensions` did not removed after I uninstalled it from vscode. 
2. So I deleted it by using `~/.vscode/extensions/wingyplus.emacsplus-0.1.0`. 
3. Installed it via vscode. It's works!!!

After reproduced that. I start thinking that it'll be an issue with vscode itself not vsce?

**Comment by joaomoreno** [comment]
Yes that is indeed a VS Code behavior, not VSCE.

@sandy081 Do you think this is worth tackling? Reinstalling a VSIX shouldn't reuse the cached version we temporarily leave around after uninstall.

**Comment by sandy081** [comment]
Agreed. Installing a VSIX should always use the given VSIX. 

@wingyplus Please file an issue in https://github.com/microsoft/vscode/issues

**Comment by wingyplus** [comment]
@sandy081 @joaomoreno Thanks for your help. I’ll open it asap.
