### ISSUE TITLE
Force unpublish extension from marketplace

### ISSUE THREAD

**Issue by dilin-MS** [microsoft/vscode-vsce#400]
Hi, I wonder are there any way to force unpublish extension from marketplace instead of interactively asking me `This will FOREVER delete 'XX.XXX'! Are you sure? [y/N]`

The scenario is that I will publish test version extension on marketplace with id "dilin.my-test-extension". The extension is pushed to marketplace in CI/CD. Since the extension is just a test version extension, it's version will always be the same for the same release of main extension. If we fix some issues and would like to publish the test extension to marketplace, considering the version does not change, we need to unpublish the former one from marketplace and publish the new one.

I would like to have a script like `vsce unpublish -p <my-PAT> dilin.my-test-extension` in CI/CD script. The problem is that this command is interactive and will ask me to confirm `Yes`. Are there any way to force unpublish extension from marketplace? A `-f` option for example.
THX!

**Comment by Grommers00** [comment]
Could I try this issue?

**Comment by dilin-MS** [comment]
Hi, later I discover a workaround to achieve my goal: `yes | vsce unpublish -p <my-PAT> dilin.my-test-extension`

**Comment by connor4312** [comment]
This doesn't appear to have published successfully, so I'm unable to test it.

[`vsce@1.70.0`](https://github.com/microsoft/vscode-vsce/releases/tag/v1.70.0) was revved after merging Jame's PR, but the flag isn't in the unpublish options or the compiled code.

```
➜  test-extension git:(master) ✗ vsce --version
1.70.0
➜  test-extension git:(master) ✗ vsce unpublish --help
Usage: unpublish [options] [<extensionid>]

Unpublishes an extension. Example extension id: microsoft.csharp.

Options:
  -p, --pat <token>  Personal Access Token
  -h, --help         output usage information
➜  test-extension git:(master) ✗ vsce unpublish --force foo
error: unknown option `--force'
```

**Comment by sandy081** [comment]
This is not published yet. So reopening until it is published.

**Comment by joaomoreno** [comment]
Coming out in 1.71.0.
