### ISSUE TITLE
Bad warning "For performance reasons, you should bundle your extension" when extension contains non-code resources

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode-vsce#402]
I recently started shipping some icons inside my extension to avoid relying on a net connection. I now get this warning when building:

> This extension consists of 2277 separate files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore

My extension is bundled, and has only one script file. The rest of the files are mostly just a folder full of PNG icons which may be displayed in tooltips or gutter icons.

I think the printing of this warning should have some filtering that it's only looking at JS files?

https://github.com/microsoft/vscode-vsce/blob/282b740301e25318c4802d67ad31581f39ebb064/src/package.ts#L944

**Comment by joaomoreno** [comment]
Agreed... but the extension actually ships +2k icons? :fearful:

**Comment by joaomoreno** [comment]
Changed the limit to 5k files and kept the 100 limit for JavaScript files only.

**Comment by DanTup** [comment]
Yeah, they're icons that the Flutter provides (see https://api.flutter.dev/flutter/material/Icons-class.html). We include them in the documentation/hovers and in the gutter, like this:

<img width="386" alt="Screenshot 2019-10-09 at 8 55 41 am" src="https://user-images.githubusercontent.com/1078012/66462242-97796f00-ea72-11e9-97ca-490818164cd9.png">

I have a git submodule that includes them so I can ship them in the extension so they'll work offline. To be fair, half of them aren't currently usable (there are Material icons and Cupertino icons, but only the Materials work right now), but it didn't seem like it'd be a big deal to include :-)

**Comment by joaomoreno** [comment]
> I have a git submodule that includes them so I can ship them in the extension so they'll work offline. To be fair, half of them aren't currently usable (there are Material icons and Cupertino icons, but only the Materials work right now), but it didn't seem like it'd be a big deal to include :-)

Then the warning actually applies. One thing webpack does is remove all unused things. You could potentially write a tool which does the same in your scenario (omit them at packing time) instead of shipping them all.

**Comment by DanTup** [comment]
@joaomoreno I probably described it badly. The ones that are currently unused are all on a single folder and I could just delete that folder. The other folder are all *potentially* used because they depend on which icons the user users in their code (we need to ship them all, so if they use that icon, we can show its preview). We can't know up-front which ones we'll need (other than the Cupertino folder not being used - but I hope that's a temporary restriction and we'll support them eventually too).

Short of going back to pulling them from the web (which breaks them working offline) I don't see any way around this (they're used in `gutterIconPath`s for decorations, so there's no way to use a sprite sheet or anything either).

If you think there's a better way, I'm open to ideas - but I figured there wasn't really a drawback to doing this (other than the 8MB of disk space when uncompressed :-))
