### ISSUE TITLE
[chore]: no code linters found

### ISSUE THREAD

**Issue by jamesgeorge007** [microsoft/vscode-vsce#408]
It is a good practice to use a code linter which results in maintainable code. We could also make use of `pre-commit` hooks which would ease the Dev workflow in the long run.

**Comment by joaomoreno** [comment]
By now TypeScript ships with a *lot* of linting rules. We don't need to bring in extra linters any more. We just have to slowly move the codebase forward and adopt those rules (strict null checks, strict initializations, etc).
