### ISSUE TITLE
Link-like structures in code blocks in README.md get adjusted

### ISSUE THREAD

**Issue by masterzenox** [microsoft/vscode-vsce#410]
Things like a `[some_char_set](some_group)` regex inside inline and fenced code blocks get transformed into `[some_char_set](https:/github/author/package/blob/master/some_group)`. [Headwind's](https://marketplace.visualstudio.com/items?itemName=heybourn.headwind) `headwind.classRegex` description is an example of such behaviour.

As of now I don't have time to work on a solution, but i see 2 options:
- Maybe we can edit the `markdownPathRegex` in [package.ts](https://github.com/microsoft/vscode-vsce/blob/master/src/package.ts#L386-L406) to not match links inside backticks (can be hard, especially with arbitrary code inside the same code block)
- Implement a markdown parser like [remark](https://github.com/remarkjs/remark), which could also solve other problems like #398

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode-vsce/issues/375
