### ISSUE TITLE
In Git history, earlier commits logs are blocked by floating window.

### ISSUE THREAD

**Issue by libth** [microsoft/vscode-vsce#413]
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-73-generic

![Screenshot from 2020-01-17 17-23-59](https://user-images.githubusercontent.com/1264920/72600471-aa8fbb00-394e-11ea-8c98-99d3872fd5f4.png)

when one commit was selected, a floating window comes out from the bottom of this window to show details of that commit, and it blocks all commits behind. 
I think it's better to layout them side by side.

**Comment by joaomoreno** [comment]
Which extension contributes this view?

**Comment by libth** [comment]
Sorry, github been blocked here for a while.
Turns out it's a **git-history** extension's problem, I thought it was in vs-code built-in git view.
