### ISSUE TITLE
vsce publish fails

### ISSUE THREAD

**Issue by vignaesh01** [microsoft/vscode-vsce#414]
vsce version 1.71.0
node version v10.15.3
npm version 6.4.1

vsce publish fails with the below message:

Executing prepublish script 'npm run vscode:prepublish'...

> sfdx-command-builder@0.1.0 vscode:prepublish C:\Projects\VS Code Extensions\sfdx-command-builder
> npm run compile

> sfdx-command-builder@0.1.0 compile C:\Projects\VS Code Extensions\sfdx-command-builder
> tsc -p ./

 ERROR  Command failed: npm list --production --parseable --depth=99999
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.14.0
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.3
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.4, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.2, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.2, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.3
npm ERR! missing: inherits@2.0.4, required by glob@7.1.6
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.6
npm ERR! missing: once@1.4.0, required by glob@7.1.6
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.9.0, required by tar@4.4.13
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.13
npm ERR! missing: safe-buffer@5.1.2, required by tar@4.4.13
npm ERR! missing: yallist@3.1.1, required by tar@4.4.13
npm ERR! missing: minipass@2.9.0, required by fs-minipass@1.2.7
npm ERR! missing: safe-buffer@5.1.2, required by minipass@2.9.0
npm ERR! missing: yallist@3.1.1, required by minipass@2.9.0
npm ERR! missing: minipass@2.9.0, required by minizlib@1.3.3

**Comment by joaomoreno** [comment]
Did you run `npm install`?

**Comment by vignaesh01** [comment]
This got fixed now. Thank you
