### ISSUE TITLE
"vsce publish" command returns Invalid publisher name 'Siarhei Kuchuk'. Expected the identifier of a publisher, not its human-friendly name. 

### ISSUE THREAD

**Issue by drweb86** [microsoft/vscode-vsce#419]
Hello

I did not specify the publisher name in this command but it complains about it. I tried to reinstall it, but it still gets publisher name from somewhere

Thanks.

**Comment by drweb86** [comment]
I figured it out. It reads publisher name from package.json of extension. And there it should be id and not name of publisher.

**Comment by CartBlanche** [comment]
@drweb86 I'm getting the same error and I can't find in the documentation how to get an id instead of a full publisher name. Can you point me to to the right place?

**Comment by drweb86** [comment]
@CartBlanche 
![image](https://user-images.githubusercontent.com/4712173/158873214-ec34c6ff-1a42-4397-b529-e95d72bfb090.png)

**Comment by CartBlanche** [comment]
@drweb86 Thanks. That helps a lot!
