### ISSUE TITLE
Support pnpm

### ISSUE THREAD

**Issue by muuvmuuv** [microsoft/vscode-vsce#421]
I tried publishing my extension but recently switched to use [pnpm](https://pnpm.js.org/) instead of npm. `vsce` seems to not support this package manager (does `yarn` even works, very similar to `pnpm`) since it tries to do `npm list --production --parseable --depth=99999` which fails in pnpm projects because of the different handling of dependencies.

Project: https://github.com/muuvmuuv/vscode-sundial

Error:

```
❯ npm list --production --parseable --depth=99999
/Users/marvinheilemann/Development/VSCode/vscode-sundial
/Users/marvinheilemann/Development/VSCode/vscode-sundial/node_modules/dayjs
/Users/marvinheilemann/Development/VSCode/vscode-sundial/node_modules/got
/Users/marvinheilemann/Development/VSCode/vscode-sundial/node_modules/public-ip
/Users/marvinheilemann/Development/VSCode/vscode-sundial/node_modules/suncalc
npm ERR! missing: @sindresorhus/is@^1.0.0, required by got@10.5.5
npm ERR! missing: @szmarczak/http-timer@^4.0.0, required by got@10.5.5
npm ERR! missing: @types/cacheable-request@^6.0.1, required by got@10.5.5
npm ERR! missing: cacheable-lookup@^2.0.0, required by got@10.5.5
npm ERR! missing: cacheable-request@^7.0.1, required by got@10.5.5
npm ERR! missing: decompress-response@^5.0.0, required by got@10.5.5
npm ERR! missing: duplexer3@^0.1.4, required by got@10.5.5
npm ERR! missing: get-stream@^5.0.0, required by got@10.5.5
npm ERR! missing: lowercase-keys@^2.0.0, required by got@10.5.5
npm ERR! missing: mimic-response@^2.0.0, required by got@10.5.5
npm ERR! missing: p-cancelable@^2.0.0, required by got@10.5.5
npm ERR! missing: p-event@^4.0.0, required by got@10.5.5
npm ERR! missing: responselike@^2.0.0, required by got@10.5.5
npm ERR! missing: to-readable-stream@^2.0.0, required by got@10.5.5
npm ERR! missing: type-fest@^0.9.0, required by got@10.5.5
npm ERR! missing: dns-socket@^4.2.0, required by public-ip@4.0.0
npm ERR! missing: got@^9.6.0, required by public-ip@4.0.0
npm ERR! missing: is-ip@^3.1.0, required by public-ip@4.0.0
```

**Comment by muuvmuuv** [comment]
Equivalent command would be: `pnpm list --prod --json` (`yarn` uses the same)

**Comment by muuvmuuv** [comment]
I guess this requires some rework of the npm.ts script. There is a package that checks which pm was used, maybe something to consider: https://github.com/zkochan/packages/tree/master/which-pm

**Comment by empathicqubit** [comment]
I've been looking at how to make this work. The main issue is that pnpm makes heavy use of symlinks which won't work with the vsix compression, which is just PKZIP.

**Comment by Jack-Works** [comment]
Having this problem too. I don't want to mix many package managers in a single project

**Comment by creepinson** [comment]
I just ended up using yarn for my vscode extension, while using pnpm for everything else. Hopefully this will be solved soon.

**Comment by lukeshiru** [comment]
`vsce` should be package manager agnostic. Having it using `npm` instead of using whatever the dev has is far from ideal. I had to use `npm` when I use `pnpm` for everything else:

```zsh
pnpm i
vsce publish # error

npm ci
vsce publish #works
```

This worked on previous versions of `vsce`, so the change mush be kinda recent.

**Comment by muuvmuuv** [comment]
Oh... I just forgot about my issue about that last year and switched to pnpm again with the same extension xD 

Can this get more attention please, since Node allows to have any pm to be the default: https://pnpm.io/installation#nodejs-is-preinstalled

I really don't want to use npm just for one project which would also mean I must remove my `alias npm=pnpm` line in zshrc :D

**Comment by softboy99** [comment]
+1

**Comment by idleberg** [comment]
> `vsce` should be package manager agnostic. Having it using `npm` instead of using whatever the dev has is far from idea

In the longterm it should probably use `corepack`, which was designed for this case:

> Corepack is a zero-runtime-dependency Node.js script that acts as a bridge between Node.js projects and the package managers they are intended to be used with during development. In practical terms, **Corepack will let you use Yarn and pnpm without having to install them** - just like what currently happens with npm, which is shipped by Node.js by default.
>
> via [nodejs/corepack](https://www.npmjs.com/package/corepack)

**Comment by F3n67u** [comment]
Below solution works for me:

1. bundle extension, see https://code.visualstudio.com/api/working-with-extensions/bundling-extension

```
// this is my package.json
"scripts": {
    "vscode:prepublish": "npm run esbuild-base -- --minify",
    "esbuild-base": "esbuild ./src/extension.ts --bundle --outfile=out/main.js --external:vscode --format=cjs --platform=node"
}
```

2. add `--no-dependencies` option to `vsce package` and `vsce publish` command(because you already bundled your extension, then there is no need to include npm dependencies when package and publish, all things is in your bundle)

```
// this is my package.json
"scripts": {
    "package": "pnpm vsce package --no-dependencies",
    "publish": "pnpm vsce publish --no-dependencies"
}
```

**Comment by johnsoncodehk** [comment]
@F3n67u done, thank you!

If someone need to reference:
- https://github.com/johnsoncodehk/volar/commit/d32311b296a2765d3d40a471e45023db7fb7a925
- https://github.com/johnsoncodehk/volar/commit/ab1fafcfc0033f62cdf5104f027d37b9a11d4a14

**Comment by mohanraj-r** [comment]
Thanks @F3n67u 
When `vsce package --no-dependencies` is specified, it doesn't include node_modules even without any .vscodeignore file. Is this expected? Is node_modules not required to be packages into the vsix when esbuild is used?

**Comment by F3n67u** [comment]
> Thanks @F3n67u
> When `vsce package --no-dependencies` is specified, it doesn't include node_modules even without any .vscodeignore file. Is this expected? Is node_modules not required to be packages into the vsix when esbuild is used?

@mohanraj-r yes. It's expected. when you bundle your extension then node_moudle is not needed.

**Comment by alexn-s** [comment]
just encountered the same issues with pnpm. really thought something huge like vscodee/ vsce cli supports all package managers.

**Comment by doctor-ew** [comment]
Same here -- is pnpm support on the product roadmap?

**Comment by shellscape** [comment]
Just under three years and this hasn't gotten any attention from Microsoft. This is the problem with a bigcorp owning the product.

**Comment by shellscape** [comment]
Note that the solution posted by @F3n67u will work in _many_ cases but not _all_. ESBuild has a notoriously difficult time with dynamic require, which packages like `prismajs` make use of.

**Comment by samueldcorbin** [comment]
It is crazy that this still doesn't work.

If you make a VSCode Extension using Microsoft's own suggested generator-code and set it to pnpm, vsce package just straight-up doesn't work.

Why is that even an option if this doesn't actually work?

**Comment by FelixWaweru** [comment]
They really need to fix this. Now I have to restructure my project to use npm instead :(

**Comment by danielbayley** [comment]
> Just under three years and this hasn't gotten any attention from Microsoft. This is the problem with a bigcorp owning the product.

Yes, and de facto forcing it on everyone, after buying out GitHub, and subsequently killing Atom—after promising not to 🤥 Ran into this latest hurdle, having to port over my dozen or so packages… 😠

**Comment by mai1015** [comment]
i wonder why they support it in code generator but not the package tool

**Comment by joaomoreno** [comment]
Closing this as out of scope. As part of our recurring maintenance milestone, we've decided to limit the amount of supported package managers to npm and yarn v1 only.

Note that there are [known workarounds](https://github.com/microsoft/vscode-vsce/issues/517#issuecomment-1724528163).

**Comment by maninak** [comment]
Here's a [better workaround](https://stackoverflow.com/a/76233583/5015955), accounting for runtime dependencies, that worked for me.

**Comment by hyperswine** [comment]
this is still an issue? Well I guess workarounds will have to do

**Comment by okay-head** [comment]
This is still and issue? Sucks that I'd have to stick to `npm` for vscode extensions

**Comment by shellscape** [comment]
@okay-head I switched to Zed a while back. vscode is run by corporate Microsoft managers, not the actual users.

**Comment by okay-head** [comment]
@shellscape Zed is only available for Mac

How about vscodium? Is it any good

**Comment by yg-i** [comment]
Isn't pnpm explicitly listed as one of the package manager options in the official vscode extension generator (yo code)? 

<img src="https://github.com/microsoft/vscode-vsce/assets/148152939/c2d6c9f9-3e78-4925-8647-2745aefc5021" width="300" />

I picked the pnpm option and haven't made any changes to any of the config files. I'm able to run and debug my extension with no problem but when I try to package it, I see this wall of errors:

<img src="https://github.com/microsoft/vscode-vsce/assets/148152939/4fb358bc-aad8-4769-9756-26b7ef26d886" width="50"/>

**Comment by iRonin** [comment]
Try this:

```
pnpm vsce publish --no-dependencies
```

**Comment by evisong** [comment]
> Try this:
> 
> ```
> pnpm vsce publish --no-dependencies
> ```

@iRonin You save my day, thanks!

My case was:

```
pnpm vsce package --no-dependencies
```

It works pretty well.

It would be great if VSCode to add the commands to the document.

**Comment by segevfiner** [comment]
This makes it package without node_modules though, so will only work when you bundle all your dependencies, and won''t work with dependencies that don't bundle well, such as ones containing native addon modules, WASM, or static asset folders.

**Comment by KTrain5169** [comment]
> `vsce` should be package manager agnostic. Having it using `npm` instead of using whatever the dev has is far from ideal.

this should be what happens. the official Yeoman generator offers pnpm as a pm option, so it would make sense to provide first-class support for it as well.

**Comment by trancexpress** [comment]
Are there any workarounds when `npm` is not installed at all?

```
Executing prepublish script 'npm run vscode:prepublish'...
/bin/sh: line 1: npm: command not found
```

Seems like removing the prepublish part in scripts avoids the error:

```
   "scripts": {
-    "vscode:prepublish"
```

Should be enough for my case...
