### ISSUE TITLE
Should upgrade lodash version to >=4.17.12 

### ISSUE THREAD

**Issue by yiyione** [microsoft/vscode-vsce#422]
When I run `yarn audit fix`, I got a vulnerability from vsce:
│ high                   │ Prototype Pollution 
│ Package             │ lodash 
│ Patched in         │ >=4.17.12 
│ Dependency of │ vsce         
│ Path                  │ vsce > lodash
│ More info          │ https://www.npmjs.com/advisories/1065

**Comment by joaomoreno** [comment]
Can you show me the full output of `yarn audit fix`? I'm getting different results.

**Comment by yiyione** [comment]
I'm sorry, I didn't run `yarn audit fix` under `vscode-vsce` project, looks like it doesn't have vulnerability here.
I run it in another project, has dependency of vsce:
`"devDependencies": { "vsce": "^1.73.0" }`
I got this:
![audit_fix](https://user-images.githubusercontent.com/17357108/74386829-f2144480-4e31-11ea-8c9d-063dbd78bde4.png)
