### ISSUE TITLE
Make version requirements consistent between package and publish

### ISSUE THREAD

**Issue by robertoaloi** [microsoft/vscode-vsce#425]
Hi! I tried to publish an extension with version `0.1.0-a`. The version was accepted by the `package` command, but not by the `publish`:

```
$ vsce publish
ERROR  The version string '0.1.0-a' doesn't conform to the requirements for a version. It must be one to four numbers in the range 0 to 2147483647, with each number seperated by a period. It must contain at least one non-zero number.
```

Fair enough, then I replaced the `-a` with `.0` (I need an extra value aside the semver and `0.1.0.0` should match the above expectations). This time is the `package` command which complains:

```
$ vsce package
ERROR  Invalid extension version '0.1.0.0'
```

If this is not supposed to be a valid version either, isn't the message returned by the `publish` command incorrect?

VSCE version: 1.73.0

**Comment by robertoaloi** [comment]
And now I notice that #415 is related. Also, there's a typo in the message itself:

seperated -> separated

**Comment by joaomoreno** [comment]
Yes, last month I had `publish` catch invalid versions, but there was a public outcry: https://github.com/microsoft/vscode-vsce/issues/415#issuecomment-581291512

So, closing it as designed.

**Comment by joaomoreno** [comment]
> If this is not supposed to be a valid version either, isn't the message returned by the publish command incorrect?

Indeed. Let's just rewrite the message we get from the Marketplace.
