### ISSUE TITLE
vsce package throwing error

### ISSUE THREAD

**Issue by kirankotari** [microsoft/vscode-vsce#429]
Couldn't detect the repository where this extension is published. The link 'MANIFEST.in' will be broken in README.md. Please provide the repository URL in package.json or use the --baseContentUrl and --baseImagesUrl options.

I am new to Visual Studio Code Extension. [Code @GitHub](https://github.com/kirankotari/PyPa)

**Comment by joaomoreno** [comment]
Can you show me your README.md?

**Comment by kirankotari** [comment]
[PyPa](https://github.com/kirankotari/PyPa) complete repo

**Comment by joaomoreno** [comment]
Those links you have in the top of README.md will be broken when you submit this to the Marketplace. Neither the Marketplace nor VS Code will be able to honor them. I suggest you remove them from the README.md.
