### ISSUE TITLE
Fix markdown-it security vulnerability

### ISSUE THREAD

**Issue by RedMickey** [microsoft/vscode-vsce#431]
Hello, I'm a member of the development team of VS Code extensions for debugging [Cordova](https://github.com/microsoft/vscode-cordova) and [React Native](https://github.com/microsoft/vscode-react-native) applications. A security vulnerabilities was revealed in **vscode-vsce** package dependencies. The package causing a security issue is [markdown-it](https://github.com/markdown-it/markdown-it). Detailed info about the vulnerability is available [here](https://ossum.microsoft.com/component/review?id=333). The vulnerability has been already [fixed](https://github.com/markdown-it/markdown-it/issues/583). It’s recommended to update this dependency.

**Comment by jamesgeorge007** [comment]
#437
