### ISSUE TITLE
Question: How is Azure DevOps PAT tied to vsce publisher?

### ISSUE THREAD

**Issue by MetRonnie** [microsoft/vscode-vsce#443]
My team is in the process of creating a VSCode extension.

I have generated a PAT on Azure DevOps as described in the [VSCode publishing extension guide](https://code.visualstudio.com/api/working-with-extensions/publishing-extension). This appears to be unique to my (enterprise) microsoft account. The next step is to create a publisher, and apparently
> `vsce` will remember the provided Personal Access Token for future references to this publisher

But what I can't understand is the connection between a publisher and the PAT. I've read on other issues that when the PAT expires a newly generated one can be added using `vsce login`, but who can do that? Is there a connection to my company microsoft account that is set in stone when I first create a publisher? What if another team member needs to publish a patch? What if I move to a different team in the company that has nothing to do with the extension?

**Comment by joaomoreno** [comment]
An account is authenticated with the PAT. An account can have access to multiple publishers and a publisher can be accessed by multiple accounts. You can use the following link to edit a publisher's membership: https://marketplace.visualstudio.com/manage
