### ISSUE TITLE
'vsce package' hangs when prepublish script asks for user input

### ISSUE THREAD

**Issue by rlipscombe** [microsoft/vscode-vsce#444]
I'm hacking on the https://github.com/elixir-lsp/vscode-elixir-ls extension, but when I run `vsce package`, it hangs:

```
$ vsce package
Executing prepublish script 'npm run vscode:prepublish'...
^C
```

After a while, I ran `npm run vscode:prepublish` directly, which asked me a question (I was missing some stuff after having recently deleted `~/.mix`).

After resolving that (answering 'Y' to the question), `vsce package` successfully ran to completion.

Could `vsce package` close stdin when invoking child processes, or something? That'd cause them to fail and then (hopefully) `vsce package` could display the output, which would give clues?

**Comment by joaomoreno** [comment]
What vsce version are you on?

**Comment by rlipscombe** [comment]
I literally only just ran `npm install -g vsce@latest`, so ... whatever that is.

**Comment by joaomoreno** [comment]
Could I perhaps reproduce that prompt locally? We just changed prepublish to inherit stdio, so everything should work without any issue.

**Comment by rlipscombe** [comment]
You don't get a prompt, though, because vsce swallows stdout. Which means that you don't know that you need to answer the prompt, even if stdio is inherited...

**Comment by rlipscombe** [comment]
But:

1. Clone https://github.com/elixir-lsp/vscode-elixir-ls
2. Make sure that you don't have a `~/.mix` directory.
3. Run `vsce package`. It appears to hang. Kill it with Ctrl+C.
4. Run `npm run vscode:prepublish`. It prompts about missing "Hex". Press Enter to answer yes to the question.
5. Run `vsce package`. It runs to completion.

You'll probably need Elixir installed. I've got 1.10.2.

**Comment by joaomoreno** [comment]
I first get an error:

```
cp: cannot stat 'elixir-ls/CHANGELOG.md': No such file or directory
```

Once I commented out that, it complains it doesn't know what `mix` is:

```
./prepublish.bash: line 8: mix: command not found
```

Where do you get `mix` from?

**Comment by rlipscombe** [comment]
You need to clone with `--recursive`, to pick up the submodules.
You get `mix` by having Elixir installed.

**Comment by joaomoreno** [comment]
I do get a prompt on vsce 1.75.0:

![image](https://user-images.githubusercontent.com/22350/80505629-dde1dd00-8974-11ea-88e8-2d64de5fff3b.png)

So... what shell/terminal are you using?

**Comment by rlipscombe** [comment]
Ubuntu 18.04, gnome-terminal, bash.

**Comment by joaomoreno** [comment]
Can you show me a screenshot of where it exactly hangs?

**Comment by joaomoreno** [comment]
Oh I guess you did.

What was the exact prompt you got when you ran the prepublish script directly?

**Comment by rlipscombe** [comment]
```
$ npm run vscode:prepublish

> elixir-ls@0.3.3 vscode:prepublish /home/roger/Source/elixir-lsp/vscode-elixir-ls
> ./prepublish.bash

==> elixir_ls_utils
Could not find Hex, which is needed to build dependency :jason
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] 
```

I pressed Enter.

```
* creating /home/roger/.mix/archives/hex-0.20.5
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  dialyxir 1.0.0
  docsh 0.7.2
  erlex 0.2.6
  forms 0.0.1
  getopt 1.0.1
  jason 1.1.2
  providers 1.8.1
warning: Building with Erlang/OTP 22. Make sure to build with OTP 20 if publishing the compiled packages because modules built with higher versions are not backwards-compatible.

Generated archive "/home/roger/Source/elixir-lsp/vscode-elixir-ls/elixir-ls-release/forms-0.0.1.ez" with MIX_ENV=dev
Generated archive "/home/roger/Source/elixir-lsp/vscode-elixir-ls/elixir-ls-release/erl2ex-0.0.10.ez" with MIX_ENV=dev
Generated archive "/home/roger/Source/elixir-lsp/vscode-elixir-ls/elixir-ls-release/erlex-0.2.6.ez" with MIX_ENV=dev
Generated archive "/home/roger/Source/elixir-lsp/vscode-elixir-ls/elixir-ls-release/jason-1.1.2.ez" with MIX_ENV=dev
Generated archive "/home/roger/Source/elixir-lsp/vscode-elixir-ls/elixir-ls-release/dialyxir-1.0.0.ez" with MIX_ENV=dev
Generated archive "/home/roger/Source/elixir-lsp/vscode-elixir-ls/elixir-ls-release/elixir_ls_utils-0.3.3.ez" with MIX_ENV=dev
Generated archive "/home/roger/Source/elixir-lsp/vscode-elixir-ls/elixir-ls-release/getopt-1.0.1.ez" with MIX_ENV=dev
Generated archive "/home/roger/Source/elixir-lsp/vscode-elixir-ls/elixir-ls-release/providers-1.8.1.ez" with MIX_ENV=dev
Generated archive "/home/roger/Source/elixir-lsp/vscode-elixir-ls/elixir-ls-release/docsh-0.7.2.ez" with MIX_ENV=dev
Generated archive "/home/roger/Source/elixir-lsp/vscode-elixir-ls/elixir-ls-release/elixir_sense-1.0.1.ez" with MIX_ENV=dev
Generated archive "/home/roger/Source/elixir-lsp/vscode-elixir-ls/elixir-ls-release/debugger-0.3.3.ez" with MIX_ENV=dev
Generated archive "/home/roger/Source/elixir-lsp/vscode-elixir-ls/elixir-ls-release/language_server-0.3.3.ez" with MIX_ENV=dev
```

**Comment by joaomoreno** [comment]
So... the same that I got. So strange that you don't see exactly what I see. `vsce --version` does return `1.75.0` right? Can you maybe try another terminal app? Not sure what you're using right now?

**Comment by rlipscombe** [comment]
```
$ vsce --version
1.75.0
```

GNOME Terminal 3.28.2, on Ubuntu 18.04.4 LTS.

**Comment by joaomoreno** [comment]
What Node version do you have?

**Comment by rlipscombe** [comment]
```
$ node
Welcome to Node.js v12.16.1.
```

**Comment by rlipscombe** [comment]
Incidentally, don't spend too long on trying to reproduce this, unless someone else reports it. I was building that extension to try to investigate some _other_ problem, and I've solved that other problem, so this is low on my list of concerns right now.

**Comment by joaomoreno** [comment]
Great, I'll close it and keep it in mind in case similar issues come along.
