### ISSUE TITLE
Problem with publisher

### ISSUE THREAD

**Issue by SrBrahma** [microsoft/vscode-vsce#445]
I created a new published but when I passed the token, I had another text on my clipboard (d'oh!). Now, it doesn't seem that I can remove it, as when I try to delete-publisher, it asks me for the inputted token, that I don't know what it was. How to remove it?

Also, as I entered a invalid token and it threw me an error 

```
({"$id":"1","innerException":null,"message":"TF400813: Resource not available for anonymous access. Client authentication required.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000})
```

, the publisher shouldn't be created.

**Comment by joaomoreno** [comment]
Try `vsce logout PUBLISHER_NAME`

**Comment by SrBrahma** [comment]
Yeah, I managed to fix it by doing the logout command that I found in the --help.

Shouldn't be the default behavior when deleting?

**Comment by joaomoreno** [comment]
I guess VSCE tries to delete it first and only then logout, just to be safe not to lose any credentials.

**Comment by Kinfe123** [comment]
I have the same issue in publishing extension using PAT but it doesnt even let me to logout with in the publisher name that are found the package.json file...Any One who has n opinion about this
