### ISSUE TITLE
Add support for new extension categories

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-vsce#459]
Re https://github.com/microsoft/vscode/issues/100399

New extension categories have been added in the marketplace and need to be added in various places for VS Code.

- Data Science
- Machine Learning
- Visualization
- Testing
- Notebooks

**Comment by joaomoreno** [comment]
@sandy081 As discussed with @egamma, VSCE doesn't know about categories. This needs to be filed against the Marketplace.
