### ISSUE TITLE
Add json minifier into the packager

### ISSUE THREAD

**Issue by DaanV2** [microsoft/vscode-vsce#463]
I have no idea if I should post this here.

But I would love to see an option that minify all JSON files.
I'm currently developing an extension that has 600+ JSON files all used for languages and JSON validation.
If they are condensed (no comments, whitespace, and newlines) its saves about 0.5 MB of data.

**Comment by joaomoreno** [comment]
VSCE is merely a packaging tool. For minification purposes, use something like https://www.npmjs.com/package/json-mangler
