### ISSUE TITLE
command not found after install but tree provider is working

### ISSUE THREAD

**Issue by deepakpahwa19** [microsoft/vscode-vsce#465]
Hi There,

I have developed an extension [MultiColor Bookmarks](https://marketplace.visualstudio.com/items?itemName=DeepakPahawa.flowbookmark)  but unable to use commands immediately after installing. It says command not found for all the commands. However, tree provider is displaying data but clicking on any bookmark is not taking to the exact location.

![image](https://user-images.githubusercontent.com/30567657/86534990-bf5f0b80-befa-11ea-9311-3db2d0cd8bfd.png)

PS:- After Reloading the window after installation makes the commands working.

Thanks in advance.

**Comment by alexr00** [comment]
@deepakpahwa19 can you point me to a repository where I can repro the issue?

**Comment by deepakpahwa19** [comment]
@alexr00 yes please, here is the repository having package.json and extension.ts. Please help.
[FlowBookmarks](https://github.com/deepakpahwa19/flow-bookmarks/tree/master/src)

**Comment by wicky4github** [comment]
#### Same problem on me, can somebody tell me how to solve this problem?

------------------------------------------

In debug mode: everything is ok.

Snapshots: 
[https://github.com/wicky4github/vscode-miniprogram-util/blob/master/debug1.png](url)
[https://github.com/wicky4github/vscode-miniprogram-util/blob/master/debug2.png](url)

------------------------------------------

After building vsix then installed: Tree view is working, but the commands are not available.

Snapshot: 
[https://github.com/wicky4github/vscode-miniprogram-util/blob/master/prod1.png](url)
