### ISSUE TITLE
README has a word misuse

### ISSUE THREAD

**Issue by Ivan-Kouznetsov** [microsoft/vscode-vsce#470]
> Warning: When using vsce as a library be sure to sanitize any user input used in API calls, as a security measurement.

Should be

> Warning: When using vsce as a library be sure to sanitize any user input used in API calls, as a security **measure**.

A measure is (among other definitions): " a step planned or taken as a means to an end. Ex: took strong measures against the rebels" https://www.merriam-webster.com/dictionary/measure 

Measurement on the other hand is: "the act or process of measuring" 
https://www.merriam-webster.com/dictionary/measurement

**Comment by gregvanl** [comment]
Thanks for pointing this out!
