### ISSUE TITLE
Support  analyze the extension bundle size

### ISSUE THREAD

**Issue by hustwcy** [microsoft/vscode-vsce#473]
I packaged my extension, but it's too big. I want to to find the abnormal proportion in my extension. It would be nice to have a tool like [webpack-bundle-analyzer](url) to analyze the size of my extension.

![image](https://user-images.githubusercontent.com/10253976/89105446-caeb1700-d453-11ea-83e3-c2d053807984.png)

**Comment by joaomoreno** [comment]
I believe that to be out of scope for VSCE. There are plenty of great tools out there: https://superuser.com/questions/300606/how-to-analyse-disk-usage-in-command-line-linux

**Comment by hustwcy** [comment]
@joaomoreno Maybe i expressed my opinion incorrectly. I want to know the consist of the bundled .vsix file, because sometimes we can't find the reason of .vsix file size so big. It's will be easy solve the problem if vsce cli tool can support the consist of the bundled .vsix file.

**Comment by joaomoreno** [comment]
A VSIX is a simple ZIP file: extract it and run a disk analysis tool over the extracted results.

**Comment by hustwcy** [comment]
> A VSIX is a simple ZIP file: extract it and run a disk analysis tool over the extracted results.

ok.  Thanks
