### ISSUE TITLE
The documentation on using vsce and webpack is confusing

### ISSUE THREAD

**Issue by Ptival** [microsoft/vscode-vsce#479]
`vsce` starts complaining when there are more than a hundred JS files, saying we should use `webpack` and a `.vscodeignore`.

My first try was to only allow the `dist` directory in `.vscodeignore`. However, this breaks my extension (it builds, but fails when loaded) as it cannot find either npm packages (like `vscode-languageclient`), or my server files (which it looks for in `server/out/server.js`... outside of `dist`).

Looking back in the `lsp-sample` setup, I see that it suggests letting a whole bunch of files from `client/node_modules`:

https://github.com/microsoft/vscode-extension-samples/blob/83261e3f32421da84513c5a76e8b6a08fff3c332/lsp-sample/.vscodeignore#L9-L14

The moment I do so, my extension works again, but `vsce` complains that there are more than 100 Javascript files.

What does this all mean?

- Isn't `webpack` supposed to pack everything together? Why are the `node_modules` directories still needed? Why is the `server/out` directory also still needed?

- If we are to indeed let all those vscode files inside the vsxi like the sample suggests, why is vsce complaining about them?

**Comment by joaomoreno** [comment]
> * Isn't `webpack` supposed to pack everything together? Why are the `node_modules` directories still needed? Why is the `server/out` directory also still needed?

Yeah it should. As I'm not a webpack expert, I suggest asking this question in StackOverflow or in the webpack repo.

> * If we are to indeed let all those vscode files inside the vsxi like the sample suggests, why is vsce complaining about them?

You should still strive to keep your extension small, for performance reasons.
