### ISSUE TITLE
Add command to install and uninstall extensions

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-vsce#48]
Similar to [`apm`](https://github.com/atom/apm)'s `install` and `uninstall` commands, it would be great to have an official way of installing and uninstalling extensions via the command line in a platform independent way.

This would enable a nicer way of maintaining a consistent development environment across multiple PCs/platforms without resorting to symlinking the extensions to cloud storage (see https://github.com/Microsoft/vscode/issues/679).

**Comment by joaomoreno** [comment]
This issue was moved to Microsoft/vscode#691
