### ISSUE TITLE
cb.apply is not a function

### ISSUE THREAD

**Issue by meilZhu** [microsoft/vscode-vsce#481]
Hello! At first, when I packaged the vscode plug-in, I reported an error as follows

Error: Command failed: npm list --production --parseable --depth=99999`
npm ERR! missing: lodash@, required by kissy-xtemplate@0.4.3

However, according to the feedback from GitHub, it was the NPM version problem. I said that NPM version 5.5.1 was needed. However, after the version was changed here, the following errors appeared again

report errors

ERROR  Command failed: npm list --production --parseable --depth=99999 --loglevel=error
npm ERR! cb.apply is not a function

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode-vsce/issues/439
