### ISSUE TITLE
Azure Devops repository doesn't work as content base url

### ISSUE THREAD

**Issue by sungle3737** [microsoft/vscode-vsce#486]
```json
    "repository": {
        "type": "git",
        "url": "https://seong-land@dev.azure.com/seong-land/vscode-addon/_git/terminal-intuiter"
    },
```
`https://dev.azure.com/seong-land/vscode-addon/_git/terminal-intuiter` do not work also

my package.json is like this
but vsce package or publish throw 
```
ERROR  Couldn't detect the repository where this extension is published. The image 'images/example.gif' will be broken in README.md. Please provide the repository URL in package.json or use the --baseContentUrl and --baseImagesUrl options.
```

my readme
```markdown
![example](images/example.gif)
```

Azure devops repository doesn't work properly

**Comment by joaomoreno** [comment]
That's because we don't know how to fetch static content from azure devops. This is why there are the `--baseContentUrl` and `--baseImagesUrl` options, so you can provide those URLs yourself.

**Comment by dggsax** [comment]
Would you be able to share/point to any guidance for how other groups using Azure DevOps have handled this problem? Is the solution that teams publish the README media to a publically available source and just set that as the `--baseContentUrl`, or is there a way to point the URL's to ADO where the images will render correctly (provided the user has access to the Azure DevOps instance of course).
