### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by YashTotale** [microsoft/vscode-vsce#488]
# Error: write EPIPE

I'm not sure what the problem is, but everytime I try to publish my extension, I get this error.

![Error](https://user-images.githubusercontent.com/30784592/93694339-5a5d8f80-fabf-11ea-88d4-7987b2c61fb0.png)

Is it something I might be doing?

**Version**
![Version](https://user-images.githubusercontent.com/30784592/93694378-d526aa80-fabf-11ea-9cd0-ba3ed82f2645.png)

**Comment by joaomoreno** [comment]
Does `vsce package` work?

**Comment by YashTotale** [comment]
Yes, `vsce package` works.

![vsce package](https://user-images.githubusercontent.com/30784592/94328732-aa2dd200-ff69-11ea-855e-ff4510481d99.png)

**Comment by YashTotale** [comment]
My extension is called **Terminal All In One** and the publishing was working fine until a couple days ago.

**Comment by joaomoreno** [comment]
What node version do you have instlaled?

**Comment by YashTotale** [comment]
![image](https://user-images.githubusercontent.com/30784592/94744061-3efb4b80-032d-11eb-9c03-f5f53aa63973.png)

**Comment by joaomoreno** [comment]
Can you perhaps see if you still have that issue with node v10?

**Comment by YashTotale** [comment]
![image](https://user-images.githubusercontent.com/30784592/94861578-9b717000-03ec-11eb-87fe-b9bf0c4d6aaf.png)

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by YashTotale** [comment]
No, the publishing was fine for a long time until this issue came up.

**Comment by joaomoreno** [comment]
Does this happen on other machines?

**Comment by YashTotale** [comment]
Yes, I tried it on a different mac and the same error occurred.

**Comment by YashTotale** [comment]
Could it be something with my code?

**Comment by joaomoreno** [comment]
@prashantvc Could we somehow trace this user's publish request and see what's going wrong?

**Comment by prashantvc** [comment]
This looks like nodejs issue. Let me see if I can reproduce it on my machine with source

But we will take look at the server logs, @mayankmaheshwari18 can you take a quick look at this please?

@YashTotale btw I am digging your terminal setup, could you share what plugins and theme you're using :D

**Comment by YashTotale** [comment]
Sure, I am using [iTerm 2](https://www.iterm2.com/) with [Oh My Zsh](https://ohmyz.sh/) and the [powerlevel10k theme](https://github.com/romkatv/powerlevel10k). My color scheme is [Gruvbox Dark](https://iterm2colorschemes.com/).

**Comment by YashTotale** [comment]
No idea how, but I tried to publish again today after regenerating my Personal Access Token and it worked.

![image](https://user-images.githubusercontent.com/30784592/96788231-fffa6c00-13a7-11eb-8e4b-4829cc540689.png)

**Comment by YashTotale** [comment]
Also, this is off-topic but is it possible for me to customize my [publisher page](https://marketplace.visualstudio.com/publishers/yasht)?

**Comment by joaomoreno** [comment]
cc @prashantvc for above
