### ISSUE TITLE
Repository shorthand

### ISSUE THREAD

**Issue by cbarrick** [microsoft/vscode-vsce#489]
With npm, `package.json` supports a shorthand for GitHub, GitLab, BitBucket, etc.

https://docs.npmjs.com/files/package.json#repository

However, vsce spits out a warning when one of these shorthands is used:

```shell
$ cat package.json | grep repository
    "repository": "github:foo/bar",

$ vsce package
 ERROR  Couldn't detect the repository where this extension is published. The link './LICENSE' will be broken in README.md. Please provide the repository URL in package.json or use the --baseContentUrl and --baseImagesUrl options.
```

It would be nice if vsce would support these shorthands.

**Comment by wangweixuan** [comment]
I suggest including the package [`hosted-git-info`](https://github.com/npm/hosted-git-info), which supports parsing those shorthands and is developed by npm.

**Comment by joaomoreno** [comment]
@wangweixuan Please close one of the PRs, pick your favorite.
