### ISSUE TITLE
getaddrinfo ENOTFOUND marketplace.visualstudio.com marketplace.visualstudio.com:443

### ISSUE THREAD

**Issue by areijngoudt** [Microsoft/vscode-vsce#49]
When trying to install the extension 'solidity 0.0.1' still this error (now with the url starting with matkerplace, not app.marketplace).

**Comment by joaomoreno** [comment]
Do you use a proxy?

**Comment by areijngoudt** [comment]
Yes. Do I need to configure that in Code?

**Comment by joaomoreno** [comment]
Yes you do, there is an `http.proxy` setting you can set. But this still won't work for installing extensions until the end of December. See Microsoft/vscode#69

**Comment by areijngoudt** [comment]
Is there a workaround for now?

**Comment by joaomoreno** [comment]
Unfortunately there isn't.
