### ISSUE TITLE
Support --changelog command

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode-vsce#490]
Sometimes I want to see what the changelog looks like, without publishing. Otherwise it could just be created on `package` as well as `publish`?

**Comment by joaomoreno** [comment]
What do you mean by changelog?

**Comment by Stanzilla** [comment]
I was under the impression that `vsce publish` puts all the recent commits into `changelog.md` if that is not the case, feel free to ignore .)

**Comment by joaomoreno** [comment]
Yeah it doesn't. There are pretty good tools out there for that, though, ie https://www.npmjs.com/package/semantic-release

**Comment by felipecrs** [comment]
We recently started to use `semantic-release` in `vscode-shellcheck`, in case you find it useful.

https://github.com/timonwong/vscode-shellcheck/pull/112
