### ISSUE TITLE
VSCE does not package node_modules since about October 2 (version 1.81.0)

### ISSUE THREAD

**Issue by mmmyddd** [microsoft/vscode-vsce#497]
- Create extension
- Run npm install to create node_modules directory
- Run vsce package in extension directory
- unzip .vsix file
- No node_modules

**Comment by mmmyddd** [comment]
I  use npm and not yarn, BTW.

**Comment by felipecrs** [comment]
Did you try with `--no-yarn`, so we can check if this issue is the same as #494?

**Comment by mmmyddd** [comment]
> Did you try with `--no-yarn`, so we can check if this issue is the same as #494?

Yes, --no-yarn helps, but pls correct this, for npm seems the default option in my point of view

Thank you.

**Comment by laike9m** [comment]
This is causing my extension to not function. There's no clear error message when building, which is even worse.

**Comment by Foxhoundn** [comment]
Why was this a sudden, silent change like this, from npm to yarn? Everything in our pipelines is failing because none of our images had `yarn` >.<

**Comment by felipecrs** [comment]
People, this is a bug being tracked on #494. This is not an intended change.

**Comment by felipecrs** [comment]
It should be fixed in newest version, 1.81.1.

**Comment by joaomoreno** [comment]
Dupe of #494

Sorry for the breakage yall! Fix is out there!
