### ISSUE TITLE
Support to open the extension's report pages

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-vsce#499]
The Marketplace is now providing  acquisition reports for an extension. This reports page is not easily to find and navigate to, unless you remember the marketplace URL `https://marketplace.visualstudio.com/manage/publishers/PUBLISHER/`. 

Discussed with @joaomoreno and the suggestion is to print out a notice for that Marketplace URL whenever an extension gets published.

//fyi @fiveisprime

**Comment by joaomoreno** [comment]
Here's how it looks:

```
$ npx vsce publish
Publishing joaomoreno.banana@0.13.1...
 INFO  Extension URL (might take a few minutes): https://marketplace.visualstudio.com/items?itemName=joaomoreno.banana
 INFO  Hub URL: https://marketplace.visualstudio.com/manage/publishers/joaomoreno/extensions/banana/hub
 DONE  Published joaomoreno.banana@0.13.1.
```
