### ISSUE TITLE
vsce image URL rewriting assumes default branch is master, breaks when default branch is main

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/vscode-vsce#504]
A lot of projects are renaming their master branch to main. This breaks images in the marketplace that are using relative image references, because vsce always rewrites them to `master`.

**Comment by joaomoreno** [comment]
Both `package` and `publish` commands support `--githubBranch` to override the branch name. We can maybe go one step further and mess around inside the publisher's `.git` folder and look for a `master` or `main` ref and come up with a better heuristic. But I'm not sure it's really necessary for now.
