### ISSUE TITLE
vsce package @types/vscode error

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode-vsce#506]
So from the [documentation](https://code.visualstudio.com/api/references/extension-manifest) it sounds like I should keep my `engines` version at a level where my extension works at a minimum, yet, vsce requires it to be at the same level as my installed version of `@types/vscode` which is a bit confusing. 

I don't think a lower version of types should block packaging either.

**Comment by joaomoreno** [comment]
Yeah that is confusing. Pinging @octref in case he's still around to argue why we decided to go ahead with that requirement for vsce.

**Comment by octref** [comment]
If your `@types/vscode` is newer than the engine, it's possible for you to use new API which aren't in the old versions of VS Code, so you should upgrade `engines` or downgrade `@types/vscode` to earliest possible version.

**Comment by Stanzilla** [comment]
So I guess the best way is to pin types at an older version unless I actually use a new feature that requires it?

**Comment by octref** [comment]
Exactly

**Comment by joaomoreno** [comment]
Thanks @octref !!
