### ISSUE TITLE
Can't publish package

### ISSUE THREAD

**Issue by Levminer** [microsoft/vscode-vsce#507]
Every time I log in and try `vsce publish` I get this error: `ERROR  Access Denied: <my account name> needs the following permission(s) on the resource  to perform this action: Allows for the creation of BuiltIn extensions.`

**Comment by joaomoreno** [comment]
Did you follow this guide? https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token

Pay attention to:

- All accessible organizations
- Custom defined, Marketplace: Acquire & Manage

**Comment by Levminer** [comment]
Yes

**Comment by joaomoreno** [comment]
cc @prashantvc: Can you provide more insights?

**Comment by prashantvc** [comment]
@Levminer Do you see your publisher name on https://marketplace.visualstudio.com/manage/ (left on the webpage)

**Comment by Levminer** [comment]
@prashantvc Yes.

**Comment by prashantvc** [comment]
@SaiKanth007 can you take a look at this issue, please?

**Comment by SaiKanth007** [comment]
@Levminer While generating the PAT token, can you select "All Accessible Organization" and "Full Access" (instead of custom access). Let us know if the you still get the same error ?

**Comment by Levminer** [comment]
@SaiKanth007 Yes.

**Comment by SaiKanth007** [comment]
@Levminer Can you please share the publisherName under which you are trying to publish this extension. Also can you please email us your VSID to vsmarketplace@microsoft.com

Steps to share VSID:
1.       Login to the Marketplace (https://marketplace.visualstudio.com ) with the required email address, which needs to have access to the publisher. 
2.       After getting logged in, from the same browser window, open https://marketplace.visualstudio.com/_apis/connectiondata 
3.       You should see some JSON data in the window.
4.       Copy paste the output of the page that you see. We are interested in the "id" field of the "authenticated" user.

**Comment by Levminer** [comment]
ID: `298dc9a4-106c-6b05-9f14-cf7e902f9c93`

**Comment by SaiKanth007** [comment]
@Levminer Please restrict from sharing VSID's on public github repositories. 

Also please share the publisherName under which you are publishing the package

**Comment by Levminer** [comment]
@SaiKanth007 I sent an email.

**Comment by Levminer** [comment]
In my package.json in the keywords section had a `#` and that's why it don't worked.

**Comment by vijval2010** [comment]
> In my package.json in the keywords section had a `#` and that's why it don't worked.

I had the same problem and I set a keyword to "#000000"

**Comment by eaccmk** [comment]
This is purely reproducible issue , in your VScode extensions `package.json` file add a keyword starting with hash `#` such as 

```
 "keywords": [
    "#VScodeBug",
    "#bug",
    "# bug",
    ],
```

I stumbled on this, can this 🐞  be fixed ?

**Comment by prashantvc** [comment]
@eaccmk perhaps you should file separate bug for it
