### ISSUE TITLE
Add Options for Publish without Packaging step

### ISSUE THREAD

**Issue by mitchdenny** [Microsoft/vscode-vsce#51]
I'd like to be able to separate out the package step and the publishing step. At the moment I can create a package without uploading it, but I can't upload a package without first building the package. I'd love to have a variation of the package command that is something like this:

```sh
vsce publish --vsix [path to vsix] --publisher [publisher name] --name [extension name]
```

**Comment by mitchdenny** [comment]
I was thinking about this some more. I think that all you really need is the path to the VSIX file, you can get all the metadata out of the package itself. So the command would look more like this:

vsce --vsix [path to vsix] --pat [personal access token]

Make sense?

**Comment by joaomoreno** [comment]
:+1: 

```
vsce publish [--pat PAT] ext-0.0.1.vsix
```

**Comment by mitchdenny** [comment]
Hi @joaomoreno - are you planning on changing this so that the command can run with just the *.vsix file present. At the moment you need all the other files, and it looks like it does a rebuild. Perhaps if I provide some more context it'll help explain what I am after.

I've got a VS code extension at https://github.com/mitchdenny/ecdc/. I'm currently building that extension using Visual Studio Team Services Build. That all works fine, but rather than publish directly from the build I would prefer store the artifact in VSTeam and then use a release management process to push the extension up to the gallery.

The thing is that storing the entire source tree just so I can do a ```vsce publish``` seems like overkill. The command you have specified above would be perfect if it only needed the *.vsix file to work.

I'm also thinking of building a VSTeam Agent Task which wraps ```vsce``` to make this process even easier in the future.

**Comment by joaomoreno** [comment]
Yes, what I meant by my previous comment was that I think this is a good idea! :+1:

**Comment by mitchdenny** [comment]
Haha! Awesome :)

**Comment by mitchdenny** [comment]
Hi @joaomoreno - is it possible that the 1.0.0 version of the vsce package is broken after this change went in? I'm having trouble getting Personal Access Tokens to work. I just generated a fresh token and got an error:

```sh
vsce login mitchdenny
```
```
Personal Access Token for publisher 'mitchdenny': ****************************************************

Error: Failed Request: Unauthorized(401) - 
```

**Comment by chrisdias** [comment]
assigning to @bpasero and reopening in case we have a regression.  @egamma fyi for triage.

**Comment by mitchdenny** [comment]
Sorry guys - you can close this down. I've got a case of the dumbs today. The token I was generating was specific to a VSTS account, not a global token.

**Comment by chrisdias** [comment]
no problem, glad you found the issue!
