### ISSUE TITLE
vsce package changes file permission

### ISSUE THREAD

**Issue by katauber** [microsoft/vscode-vsce#512]
I create a vsix file via `vsce package` using Windows and everything seems fine, but if a Unix user installs this vsix file there are problems with execution rights when using the extension.
I investigated the problem and found out that there files that lost their execution permisson after packed with vsce in Windows. This does not happen, when execute `vsce package` with Unix.
While in Windows it seems to be no problem, that the files lost the execution permission, in Unix the extension doesn't work.

Does anybody has an idea how to handle this?

**Comment by joaomoreno** [comment]
> I investigated the problem and found out that there files that lost their execution permisson after packed with vsce in Windows.

The files lost their permission the moment they existed in the Windows filesystem, which doesn't have that concept. If you're packaging an extension which depends on files having proper Unix file permissions, you need to build it in a Unix machine.
