### ISSUE TITLE
Keymap is different on windows, linux ,mac

### ISSUE THREAD

**Issue by Hypdncy** [microsoft/vscode-vsce#513]
Hello:
    I have a agent of windows ,a agent of linux, but I can not use the same keymap in those,  I think I will go  nuts,
    I hope a config in setting to configure the default keymap (windows or linux or mac)

Thank You !

**Comment by joaomoreno** [comment]
Is this a VS Code issue?

**Comment by Hypdncy** [comment]
I think this
