### ISSUE TITLE
Undo acidental unpublish

### ISSUE THREAD

**Issue by danielbolognani** [microsoft/vscode-vsce#518]
Hello,
Is it possible to undo an acidental unpublish command on our extension? One of our collaborators have unpublish it and now the extension is a brand new one (without history, etc...).
If it is possible, but this is not the place to ask, please point me out on how to achieve it.
Thanks!

**Comment by prashantvc** [comment]
@danielbolognani could you email vsmarketplace@microsoft.com?
please be sure to share more details about the extension

**Comment by danielbolognani** [comment]
I already did, waiting for a response. Thanks
