### ISSUE TITLE
New command: verify-pat

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-vsce#525]
Or something like that. Since apparently there is no public API in the VSCode Marketplace for that purpose, it would be handy to have a command which could verify if the PAT is actually usable.

I need this for validating the token as a verification step in the semantic-release-vsce plugin.

https://github.com/raix/semantic-release-vsce/blob/59e9fa4e0ed090388d4a475e7bbbc2d5bdc10df0/lib/verify.js#L17

**Comment by joaomoreno** [comment]
I like that. Wanna PR it?

We already have code which tests a PAT: https://github.com/microsoft/vscode-vsce/blob/3ef89858ecd86b59d5926503efc661bdfc7ee7df/src/store.ts#L59-L64

**Comment by felipecrs** [comment]
Amazing!

> Wanna PR it?


Yes, please!
