### ISSUE TITLE
package.json repository url not read

### ISSUE THREAD

**Issue by LuisPeregrinaIBM2** [microsoft/vscode-vsce#527]
When creating VSIX and using a relative image in the README.md it says:
 ERROR  Couldn't detect the repository where this extension is published. The image 'preview.png' will be broken in README.md. Please provide the repository URL in package.json or use the --baseContentUrl and --baseImagesUrl options.

However, there is a repo url in package.json:
```
{
	...
	"repository": {
		"type": "git",
		"url": "https://***.git"
	},
```

**Comment by joaomoreno** [comment]
Is it a github repo?

**Comment by LuisPeregrinaIBM2** [comment]
github enterprise, public repo

**Comment by LuisPeregrinaIBM2** [comment]
either way, parameter baseImagesUrl works, so either the message is missing some additional info (github.com repos only) or it's not parsed correctly.
