### ISSUE TITLE
Support reading PAT from environment variable

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-vsce#528]
This would enable more seamless integration in CI, preventing us from having to expose the PAT in the command line.

Such as `VSCE_TOKEN`:

```sh-session
$ export VSCE_TOKEN=123
$ vsce publish # no need for --pat
```

**Comment by joaomoreno** [comment]
That was already added a few months ago: https://github.com/microsoft/vscode-vsce/commit/07ea89230270a9a1e3e8350d57227943d5939865

Let me know if it doesn't work.
