### ISSUE TITLE
README.md is not picked up by vsce

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-vsce#53]
> Hi There,

> I have published my snippet extension over marketplace. I have put all details in package.json.
 
> But in extension home page, it doesn't show any description about tool.
 
> `https://marketplace.visualstudio.com/items/UVBrain.Angular2`
 
> If you go to my extension above, it mention as
"No overview has been entered by publisher"
 
> I do have readme.md file in my github
 
> `https://github.com/ultrasonicsoft/vscode-ng2-typescript-snippets`

> Could you please let me know how can I provide description in overview section?
 
> Thanks!

**Comment by joaomoreno** [comment]
Cannot reproduce. I cloned the repo, changed the publisher to my publisher and published. Here are the results:

![image](https://cloud.githubusercontent.com/assets/22350/11848112/af5e8fb4-a418-11e5-8993-0dfa5e167548.png)

**Comment by ultrasonicsoft** [comment]
Strange, it's still not working for me.

I updated my version info to 0.2.2 and ran below commands
1. vsce package
2. vsce publish

This is the folder from where I am running those commands:

![image](https://cloud.githubusercontent.com/assets/4145169/11848984/7707f870-a44b-11e5-8b3a-a3f9d34bf6ed.png)


Here is the output:

![image](https://cloud.githubusercontent.com/assets/4145169/11848963/6b8ccd4a-a44b-11e5-8577-a3783bf7eef6.png)

**Comment by ultrasonicsoft** [comment]
I hadn't put readme.md file in my publishing folder. I thought it will be read from Git.

Thanks joaomoreno!!

**Comment by pagebrooks** [comment]
For future reference, I ran into this issue and it was because I had *.md in my .vscodeignore file. Just wanted to mention this if anyone else has the same problem.
