### ISSUE TITLE
Cannot overwrite the access token

### ISSUE THREAD

**Issue by mrakgr** [microsoft/vscode-vsce#530]
```
PS C:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin> vsce login mrakgr
Publisher 'mrakgr' is already known
Do you want to overwrite its PAT? [y/N] y
Personal Access Token for publisher 'mrakgr': ****************************************************

 ERROR  Failed request: (401)
```

Trying to do a `vsce publish patch -p <token>` also fails with a 401 error. The situation on my PC is a bit unusual because a few days ago, I was on a cleaning spree and deleted the `AppData` folder by hand in order to free up space on the SSD. This broke some apps, and I suspect `vsce` is one of them. Right now my only choice for publishing on the VS Code marketplace is the web interface.

Can I do anything to fix this apart from reinstalling Windows?

**Comment by joaomoreno** [comment]
You need to request a new access token: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token

**Comment by mrakgr** [comment]
No wait, I definitely did that. I created a fresh one with full access...but neglected to set `Organization` to `All Accessible Organizations`. ...And now it works.

Sorry about that.
