### ISSUE TITLE
Try to detect default GitHub branch

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-vsce#534]
More and more people are changing their default branch from `master` to `main`. It would be great if VSCE could detect this and do right right thing when publishing an extension instead of assuming `master`.

**Comment by felipecrs** [comment]
My suggestion is:

```sh-session
$ git symbolic-ref refs/remotes/origin/HEAD
refs/remotes/origin/master
```

**Comment by estruyf** [comment]
Another option is to use `vsce publish --baseImagesUrl <URL to your repo>`. This is how I fixed it. 

IMO, it would be nice if this could be a setting in the `package.json` file. Like:

```json
vsce: {
  "defaultBranch": "main"
}
```
