### ISSUE TITLE
`vsce package` asks for Publisher error

### ISSUE THREAD

**Issue by exhesham** [microsoft/vscode-vsce#539]
Hi,

I want to pack my first extension using your guide: [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension).

The bug is when I run the command `vsce package`, I get error for missing publisher name. Why packaging an extension requires publishing details? Sounds to me like a bad design. Here is the error:

> ERROR  Invalid publisher name 'xxxxx'. Expected the identifier of a publisher, not its human-friendly name.  Learn more: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions

How can I use extension from exported file without publishing it outside?

**Comment by joaomoreno** [comment]
You simply need a publisher ID in `package.json`. The publisher ID doesn't need to be registered in the Marketplace, you can use a dummy string like `exhesham`.
