### ISSUE TITLE
NPM modules are not publishing

### ISSUE THREAD

**Issue by shanalikhan1** [Microsoft/vscode-vsce#54]
Hi , 
I created an extension for VS code. I published and downloaded it and found out that the NPM modules i used are not published. How to publish those modules online.

**Comment by joaomoreno** [comment]
Run `vsce list` to see which files will be published.

Make sure you

1. Run `npm install` to get those dependencies in disk before publishing, and
2. Do not list them in your `.vscodeignore`.

**Comment by shanalikhan1** [comment]
Following are the modules im using in extension.
 "devDependencies": {
    "fs": "^0.0.2",
    "github": "^0.2.4",
    "node-github": "0.0.3",
    "open": "^0.0.5",
    "typescript": "^1.6.2",
    "vscode": "0.10.x"
  },
  "dependencies": {
    "fs": "^0.0.2",
    "github": "^0.2.4",
    "node-github": "0.0.3",
    "open": "^0.0.5",
    "typescript": "^1.6.2",
    "vscode": "0.10.x"
  }


this is my vscodeignore file
.vscode/**
typings/**
out/test/**
test/**
src/**
**/*.map
.gitignore
tsconfig.json
vsc-extension-quickstart.md


I still dont see my npm modules listing in vsce list
how to add those modules in publishing.

**Comment by joaomoreno** [comment]
I'm assuming you ran `npm install`. Are your sources open? Could I take a look at them, so I can try out the same?

**Comment by shanalikhan1** [comment]
Yes i ran npm install.
It works on my machine when i publish and download from there i dont see any npm modules there

https://marketplace.visualstudio.com/items/Shan.code-settings-sync
Repo : https://github.com/shanalikhan1/code-settings-sync

**Comment by shanalikhan1** [comment]
its working now. one thing. i developed on windows and installed modules on windows , will vsce auto compile it for mac and linux ?

**Comment by joaomoreno** [comment]
How did it start working?

No, Code doesn't support extensions with native node module dependencies yet. See Microsoft/vscode#658 for more details.
