### ISSUE TITLE
Use semantic-release

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-vsce#541]
Hi,

The [`semantic-release`](https://github.com/semantic-release/semantic-release) helps a lot to generate new releases, changelogs, and keep versioning right. This implies using [Conventional Commits](https://www.conventionalcommits.org/).

If you agree, I can send a PR.

**Comment by joaomoreno** [comment]
I'd be curious to see what tooling we could get here. 👌

**Comment by joaomoreno** [comment]
@felipecrs Hey this is pretty cool, thanks for pushing us to do it.
