### ISSUE TITLE
Allow configuration through config file or a vsce key under package.json

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-vsce#548]
Currently, the configuration can be done through CLI options, such as `--yarn` and `--github-branch`. It would be very good if configurations could be done through the `package.json`, as is for `npm publish` itself. Something like:

```json
{
  "name": "vscode-shellcheck",
  [...]
  "vsce": {
    "yarn": true,
    "githubBranch": "main"
  }
}
```

This would be especially useful in [`semantic-release-vsce`](https://github.com/felipecrs/semantic-release-vsce), as it currently does not allow the user to set extra arguments for the `vsce` call.

https://github.com/felipecrs/semantic-release-vsce/issues/115

**Comment by jedwards1211** [comment]
I need a way to pass `--insiders` when publishing via `semantic-release-vsce`
