### ISSUE TITLE
Warn about README in vscodeignore

### ISSUE THREAD

**Issue by prashantvc** [microsoft/vscode-vsce#550]
Issue Type: <b>Bug</b>

I currently have a color theme I am working on but the overview doesn't link to the repo's README. The docs say it should automatically be picked up from the provided repo in `package.json` under the master branch. Am I missing something?

Extension page: [blackbird](https://links.mattglei.ch/aotSW)
Repo: [Matt-Gleich/blackbird](https://links.mattglei.ch/Z_LMr)

VS Code version: Code - Insiders 1.55.0-insider (6ebe2a14f3722bc2582ecd8108d0a71dfdd46036, 2021-03-25T16:23:16.288Z)
OS version: Darwin x64 20.3.0

Moved from https://github.com/microsoft/vsmarketplace/issues/40

Reporter: @Matt-Gleich

**Comment by felipecrs** [comment]
Or better yet, add `!README.md` to the list of default ignores.
