### ISSUE TITLE
VSCE Claims version is 1.86.0 when installed version is 1.87.1

### ISSUE THREAD

**Issue by mikecentola** [microsoft/vscode-vsce#560]
![image](https://user-images.githubusercontent.com/12663057/115423512-e3f74c00-a1cb-11eb-9602-000bd0563614.png)

I've uninstalled and reinstalled vsce. Everything works fine but it complains every time that I don't have the latest version.

**Comment by joaomoreno** [comment]
I'm not sure what `npm show` does. Can you show me the docs for that npm command?

**Comment by mikecentola** [comment]
@joaomoreno `npm show`, `npm view`, `npm info` and `npm v` all do the same thing.

Also `npm outdated` doesn't show anything outdated even though vsce claims it's old.

**Comment by joaomoreno** [comment]
`vsce -V` shows you your installed version

`npm show vsce version` shows you the latest available version on npm

**Comment by mikecentola** [comment]
I understand that but does this make any sense? `vsce` still thinks it is version 1.86.0 but npm shows I have 1.87.1 installed and no update.

![image](https://user-images.githubusercontent.com/12663057/116270392-0b5e9380-a74d-11eb-8622-d7dbc168bc2a.png)

**Comment by mikecentola** [comment]
Just an update for anyone that comes across this. Turns out somehow older versions persisted in `C:\Program Files\nodejs\`

Removing those allowed the correct ones from AppData to be run.
