### ISSUE TITLE
npm ERR! peer dep missing: diagnostic-channel@*, required by diagnostic-channel-publishers@0.4.4

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode-vsce#562]
I cant package using npm. After switching to yarn everything worked.
![image](https://user-images.githubusercontent.com/55927613/115989210-3b732e80-a5b5-11eb-8021-ee14e8ebcdbd.png)

**Comment by AllanOricil** [comment]
I had to switch to yarn: `vsce package --yarn`

**Comment by joaomoreno** [comment]
Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by AllanOricil** [comment]
@joaomoreno Im reporting a bug. I don't know why you thought I was asking something. The bug is that just by switching from npm to yarn, vsce package command works.

**Comment by joaomoreno** [comment]
Oh got it. Since https://github.com/microsoft/vscode-vsce/pull/492 vsce will detect `yarn.lock` and use `--yarn` automatically. Didn't that work for you?

**Comment by AllanOricil** [comment]
@joaomoreno oh I was using npm, and that is probably the reason I had to force with --yarn. I will switch everything to yarn and try again. Thanks
