### ISSUE TITLE
ERROR, Invalid regular expression: /(?<domain>github(\.com\/|:))(?<project>(?:[^/]+)\/(?:[^/]+))(\/|$)/: Invalid group

### ISSUE THREAD

**Issue by TKapitan** [microsoft/vscode-vsce#569]
Hello,
I want to create an update of my VS Code Extension; however, I still get an error below

`
PS C:\Users\Kepty\ALRM-VSCode> vsce package
INFO  Detected presence of yarn.lock. Using 'yarn' instead of 'npm' (to override this pass '--no-yarn' on the command line).
Executing prepublish script 'yarn run vscode:prepublish'...
yarn run v1.22.10
warning package.json: No license field
$ yarn run compile
warning package.json: No license field
$ tsc -p ./
Done in 4.37s.
 ERROR  Invalid regular expression: /(?<domain>github(\.com\/|:))(?<project>(?:[^/]+)\/(?:[^/]+))(\/|$)/: Invalid group
`

I did the previous version a week ago without any problem. The source codes of my app are here: https://github.com/TKapitan/ALRM-VSCode

**Comment by joaomoreno** [comment]
What's your Node.JS version?

**Comment by ooeygui** [comment]
The VSCode ROS node hit this during CI as well:
https://github.com/ms-iot/vscode-ros/runs/2548420883?check_suite_focus=true

Our github workflow has been configured to use Node 8 for the dev tooling. I'm adjusting to 14 which is what runs locally.

**Comment by joaomoreno** [comment]
Yeah, latest vsce requires node >= 10
