### ISSUE TITLE
How to make pre compile binaries for dependent modules

### ISSUE THREAD

**Issue by shanalikhan1** [Microsoft/vscode-vsce#57]
These are my dependencies in my extension.
"dependencies": {
"fs": "^0.0.2",
"github": "^0.2.4",
"node-github": "0.0.3",
"open": "^0.0.5"
}
Im using npm install and it works in windows. 
I read that in order to make it work in linux or mac i have to use pre compile binaries of these packages in my extension. Right ?
How to make pre compile binaries. Please tell a easy way in order to create binaries for these modules and include in code extension.

**Comment by joaomoreno** [comment]
As I told you in #54, native extensions are not yet supported. A few workarounds are discussed in Microsoft/vscode#658.
