### ISSUE TITLE
Cannot add new member to extension publisher

### ISSUE THREAD

**Issue by lhl2617** [microsoft/vscode-vsce#573]
I am following the steps in this comment: 
https://github.com/microsoft/vscode/issues/21478#issuecomment-284889034

And I'm getting this error (TF14045) when trying to add another user:

![image](https://user-images.githubusercontent.com/33488131/118398921-92b76c80-b652-11eb-8bf4-7a65ea1d9745.png)

FWIW, I'm currently developing extension under a university org account, and will be leaving the university and would like it transferred. It seems like adding a personal account is the easier option (other than explicitly deprecating the extension and starting from a clean slate). I suspect that people outside the org cannot be reached and hence the error.

**Comment by lhl2617** [comment]
I was able to add another user in the same org (university).

It's been four years since extension transferral was requested--any updates on a better flow?

**Comment by joaomoreno** [comment]
Can you please file an issue in https://github.com/microsoft/vsmarketplace instead? Thanks!

**Comment by lhl2617** [comment]
Sure :)

**Comment by lhl2617** [comment]
@joaomoreno I'm getting no ACK on this critical issue. Reopening.

**Comment by joaomoreno** [comment]
Sometimes there's no ACK. Please do not reopen this, since it's an issue with the Marketplace, not VS Code.
