### ISSUE TITLE
Login is case insensitive but publish is case sensitive depending on the package.json publisher

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-vsce#578]
I just published an extension with v1.88.0 so this may be fixed already. `vsce login tyriar` succeeds, but since I set the publisher to `Tyriar` in the extension's package.json it failed with this error:

```
 ERROR  {"$id":"1","customProperties":{"Descriptor":null,"IdentityDisplayName":null,"Token":null,"RequestedPermissions":0,"NamespaceId":"00000000-0000-0000-0000-000000000000"},"inne
rException":null,"message":"Access Denied: The Personal Access Token used has expired.","typeName":"Microsoft.VisualStudio.Services.Security.AccessCheckException, Microsoft.VisualStudio.Services.WebApi","typeKey":"AccessCheckException","errorCode":0,"eventId":3000}
```

I needed to do this to get it to publish:

```
vsce logout tyriar
vsce login Tyriar
# ...
vsce publish
```

SO answer that helped me: https://stackoverflow.com/a/60004943/1156119

**Comment by joaomoreno** [comment]
Should this go to the Marketplace issue tracker, since the login should have failed? https://github.com/microsoft/vsmarketplace

**Comment by Tyriar** [comment]
Yeah I guess it is a server issue, I'd prefer both to work though.
