### ISSUE TITLE
icon location broken in 1.92.0 and later

### ISSUE THREAD

**Issue by orph** [microsoft/vscode-vsce#584]
I get this error in 1.92.0 and above, and not in 1.91.0:
```
ERROR  The specified icon 'extension/assets/foo.png' wasn't found in the extension.
```

In the package.json I have:
```
"icon": "assets/foo.png",
```

**Comment by joaomoreno** [comment]
Where does the error come up? On startup? Which extension is this? Can you share the source code?

**Comment by orph** [comment]
This happens at the end of `vsce package`.

Sorry, I can’t share the extension’s source.

**Comment by GordonSmith** [comment]
FYI I have the same issue:

In my package.json I have:
```
"icon": "images/ObservableJS.png",
```

And when running `vsce package` I get:
```
ERROR:  The specified icon 'extension/images/ObservableJS.png' wasn't found in the extension.
```

**Comment by joaomoreno** [comment]
Very likely due to https://github.com/microsoft/vscode-vsce/issues/576

@orph @GordonSmith Can you share the repos of your extensions?

**Comment by GordonSmith** [comment]
https://github.com/GordonSmith/vscode-ojs - you will need to bump the version of vsce in the package.json.

**Comment by joaomoreno** [comment]
@GordonSmith: https://github.com/GordonSmith/vscode-ojs/pull/25

**Comment by GordonSmith** [comment]
@joaomoreno - are the rules different for .gitignore and .vscodeignore?

**Comment by joaomoreno** [comment]
That's exactly what has changed. VSCE used to have a custom engine for .vscodeignore. The latest release has adopted exactly the same logic as .gitignore. Your current rules would also fail in .gitignore.

**Comment by GordonSmith** [comment]
Thanks - have fixed my .vscodeignore file and all is good.
