### ISSUE TITLE
VSCE not honoring .vscodeignore exclusions correctly

### ISSUE THREAD

**Issue by PeterWone** [microsoft/vscode-vsce#587]
Does this issue occur when all extensions are disabled?: Yes/No
Yes but this is irrelevant it's a CLI tool problem.

Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Update VSCE from 1.88 to 1.94 and publish to the marketplace
2. Get zillions of bug reports from annoyed users due to missing assets
3. Revert VSCE to 1.88, bump extension version and republish to cheers from relieved users

The problem was caused by the last line `!node_modules/highlight.js/styles` not being honoured.

## .vscodeignore

```
# folders
.vscode/**
.vscode-test/**
src
out
node_modules
**/tsconfig.json
**/tslint.json
**/*.map
**/*.ts
*.vsix

# Specific files
.gitignore
webpack.config.js
CONTRIBUTING.md
package-lock.json

# Special exclusions
images
!images/icon.png
vsc-extension-quickstart.md
!node_modules/highlight.js/styles
```

**Comment by joaomoreno** [comment]
@PeterWone Sorry for the breakage. I'm pretty sure this would fix it:

```
# folders
.vscode/**
.vscode-test/**
src
out
**/tsconfig.json
**/tslint.json
**/*.map
**/*.ts
*.vsix

# Specific files
.gitignore
webpack.config.js
CONTRIBUTING.md
package-lock.json

# Special exclusions
images
!images/icon.png
vsc-extension-quickstart.md

# node_modules
node_modules/*
!node_modules/highlight.js
node_modules/highlight.js/*
!node_modules/highlight.js/styles
```

Let me know otherwise.

**Comment by Timmmm** [comment]
It would be helpful if you had a changelog!

**Comment by PeterWone** [comment]
@joaomoreno it wasn't the change that freaked me out, it was learning about it from new users of my product. But I daresay you've had quite a bit of negative feedback from upset users of your own efforts. This is why I tried to be funny rather than outraged when reporting it.

While updating it wouldn't have been a big thing now that I know what's going on, patching the file for me is very kind and a nice gesture considering how busy you must be. Thank you.

**Comment by PeterWone** [comment]
@Timmmm they probably _do_ have a change log. The trouble is, most people publish, see the update suggestion and type `npm i -g vsce` to stay on top of security issues and stay current in case Microsoft fiddles with authentication at the other end.

@joaomoreno what I suggest is write BREAKING CHANGE in breaking change items in your changelog, and have the update prompt display those items when it suggests an update.

**Comment by joaomoreno** [comment]
> @joaomoreno it wasn't the change that freaked me out, it was learning about it from new users of my product. But I daresay you've had quite a bit of negative feedback from upset users of your own efforts. This is why I tried to be funny rather than outraged when reporting it.
> 
> While updating it wouldn't have been a big thing now that I know what's going on, patching the file for me is very kind and a nice gesture considering how busy you must be. Thank you.

Totally, we did not expect changing the ignore module would cause such dramatic breakage. Then again, it was the right thing to do. In retrospect we should've bumped the major version signifying the breakage... but by now I believe we're in the tail end of these changes, hopefully.

**Comment by joaomoreno** [comment]
@PeterWone We've decided to revert the change: https://github.com/microsoft/vscode-vsce/issues/588

I took a look at your repo and found you have done no adoption at all. Just FYI: you don't need to to anything if you use the latest 1.95.0 version, which reverts the behavior.

**Comment by PeterWone** [comment]
I have actually but it's not in the public repo yet. It won't show up till I push the next update.
