### ISSUE TITLE
Additional Command Line Options

### ISSUE THREAD

**Issue by gep13** [Microsoft/vscode-vsce#59]
I am in the process of creating an Addin for [Cake](http://cakebuild.net/) to allow easily executing the various tasks that are exposed by vsce.  That way, I can include things like packaging and publishing into my Cake Build Script for my extensions.  You can find the current work here:

https://github.com/gep13/Cake.VsCode

I am limited in what I can do due to the fact that vsce doesn't allow me to pass in the various parameters as switches to the commands.  Instead, it prompts for input from the user.  i.e. when doing `vsce login gep13` I would like to be able to pass the PAT as another parameter.  Or, I would like vsce to look for a pre-defined environment variable that contains the PAT.

Is this something that can be added to this utility?

Thanks!

**Comment by joaomoreno** [comment]
This is supported:

```
$ vsce publish --help

  Usage: publish [options] [package]

  Publishes an extension

  Options:

    -h, --help         output usage information
    -p, --pat <token>  Personal Access Token
```

**Comment by gep13** [comment]
Ah perfect, I hadn't seen that.

I was looking at this only:

![image](https://cloud.githubusercontent.com/assets/1271146/12139106/d4298036-b455-11e5-9320-87f97b483e4a.png)

This is exactly what I need, thank you! :+1:
