### ISSUE TITLE
vsce package skips .gitignore files

### ISSUE THREAD

**Issue by marianan** [microsoft/vscode-vsce#590]
repro steps:
1. git clone https://github.com/microsoft/vscode-azure-iot-edge.git
2. cd vscode-azure-iot-edge
3. vsce package 

actual result - vsix from step 3 is missing assets\solution\.gitignore causing user issue https://github.com/microsoft/vscode-azure-iot-edge/issues/583

expected result - vsix includes all .gitignore files

**Comment by joaomoreno** [comment]
With what version of `vsce` did you test this?

**Comment by marianan** [comment]
The pipeline (Linux Xenial) installed vsce using 'npm install -g vsce' which brought 1.95.1 but when I test locally on Windows using this same version the issue is no repro. I suspect that this may be related to some pipeline cache and not really the tool itself. I am unable to identify the cached version just yet. Since the latest version does not repro this behavior locally i am closing this issue and will continue investigating the caching hypothesis.
