### ISSUE TITLE
Add command line flag to not update source package.json version

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-vsce#596]
I do my builds in CI so my source package.json version is always "0.0.0-source". However when running vsce package locally for testing it updates the version, and I occassionally accidentally commit this version because of it. Provide a command line parameter similar to `--no-git-tag-version` e.g. `--no-packagejson-version`

## Workarounds
1. Local selective gitignore on the package.json, not great
2. Only do builds in CI and don't push git changes

**Comment by joaomoreno** [comment]
`vsce package` should not update the version automatically. Do you find that it does? Can you show me? Do you have steps?

**Comment by JustinGrote** [comment]
@joaomoreno to be clear this is when specifying a version at the command line, e.g. `vsce package --no-git-tag-version v1.2.3`
![image](https://user-images.githubusercontent.com/15258962/131524003-f422a06c-4f89-474d-86f0-35c705825933.png)
![image](https://user-images.githubusercontent.com/15258962/131524051-11331192-7094-408f-b685-5c336da147d0.png)

**Comment by zimmski** [comment]
Can confirm that this is with the version added to "package". Just had the same problem.

**Comment by joaomoreno** [comment]
Will add `--no-update-package-json`.

**Comment by JustinGrote** [comment]
@joaomoreno thank you!
