### ISSUE TITLE
Cannot create private extension

### ISSUE THREAD

**Issue by DennisValente** [microsoft/vscode-vsce#597]
Please allow the packaging process to respect the `private` setting of the manifest in the package.json file.

Both `vsce package` and `vsce publish` (which reruns the package command) do not take direction from the private setting, i.e. `"private": true`, in the package.json file. They will always create a public extension, as evidenced by the `<GalleryFlags>Publish<GalleryFlags>` node in the resulting "extension.vsixmanifest" file within the VSIX file.

Unless I'm missing something, this might be accomplished by changing some code in the ManifestProcessor class of the /src/package.ts file.

FROM (Line 299):

```typescript
const flags = ['Public'];
```

TO: 

```typescript
const flags = [];

if (manifest.private) {
  flags.push('Private');
} else {
  flags.push('Public');
}
```

**Comment by joaomoreno** [comment]
microsoft/vsmarketplace#167

**Comment by GitMensch** [comment]
@joaomoreno The upstream issue was closed, but it seems private extensions are not available now, nor directly related to the referenced issue (which is about a private marketplace). I suggest to reopen this one.

**Comment by joaomoreno** [comment]
@GitMensch The discussion was moved here: https://github.com/microsoft/vsmarketplace/discussions/211

**Comment by GitMensch** [comment]
Thank you for the note back, but that's an discussion where people previously reported (a bunch of different) issues.

In this specific issue here @DennisValente reported vsce to not honor the private setting along with the actual fix that can be applied to vsce (this even does not directly relate to the marketplace at all, that comes "afterwards").
