### ISSUE TITLE
Unpackaging from .VSIX

### ISSUE THREAD

**Issue by Password-Classified** [microsoft/vscode-vsce#601]
I was creating an extension, but all of a sudden, everything was deleted besides the .vsix file! Is there anyway to "unpackage" the file tree from the .VSIX?

**Comment by Password-Classified** [comment]
Just tried to restore it, but had the same issue again! Every time I use `vsce package`, it deletes my folder. It didn't do this until the most recent update.

**Comment by joaomoreno** [comment]
What is the repository for your sources? Can I see it? Can I reproduce it?

**Comment by Password-Classified** [comment]
https://github.com/Password-Classified/Language-Runner is the repository.

Once I packaged it, and  installed it into vscode, the  folder  vanished.

**Comment by Password-Classified** [comment]
It might be helpful to note that the folder was in the `.vscode/extensions` folder.

**Comment by joaomoreno** [comment]
What other extensions do you have installed?

**Comment by Password-Classified** [comment]
Quite a lot...

AREPL for python
Auto rename tag
better comments
browser preview
C/C++
Colour Highlight
Docs View
Draw.io Integration
EV3DEV Browser
Excel Viewer
EXE Runner
filesize
generate  data
gist pad
Git graph
git history
github theme
gitignore
gitlens
gruvbox theme
IKKI VSCode dark + light themes
Image Resizer
Jupyter Pack
EV3 Micropython
Live Preview
Live Share
Luna Paint
Markdown table prettifier
material icon theme
path intellisense
Prettier
Project manager
Pylance
Python
Python Indent
Sourcery
SQL Tools + SQL Tools  SQLite
SVG
SVG  Editor
TabOut
Tailwind Intellisense
The 20-20-20 Rule
VSCode PDF

I tried to  attach the file here, but Github doesn't support the file type, you can either download the zip or download from the repo. 

[LanguageRunnerVSIX.zip](https://github.com/microsoft/vscode-vsce/files/7122567/LanguageRunnerVSIX.zip)

**Comment by joaomoreno** [comment]
Can you reproduce the issue without all those extensions? The theory is that one of the extensions might delete your extension, once it's installed.

**Comment by Password-Classified** [comment]
Thanks for replying so fast! I'll try.

**Comment by Password-Classified** [comment]
I have tried a few things, but it didn't change it. Could it be, since I placed my project entirely in `.vscode/extensions`, that it would disappear if the .VSIX was  uninstalled. I uninstalled it once I found a bug in it.

**Comment by joaomoreno** [comment]
Yes. That was it. It's a very bad idea to put your sources in there. cc @sandy081

**Comment by Password-Classified** [comment]
Sorry for my bad idea... 😳. I hope I didn't take up too  much of your  time.
