### ISSUE TITLE
`vsce package -t <target>` does not include target in the output package file name

### ISSUE THREAD

**Issue by prashantvc** [microsoft/vscode-vsce#604]
The target platform is missing in the output filename when you run the `vsce package -t <target>`
If I run the `vsce package` for multiple platforms the output VSIX gets replaced

_Expected:_
The `vsce package -t <target>` should name VSIX files in the following format

`{publisher}.{extensionName}-{normalizedExtensionVersion}@{targetPlatform}.vsix`

**Comment by joaomoreno** [comment]
Went with `${manifest.name}-${options.target}-${manifest.version}.vsix`.
