### ISSUE TITLE
Git Submodules are not being totally ignored (regression of #509)

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode-vsce#607]
Back in Nov/2020 I reported #509, which were fixed right after in the next release. I remember updating **vsce** back then, and the git-submodule related files where properly ignored from the packaged extensions.

I just updated **vsce** again (1.95.1 and 1.96.1) and just noticed a regression of #509. The git-submodules related files are again being packaged (the `.gitsubmodules` in root folder and a `.git` file inside each submodule, with a single `girdir` entry...).

I'm not sure this was caused by a new commit (https://github.com/microsoft/vscode-vsce/commit/05b3a2770dd7711efa6fb932a7846decc08f3454) added in March, with a  _revert fix #509_ comment, or if #418 could be the reason. The point is, those git-submodule related files are being packaged again.

The files that should be ignored are:

* `.gitsubmodules`
* `any-submodule\.git`

Thanks in advance

**Comment by joaomoreno** [comment]
Really unsure why that revert existed, unfortunately, but intuition tells me it was causing issues for other people. This is my bad, I should've recorded the reason. Since you have a local fix, I suggest to not change anything at the vsce level until more people ask for it. Sorry about that!

**Comment by alefragnani** [comment]
Hi @joaomoreno ,

No problem! I totally understand. 

As you said, I fixed my `.vscodeignore`, and those files are being ignored again. It's just a matter of applying the same changes my other extensions. 

Thank you

**Comment by Ark-kun** [comment]
I'm having the same issues. Why is `vsce` packaging `.gitmodules`?

**Comment by alefragnani** [comment]
I’ve updated my `.vscodeignore` with the below entries and now no git related file is being bundled anymore. At least on my repos, which I use submodules.

```
**/.git/**
**/.git
**/.gitmodules
```

Hope this helps
