### ISSUE TITLE
Do not tag platform extension as web extension unless target platform is web

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-vsce#608]
At present, vsce tags an extension as a web extension based on the rules described here - https://code.visualstudio.com/api/extension-guides/web-extensions#web-extension-enablement. With platform specific extensions support, we shall tag the platform specific extension as web extension only if the extension is targeted to web platform.

Additional validations

1. Invalidate the target platform is web and the extension does not abide to web extension rules.

**Comment by joaomoreno** [comment]
@sandy081 Should all VSIXs have the tag? Or just the one targetting `web`?

**Comment by joaomoreno** [comment]
One more thing. If a platform specific extension author goes through the hassle to provide a VSIX for web, they are likely to make their extension follow the auto detection rules and VSCE will tag it as a web extension any way. This happened to me yesterday in https://github.com/microsoft/vscode-platform-specific-sample

So there might not be anything left to do here.

**Comment by sandy081** [comment]
After discussion, we decided upon following:

- vsce adds or removes the web extension tag always based on web extension enablement rules irrespective of platform specific extension.

Hence closing this as no action needed.
