### ISSUE TITLE
Allow to release "beta" versions of  an extension

### ISSUE THREAD

**Issue by zimmski** [microsoft/vscode-vsce#615]
We would like to be able to release beta versions of our extension, e.g. version x.y.z-beta. This would help to release extensions that are not yet meant for production use or at least make it clear that they are not finished.

Sidenote: ` ERROR  The version string '1234.0.0-beta' doesn't conform to the requirements for a version. It must be one to four numbers in the range 0 to 2147483647, with each number seperated by a period. It must contain at least one non-zero number.` Is not entirely true. I release a 0.0.0 version before that. If i should create an issue for that, let me know.

**Comment by isidorn** [comment]
Follow this issue for more details please https://github.com/microsoft/vscode/issues/15756#issuecomment-916728348

**Comment by zimmski** [comment]
Thanks, following the issue now.

Do you think the error message related to the "0.0.0" validation should be adapted?
