### ISSUE TITLE
--baseContentUrl and --out options don't work at 1.99

### ISSUE THREAD

**Issue by AlencarGabriel** [microsoft/vscode-vsce#620]
I have an unpublished extension on the marketplace that is maintained by CI/CD. Until version 1.97 everything was fine, but now vsce started to break when creating the package.

I run this command on CI: `vsce package --baseContentUrl -o /totvs/drone/release/package`

And now I get this error: `ERROR Invalid version c:\temp\`

**Comment by AlencarGabriel** [comment]
ping

**Comment by joaomoreno** [comment]
This is an error in your invocation. `--baseContentUrl <url>` is supposed to have an argument: `url`.

It happens now because I fixed the optionality and made it into a required argument: https://github.com/microsoft/vscode-vsce/commit/7afabf5ecc3bb4d0b7b7abbd6bf77087164cfd63

Do you really need that `--baseContentUrl`?

**Comment by AlencarGabriel** [comment]
Previously it was necessary to type --baseContentUrl empty to generate our packages without errors, as we don't publish to the marketplace.

But I did some tests now just setting "-o" and it's not giving any more errors. I will change the CI.

You can disregard this problem. Thanks for listening.

**Comment by joaomoreno** [comment]
Oh interesting. I guess the right way today would be `--baseContentUrl ‘’`

**Comment by AlencarGabriel** [comment]
> Oh interesting. I guess the right way today would be `--baseContentUrl ‘’`

It doesn't work, it still has an invalid version error.

![image](https://user-images.githubusercontent.com/10109480/135144403-2ad3e72f-37ac-4439-a1d8-b332b4e59257.png)

I tested it by passing ' ' (with space) and it looks like it worked.
