### ISSUE TITLE
Try to prevent extensions from publishing `*` activated extensions

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-vsce#641]
Today, it's too easy to publish a `*` activated extension. Extensions get big enough and grow in scope and think that they absolutely need `*` activation when often they do not.

Being `*` activated hurts vscode's startup and even though we do call that out:
https://code.visualstudio.com/api/references/activation-events#Start-up
extensions still think that it's ok.

I want to try to dissuade extension authors from using `*` and also attempt to get information as to _why_ they think they need to be `*` activated because my theory is that most don't need to be... and for the very few that truly do, that signals a gap in our activation events that we should know about.

#### Proposed solution

I think we can either be aggressive by saying "throw an error unless they add an `--force-star-activation` flag...
or throw a warning saying it's highly discouraged.

In both cases, I'd also like the call to action for the extension author to open an issue saying why they think our activation events aren't good enough.

**Comment by usernamehw** [comment]
So, there is no flag `--force-star-activation` to not get the prompt?

**Comment by joaomoreno** [comment]
Correct. The prompt won't come up in CI... but when publishing manually it's probably a good idea to annoy the extension developer every time. Keep in mind that if you're using `*` today, there's very likely a better alternative as per the docs. If you don't think so, please let us know the use case.
