### ISSUE TITLE
rules[i] is not a function

### ISSUE THREAD

**Issue by pipe01** [microsoft/vscode-vsce#642]
When running `vsce package` on [this](https://github.com/pipe01/LogicScript/tree/master/LogicScript.VSCode) repository, I get the following error:

![imagen](https://user-images.githubusercontent.com/3885705/139533512-5567b477-5b59-45d2-acce-7fbbe1d0d433.png)

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/139649190-e3df8cee-cb14-4ec8-bdc4-0d41ed3b9f72.png)

Is that the latest vsce version?

**Comment by pipe01** [comment]
Yup

![imagen](https://user-images.githubusercontent.com/3885705/139665835-d81fcabc-7019-4b27-b90b-5b1a5dc9d87e.png)

I tried using WSL and that does work, so it seems the problem is Windows-specific.

**Comment by joaomoreno** [comment]
You're in the wrong directory, aren't you?

**Comment by pipe01** [comment]
No, sorry, I recently moved that repo to a subfolder in another repo. The issue still persists:

![imagen](https://user-images.githubusercontent.com/3885705/139677475-e4f3dff6-1580-4df4-b9c8-acf5fb3b2149.png)

**Comment by joaomoreno** [comment]
Can you reinstall vsce?

**Comment by pipe01** [comment]
That seemed to work haha, oh well. Thank you for the help.
