### ISSUE TITLE
LICENSE without extension

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode-vsce#644]
New feature with the prompt https://github.com/microsoft/vscode-vsce/issues/603:

>  WARNING  LICENSE.md or LICENSE.txt not found

Should it consider `LICENSE` file without an extension?

**Comment by joaomoreno** [comment]
Actually it does, it just prints that message. I've fixed the message.

**Comment by usernamehw** [comment]
Not the message, the prompt. When you have `LICENSE` file without extension it shouldn't prompt for confirmation.
