### ISSUE TITLE
Scoped packages are unsupported

### ISSUE THREAD

**Issue by thegecko** [microsoft/vscode-vsce#655]
When packaging an existing project which is scoped (e.g. the name is of the form `@my-scope/my-package`), the following error occurs:

```bash
Invalid extension name '@my-scope/my-package'
```

The obvious fix here is to change the package name and remove the scope, however that affects how the package is published to `npm` (if it is published), or (in our case) you can no longer publish the package to GitHub packages where a scope is mandatory.

Having to maintain multiple packages which just differ in name is a headache, so could scoped package names be supported, please?

**Comment by joaomoreno** [comment]
The extension itself isn't a node module, it isn't meant to be published to npm or GitHub packages, only to the Marketplace which doesn't support scopes, unfortunately.
