### ISSUE TITLE
How to disable '*' warning?

### ISSUE THREAD

**Issue by HenrikHolmIT** [microsoft/vscode-vsce#659]
Our extension needs to run when VSCode starts. Its an internal tool for our AL developers and things need to happen when VSCode and the extension starts. Its a bit annoying to have to apply a Y when an auto build is initiated.

"make_vsix": "ts-node .scripts/incrementVersion.ts & vsce package -o .vsix & start .vsix",

Just upgraded to version 2.5.0 from 1.96.3.

**Comment by joaomoreno** [comment]
What if you do `yes | npm run make_vsix`?

**Comment by HenrikHolmIT** [comment]
Works. Thanks.

**Comment by holm76** [comment]
It seems that the yes | is not working anymore.
When I run this script I get this message in the terminal:

'yes' is not recognized as an internal or external command

"vsce_make_vsix": "ts-node .scripts/incrementVersion.ts & yes | vsce package -o .vsix & start .vsix",

What it does is execute the incrementVersion.ts file which increments version in package.json. Then it should start a new build that should not prompt and then it should open a new explorer window with the resulting file.

But 'yes' does not seem to work anymore.

Did something recently change? vsce --version returns 2.11.0

**Comment by holm76** [comment]
Nevermind.

I got it fixed by finding the flags  --allow-star-activation --allow-missing-repository

Then I don't need the 'yes' parameter anymore.
