### ISSUE TITLE
I cant login.

### ISSUE THREAD

**Issue by kimaneSe** [microsoft/vscode-vsce#661]
I have logged into https://marketplace.visualstudio.com/manage/publishers/Mastergamer433?auth_redirect=True and i have the right id and i have an organization on https://dev.azure.com/ and everything but when i sign in(from bash terminal in windows) i get "ERROR The Personal Access Token verification has failed. additional informaion:

Error: Failed request; (401)"

I dunno why i get this error. i have re created the organization and access token and publisher but nothings work

**Comment by kimaneSe** [comment]
and now when i have posted a issue it works. ofc.

**Comment by pbpf** [comment]
> 现在，当我发布一个问题时，它就可以工作了。俄亥俄州

I have same problem, how you fix this?
