### ISSUE TITLE
Errors related to lack of permissions

### ISSUE THREAD

**Issue by smorimoto** [microsoft/vscode-vsce#662]
My guess is that there is probably a path globbing the one that specifies in vscodeignore. This causes the following error and should be fixed:

```
$ vsce package --out ocaml-platform.vsix --yarn
glob error [Error: EACCES: permission denied, scandir 'D:\a\vscode-ocaml-platform\vscode-ocaml-platform\_opam\.opam-switch\sources\ocamlbuild.0.14.0\examples\07-dependent-projects\libdemo'] {
  errno: -4092,
  code: 'EACCES',
  syscall: 'scandir',
  path: 'D:\\a\\vscode-ocaml-platform\\vscode-ocaml-platform\\_opam\\.opam-switch\\sources\\ocamlbuild.0.14.0\\examples\\07-dependent-projects\\libdemo'
}
 ERROR  EACCES: permission denied, scandir 'D:\a\vscode-ocaml-platform\vscode-ocaml-platform\_opam\.opam-switch\sources\ocamlbuild.0.14.0\examples\07-dependent-projects\libdemo'
error Command failed with exit code 1.
```

**Comment by smorimoto** [comment]
Is the problem that you only ignore `node_modules` here? I'm not sure.

https://github.com/microsoft/vscode-vsce/blob/f710e835b6a0ae55ad0b6e76e1b1d417319e0184/src/package.ts#L1396-L1409

**Comment by joaomoreno** [comment]
The problem seems to be that the user under which `vsce` runs doesn't have access to that directory. Please fix the file permissions on the folder.
