### ISSUE TITLE
VSCE 2.5.1 breaks CI pipeline

### ISSUE THREAD

**Issue by kborowinski** [microsoft/vscode-vsce#663]
VSCE 2.5.1 requires user input on warnings and thus breaks CI pipeline:

```powershell
tsc -p ./
vsce package
 WARNING  Using '*' activation is usually a bad idea as it impacts performance.
More info: https://code.visualstudio.com/api/references/activation-events#Start-up
Do you want to continue? [y/N]
```

Warnings should not require user interaction. Please add option to ignore warnings.

**Comment by joaomoreno** [comment]
> Please add option to ignore warnings.

Call it with `yes | vsce package`, if you're *sure* of what you're doing.

**Comment by justanotheranonymoususer** [comment]
Have same problem on Windows. No yes on Windows.

**Comment by joaomoreno** [comment]
https://stackoverflow.com/a/24416444

**Comment by justanotheranonymoususer** [comment]
That's horrible. Just add a command line switch!

**Comment by joaomoreno** [comment]
@justanotheranonymoususer What's the reason for using `'*'`?

**Comment by justanotheranonymoususer** [comment]
Personal helper extension that is always running for personal use

**Comment by joaomoreno** [comment]
OK. You can use the `VSCE_TESTS=1` env during your pipeline, at your own risk.
