### ISSUE TITLE
--pre-release is ignored when publishing with --packagePath

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-vsce#665]
The SSH extension is built and published using a vsix and the --packagePath flag, for example the publish command looks like `npx vsce publish --pre-release --packagePath $path --noVerify`. Apparently when publishing using that flag, the `--pre-release` flag is silently ignored and the extension is published as a stable version. Looking over the vsce code, I don't see the problem.

**Comment by joaomoreno** [comment]
Fixed by https://github.com/microsoft/vscode-vsce/pull/666
