### ISSUE TITLE
preRelease missing from api.ts

### ISSUE THREAD

**Issue by gnikit** [microsoft/vscode-vsce#667]
I am not sure if I am missing something but I don't see a `preRelease` option in the API. Shouldn't it be located under *api.ts>IBaseVSIXOptions*?

I am far from an expert in TypeScript so forgive my ignorance if this question is trivial.

**Comment by joaomoreno** [comment]
@sandy081 Can you check? https://github.com/microsoft/vscode-vsce/blob/main/src/api.ts

**Comment by sandy081** [comment]
Created PR - https://github.com/microsoft/vscode-vsce/pull/679
