### ISSUE TITLE
Can vscepackageTask support README.zh.md and gitee ?

### ISSUE THREAD

**Issue by LY1806620741** [microsoft/vscode-vsce#674]
# need
1. process Readme.Zh.md file
2. support gitee.com repository

# because
## first
  I write a [plugin ](https://gitee.com/tqybt/line-share-vscode-plugin) and try to package. But vsce throw error 
`Error: Couldn't detect the repository where this extension is published. The image './doc/en.jpg "usage image"' will be broken in README.md. GitHub/GitLab repositories will be automatically detected. Otherwise,
please provide the repository URL in package.json or use the --baseContentUrl and --baseImagesUrl options.`.

then I found [code](https://github.com/microsoft/vscode-vsce/blob/main/src/package.ts#L819) can't match `gitee.com`. and yy plugin use [gitee repository](https://gitee.com/tqybt/line-share-vscode-plugin/blob/48d8f3e25bcab9debc6cb639b36045785d8e0ca1/package.json#L10) .

## second
I resolve first problem by edit glupfile add createVSIX option [code](https://gitee.com/tqybt/line-share-vscode-plugin/blob/48d8f3e25bcab9debc6cb639b36045785d8e0ca1/gulpfile.js#L77)
but the other problem happen. My `README.zh.md`'s Image url is not replace. Vsce source code has not way add muti languege readme file.[code](https://gitee.com/tqybt/line-share-vscode-plugin/blob/48d8f3e25bcab9debc6cb639b36045785d8e0ca1/README.zh.md#L6)

**Comment by joaomoreno** [comment]
The `--baseContentUrl` and `--baseImagesUrl` options exist to support any 3rd party repo hoster. I suggest to use them.

> Vsce source code has not way add muti languege readme file.code

Correct, we only have support for `README.md` for now, unfortunately.
