### ISSUE TITLE
vsce package, Extension entrypoint(s) missing

### ISSUE THREAD

**Issue by yzhang-gh** [microsoft/vscode-vsce#675]
(Happy New Year!)

The GitHub CI of my vscode extension has been working very well for a long time (vsce v1.x). However, it doesn't seem to work with vsce v2.x and says

```
 ERROR  Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':
  extension/out/src/extension
```

I'm a little confused. Is there any API change? Guess it may be related to the VS Code Web but I haven't got time to take a closer look.

---

### Additional information

the `package.json`
https://github.com/yzhang-gh/vscode-dic-completion/blob/master/package.json

the ci file
https://github.com/yzhang-gh/vscode-dic-completion/blob/master/.github/workflows/main.yml

the failed ci log
https://github.com/yzhang-gh/vscode-dic-completion/runs/4679563201?check_suite_focus=true

```
+ vsce@2.6.0

Run vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> dictionary-completion@1.1.2 vscode:prepublish /home/runner/work/vscode-dic-completion/vscode-dic-completion
> tsc -p ./

 ERROR  Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':
  extension/out/src/extension
```

the past passed ci log
https://github.com/yzhang-gh/vscode-dic-completion/runs/3868473421?check_suite_focus=true

```
+ vsce@1.100.1

Run vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> dictionary-completion@1.1.1 vscode:prepublish /home/runner/work/vscode-dic-completion/vscode-dic-completion
> tsc -p ./

 DONE  Packaged: /home/runner/work/vscode-dic-completion/vscode-dic-completion/dictionary-completion-1.1.1.vsix (13 files, 79.63KB)
```

**Comment by haneefdm** [comment]
Same issue. I can package  (and use the VSIX file successfully) but cannot publish with 2.6.0. I rolled back to version 2.5.3 and I can publish again.

My package.json hasn't changed in a long time *in this aspect* and I know that the entry point file does exist

**Comment by paulhocker** [comment]
+1

This needs to be addressed immediately. Kind of disappointed that a new version was dropped on New Years Eve when there is little available for support.

**Comment by ritwickdey** [comment]
Quick Fix: Append the `.js` extension in `main` field of `package.json`
![image](https://user-images.githubusercontent.com/18099464/147859691-637853a4-41f3-421d-adcd-8f487e360e37.png)

**Comment by mohanraj-r** [comment]
I notice the same error with the latest vsce 2.7.0 

Even the quick fix suggestion didn't help
> Quick Fix: Append the .js extension at main field of package.json
