### ISSUE TITLE
Unable to publish extension properly

### ISSUE THREAD

**Issue by wind-lc** [microsoft/vscode-vsce#682]
Steps to Reproduce:

1. Always get this error when publishing: ERROR  The Extension Id already exist in the Marketplace. Please use the different Id
2. [stackoverflow](https://stackoverflow.com/questions/70502536/error-publishing-extensions-in-visual-studio-code-marketplace)

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by ssbarnea** [comment]
@joaomoreno Sorry but the OP is is right, that error message is quite confusing as it does not mention which is the problematic extension Id!

```
$ npx vsce publish --pre-release -i ansible-0.11.7357de.vsix
 INFO  Publishing '42picky.ansible v0.11.12.13'...
 ERROR  The Extension Id already exist in the Marketplace. Please use the different Id
```

Hint, `42picky.ansible` does not even exist in the marketplace!
