### ISSUE TITLE
provide vsce package -y option to run without interactive

### ISSUE THREAD

**Issue by chouzz** [microsoft/vscode-vsce#683]
`vsce package` command  will get wanning if we using '*' activation or without lience, and let user select yes or no to continue,  hope there an option "-y" to skip these warnnings. E.g: `vsce package -y`
```bash
 WARNING  Using '*' activation is usually a bad idea as it impacts performance.
More info: https://code.visualstudio.com/api/references/activation-events#Start-up
Do you want to continue? [y/N]
```

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode-vsce/issues/659
