### ISSUE TITLE
markdown-it should be upgraded

### ISSUE THREAD

**Issue by FloLey** [microsoft/vscode-vsce#685]
Hello,
when using vsce I now have 2 moderate severity vulnerabilities. 
markdown-it should be updated to 12.3.2+ (https://github.com/advisories/GHSA-6vfc-qv3f-vr6c)
but vsce uses version 10.0.

Thanks :)

**Comment by heejaechang** [comment]
@joaomoreno when should new version with this fix be released?

**Comment by Sven-Seyfert** [comment]
Hi folks,

it would be nice when you could release this update/fix. Because it's important to get a non-vulnerable version of markdown-it again. Thanks for your work and keep healthy folks 👍 .

Best regards
Sven

**Comment by Sven-Seyfert** [comment]
Thank you 🎉 .
