### ISSUE TITLE
 ERROR  Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':   extension/extension.js

### ISSUE THREAD

**Issue by npsulav** [microsoft/vscode-vsce#687]
ERROR  Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':
  extension/extension.js

**Comment by joaomoreno** [comment]
Please double check that the file you reference in the `main` or `browser` properties in `package.json` do in fact exist.

**Comment by npsulav** [comment]
ok i checked for it and using the previous version of vsce did a work around for me without changing `package.json`
