### ISSUE TITLE
[feats] auto push after version bump and add dry-run option in publish

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/vscode-vsce#694]
I want to add two features as the title says,

for auto git push, users can use `version` hooks to do this thing, but we may do it internaly.

for dry-run, we can use dry-run to write some unit tests and simply dry-run to see the publish detail

**Comment by joaomoreno** [comment]
> auto push after version bump

You can easily write a script around vsce to do this. It doesn't have to be built into vsce itself.

> for dry-run, we can use dry-run to write some unit tests and simply dry-run to see the publish detail

`vsce ls` will show you all the files which will be included in the extension VSIX, which is, in fact, the dry run of publishing.
