### ISSUE TITLE
Replace vscodeignore mechanism

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode-vsce#697]
`.vscodeignore` is kind of a crazy way to distribute software. It's kind of "do an in-tree build and then tell us which files *not* to ship". Quite weird and error-prone. The code for it is also full of magic and has zero logging which makes it hard to use. E.g. for some reason `!/foo/**` does not work. You have to do `!foo/**` [probably because of this `substr(1)`?](https://github.com/microsoft/vscode-vsce/blob/9acc6c660d206795a8bb13ba59f502f001470488/src/package.ts#L1494)

A better way is to just ship a single directory e.g. `build` and have the user's build system copy all the file in, essentially whitelisting them. I think it would be good to support something like that instead of `.vscodeignore` (you'd have to support both for a while).

For example

```
vsce --no-vscodeignore --files dist --files package.json
```

Or perhaps just use an explicit whitelisting glob file instead - `.vscodeinclude`. It can give an error if both files are present.

Would you accept a PR for that?

**Comment by joaomoreno** [comment]
No. Ignore files are very common nowadays. You'll find them in tools like git, npm, eslint, etc. It's a common pattern that most people know how to work with and will happily do so.

If you want to implement something like you suggested you can do it without any additional features in vsce:

1. Build your extension, place everything in a `build` folder
2. Launch `vsce` from that build folder

Thanks for the feedback.

**Comment by Timmmm** [comment]
Good suggestion, thanks.

You might still want to take a look at the `!/foo` bug, and maybe document some of the magic that happens.
