### ISSUE TITLE
Deleting a publisher doesn't hide Personal Access Token

### ISSUE THREAD

**Issue by danschultewhpc** [Microsoft/vscode-vsce#70]
When I attempt to delete a publisher, I'm asked for my personal access token. When I put it in, it displays on the console in plain text, and then displays the stars on the next line. The stars should be displayed instead of my personal access token, not in addition to.

**Comment by danschultewhpc** [comment]
![capture](https://cloud.githubusercontent.com/assets/17203620/13358370/d3170b7e-dc63-11e5-899f-115f7a0b4171.PNG)

**Comment by joaomoreno** [comment]
Seems to be npm/read#29

**Comment by joaomoreno** [comment]
Can't reproduce this any more.
