### ISSUE TITLE
Feature: support `--allow-star-activation` flag

### ISSUE THREAD

**Issue by wandyezj** [microsoft/vscode-vsce#700]
The vsce package command prompts the following which require a manual response

>  WARNING  A 'repository' field is missing from the 'package.json' manifest file.

>  WARNING  Using '*' activation is usually a bad idea as it impacts performance.

Would it be reasonable to not prompt OR to provide a flag that ignores these warnings?

Some extensions have a private repository so should not include the repository field and some extensions need to activate on startup with the '*' activation event.

When generating the visx file in automation these warnings are annoying to work around.

Is this change reasonable to make?

I'm happy to make this change if this is reasonable.

**Comment by joaomoreno** [comment]
Yeah, given it's the 3rd time or so someone asks for this, let's just have a flag.

**Comment by holm76** [comment]
How do you actually use  the '*' flag?
