### ISSUE TITLE
The Extension Id already exist in the Marketplace.

### ISSUE THREAD

**Issue by Hongbusi** [microsoft/vscode-vsce#702]
Execute `vsce publish` to report an error:

``` bash
 ERROR  The Extension Id already exist in the Marketplace. Please use the different Id.
```

But I didn't find where the extension id is configured.

**Comment by holazz** [comment]
I have the same problem, have you solved it? @Hongbusi

**Comment by Hongbusi** [comment]
Modify your package.json name field.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode-vsce"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月25日(星期五) 下午3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode-vsce] The Extension Id already exist in the Marketplace. (Issue #702)





 
I have the same problem, have you solved it? @Hongbusi

**Comment by holazz** [comment]
> 

I already did that, thanks！
