### ISSUE TITLE
Support globs in `publish --packagePath`, like `vsce publish --packagePath '*.vsix'`

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-vsce#724]
So that we don't need to use something like the below:

```
npx vsce publish --packagePath $(find . -iname *.vsix)
```

From https://github.com/microsoft/vscode-platform-specific-sample/blob/37a2523b99d3348c53f4519faf1ad9e04d06d672/.github/workflows/ci.yml#L74

Which is of course not supported on Windows and can potentially work differently across different Linux versions.

**Comment by joaomoreno** [comment]
I'd argue that crosses the responsibility line: a tool should do one thing and do it well. I'm tempted to close out of scope.

**Comment by felipecrs** [comment]
I saw this extensively being used in linters, like ESLint, Prettier, etc. Example:

```console
eslint --fix '**/*.ts'
```

Instead of, let's say:

```console
eslint --fix $(find . -iname '*.ts')
```

And, if I were to guess, I would suspect it's due to the same reasons stated above (like portability).

All the needed libraries are already in `vsce` if we want to make it happen.

PS: I can send a PR for it if you agree, but if not, it's fine (the absence of this feature will mean that I will have to implement it in semantic-release-vsce instead -- as part of supporting the platform specific extensions publishing).

**Comment by joaomoreno** [comment]
I'd say no, just because it's such a fringe scenario (platform specific extensions) and not one publishers often run by hand... once it's scripted, they don't worry about it any more.

**Comment by felipecrs** [comment]
@joaomoreno all right. Thank you for the discussion. :)
