### ISSUE TITLE
Can we detect the sponsor field in package.json and require vsce 2.9.0

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-vsce#733]
Refs: https://github.com/microsoft/vscode/issues/150748

1. Have an outdated version of `vsce`, for example `2.6.7`
2. Have a `sponsor` field in your `package.json`
3. `vsce publish` -> all is good 🐛 

I was actually using an outdated version of vsce. So the sponsor information does not get added to the extension attributes.
If we see that a user has set a `sponsor` field can we require a newer `vsce` version somehow?
We probably do not have this capability but wanted to check.

**Comment by sandy081** [comment]
I wonder if this can be possible as the older versions are already published and we cannot change them.

CC @joaomoreno

**Comment by isidorn** [comment]
Yeah I thought it would only be possible if we already have some infrastructure for this.
And we probably don't. Thanks anyways!

**Comment by joaomoreno** [comment]
We already have the feature of vsce warning the user there's a new version available. There's not much more we can do here, unless you have a time machine at hand.
