### ISSUE TITLE
Don't check for yarn.lock

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-vsce#744]
Can we remove this check:

https://github.com/microsoft/vscode-vsce/blob/76b06f2030a6e8c750f3d1d38bd30396c13df897/src/npm.ts#L188

And rely on yarn to throw `error No lockfile in this directory. Run `yarn install` to generate one.`?
This makes spotting mistakes easier. When using `--yarn`, the user very much expects the tool to be in a yarn working dir.

Also, this check doesn't work for yarn workspaces (though much other stuff also doesn't work for yarn workspaces, but they can be hacked around - this check cannot be hacked around).

**Comment by joaomoreno** [comment]
Makes sense, wanna send over a PR?
