### ISSUE TITLE
Support free trial label for extensions in the Marketplace

### ISSUE THREAD

**Issue by prashantvc** [microsoft/vscode-vsce#748]
Allow extension authors to indicate extensions are `Free` or `Free Trial` in the Marketplace
Marketplace will read pricing value from the manifest property `Microsoft.VisualStudio.Services.Content.Pricing`

**Comment by joaomoreno** [comment]
@prashantvc What values are possible for the `Microsoft.VisualStudio.Services.Content.Pricing` property? Is it exactly `Free` and `Free Trial` only?

**Comment by joaomoreno** [comment]
Nevermind, just saw the PR.

**Comment by prashantvc** [comment]
> @prashantvc What values are possible for the `Microsoft.VisualStudio.Services.Content.Pricing` property? Is it exactly `Free` and `Free Trial` only?

No, there is `Paid` as well (for VS and AzDO extensions), but we are limiting `Free` and `Free Trial` for VS Code

**Comment by prashantvc** [comment]
@joaomoreno we may want to close this issue. It's been live on the Marketplace for a while
