### ISSUE TITLE
Differences between the CLI and the API

### ISSUE THREAD

**Issue by nhedger** [microsoft/vscode-vsce#754]
Not sure if this is by design, but I noticed that a few options currently available on the CLI are not exposed on the API.

The `packageCommand` function accepts a `IPackageOptions` which seems to contain all the available options but the API's `createVSIX` function accepts a `ICreateVSIXOptions` which narrows the available options.

I guess what I'm asking is:

1. Is there a good reason for this that I am missing ?
2. Would you be willing to open all options to the API ?

I'd be willing to submit a PR.

**Comment by joaomoreno** [comment]
I believe the current state is as is just 'cause no one asked for those API calls yet. PR welcome!

**Comment by nhedger** [comment]
Good to hear, I'll PR something soon in that case.
