### ISSUE TITLE
Problem to install with wsl-2 CentOS Stream 9

### ISSUE THREAD

**Issue by lokize** [microsoft/vscode-vsce#756]
![image](https://user-images.githubusercontent.com/19701630/178812622-f8e5b5e5-a1f4-4702-add3-223baf5e63f5.png)

Hi today i installed a new machine and for some unknown reason i am not able to install vsce, i am using CentOS Stream 9 with nvm and nodejs v16.16.0, I tried reinstalling other versions of node and wsl but nothing solved the problem...

**Comment by joaomoreno** [comment]
What command are you running to install vsce?

**Comment by joaomoreno** [comment]
What if you try to:

```
mkdir foo
cd foo
npm init
npm install keytar
```

Does that work?

**Comment by lokize** [comment]
> 

yes, its worked!
![image](https://user-images.githubusercontent.com/19701630/179097703-986a8dc6-2835-4f0b-98fb-7f37f870bfe5.png)

**Comment by joaomoreno** [comment]
What about:

```
mkdir foo
cd foo
npm init
npm install vsce
```

**Comment by joaomoreno** [comment]
I would go through the personal access token creation docs again: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token

**Comment by lokize** [comment]
i created another personal token but still have a error 401...
