### ISSUE TITLE
Compatibility issue with PNPM package manager in 2.10.0

### ISSUE THREAD

**Issue by drochgenius** [microsoft/vscode-vsce#758]
We are using `pnpm` package manager in our monorepo, in which we have many Visual Studio Code extensions.

Up until version `2.10.0`, we were able to build the plugins with the `--yarn` option, but from version `2.10.0` it complains the `yarn.lock` is not available due to this change: d68e2f7947069dd26c6aa425523cee8372dbd73a.

Without the `--yarn` option, the plugins do not build in the monorepo context.

Could you please explain why this change was made, and advise how we could adapt our codebase?

Thanks

**Comment by joaomoreno** [comment]
@drochgenius PNPM support is pending: https://github.com/microsoft/vscode-vsce/issues/421, we never implemented it.

Looking at d68e2f7947069dd26c6aa425523cee8372dbd73a, the only conclusion I can draw is that using `--yarn` in a workspace without `yarn.lock` was simply a way not to do any dependency analysis whatsoever. While this (kind of) worked for you, it wasn't intended behavior. d68e2f7947069dd26c6aa425523cee8372dbd73a is still a correct change. Very likely you've been shipping your extension with dev dependencies.

In your workspace, where do `node_modules` live? Do you have a repo I can look at?

**Comment by drochgenius** [comment]
Thanks @joaomoreno for your response.

In out monorepo, the `node_modules` is at the root, that is 2 levels above the vscode plugin.

```
/node_modules/
/plugins/my-vs-code-plugin/
```

We switched from `yarn` to `pnpm` about 6 months ago, and it's been a very positive change for us, so I'm really looking forward to`vsce` supporting `pnpm`.

In the meantime, we have fixed the version to `vsce@2.9.3` and continue using the `--yarn` option.

Regards

**Comment by joaomoreno** [comment]
Just curious... when you run `vsce ls` do any node modules appear in that list?

**Comment by drochgenius** [comment]
I must to apply the `--yarn` flag, or else `vsce ls` outputs a bunch of missing package errors.
Now when I do run this command: `pnpm exec vsce ls --yarn`, I don't see any node modules in the list.
I just see a list of files that are local to my VS Code extension.

**Comment by joaomoreno** [comment]
So your extension doesn't really depend on any node modules to work, correct? If so, you should not be using `--yarn` at all... you should be using `--no-dependencies`: this will skip dependency analysis altogether.

**Comment by drochgenius** [comment]
Thanks @joaomoreno ,

Yes it works perfectly if I use the `--no-dependencies` flag instead of `--yarn` with `vsce@2.10.0`.
Indeed, I don't have external dependencies because I first bundle the extension using `webpack`, so when I reach the packaging step with `vsce` all my external dependencies are already resolved in the bundle.

I now understand I was not using `vsce` correctly for my setup.
Thanks very much for your help, I think this issue can now be closed.

**Comment by melMass** [comment]
Just to clarify because I spent way too much time on this matter 😅:

Both vsce `package` and `publish` have a `bundle` step (not entirely sure by what it's powered or how it decides things), if, like IMHO you should, you handle bundling deps as part of your build process append `--no-dependencies`.

AFAIK @drochgenius your workflow was actually right, since I'm pretty sure you are handling deps bundling as part of your monorepo
