### ISSUE TITLE
Unable to Publish Extension - The Extension Id already exist

### ISSUE THREAD

**Issue by johnyenter-briars** [microsoft/vscode-vsce#761]
Greetings, and thank you for all the hard work you do for the VSCode ecosystem!

## Explanation of Issue
We are unable to publish our extension either to the marketplace, either via the command line `vsce` or via the marketplace UI.

When using `vsce` we get the below error:

```bash
C:\Users\JohnYenter-Briars\r16_internal\bamboo>vsce publish
Executing prepublish script 'npm run vscode:prepublish'...
> bamboo-vscode@0.2.0 vscode:prepublish 
> npm run compile
> bamboo-vscode@0.2.0 compile
> tsc -p ./
INFO  Publishing 'root16.bamboo-vscode v0.2.0'...
ERROR  The Extension Id already exist in the Marketplace. Please use the different Id   
```

NOTE: this is *after* performing `vsce login root16` which then promps for the PAT, which results in a successful login.

When publishing via the UI (after successfully packaging), we get the following:

![image](https://user-images.githubusercontent.com/42982326/182393545-61774aea-84ce-4e07-9ea9-27ba6e201621.png)

In our `package.json` we have defined the extension ID:

```json
"name": "bamboo-vscode",
"displayName": "Bamboo",
"publisher": "root16",
"repository": {
"url": "https://github.com/Root16/bamboo"
},
"version": "0.2.0",
```

Our understanding is that the Extension Id should now be: `root16.bamboo-vscode` which should be unique across the market place.

Is there some step or definition we're missing? Or could this be a bug in `vsce`?

### Assorted Notes
- It looks like users have reported similar issues, as recently as 5 days ago as per: #682

### General Debugging Information:
- `vsce` version: 2.10.0 
- `node` version: v18.1.0   
- [VSCode market place publisher](https://marketplace.visualstudio.com/publishers/root16)
- [VSCode Extension Source Code](https://github.com/Root16/bamboo)
- [Link to VSCode Extension package.json](https://github.com/Root16/bamboo/blob/main/package.json)

**Comment by Katsute** [comment]
I've wasted an hour on my extension trying to figure out why it wouldn't publish for this very reason.

That error message is incredibly misleading, the marketplace only considers the **→→ name ←←** `bamboo-vscode` when determining if an extension is 'unique'. An extension [`garyxuehong.bamboo-vscode`](https://marketplace.visualstudio.com/items?itemName=garyxuehong.bamboo-vscode) is already 'using' that extension id.

**Comment by johnyenter-briars** [comment]
> I've wasted an hour on my extension trying to figure out why it wouldn't publish for this very reason.
> 
> That error message is incredibly misleading, the marketplace only considers the **→→ name ←←** `bamboo-vscode` when determining if an extension is 'unique'. An extension [`garyxuehong.bamboo-vscode`](https://marketplace.visualstudio.com/items?itemName=garyxuehong.bamboo-vscode) is already 'using' that extension id.

Thank you so much Katsute! I will give this a try and report back and close the issue if required.

**Comment by johnyenter-briars** [comment]
@Katsute  is correct for which I am grateful. The name must also be unique, not just the extension Id. I would recommend that this issue be turned into a bug report, as I would consider that message very misleading. But for now I'll close this issue.
