### ISSUE TITLE
Print user friendly message when vsce is installed

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-vsce#769]
I was just playing around with [dapr](https://docs.dapr.io/getting-started/install-dapr-cli/) and I like that once I install it from the cli they print a nice message pointing to the docs:
"To get started with Dapr, please visit https://docs.dapr.io/getting-started/"

We could do the same thing for vsce? Or at least for `vsce --help`

Potential message:
"To learn more about the VS Code extension API, please visit https://code.visualstudio.com/api/extension-guides/overview
To connect with the VS Code extension developer community, please visit https://github.com/microsoft/vscode-discussions"

**Comment by joaomoreno** [comment]
I think we don't have a hook for what happens after `npm i -g vsce`. But this could work for `vsce --help`, wanna submit a PR?

**Comment by isidorn** [comment]
@joaomoreno isn't there some npm postinstall script we can run and that script could print?
But putting it in help also works.

Yeah, let me assign to myself and next milestone.

**Comment by rebornix** [comment]
@isidorn this feature doesn't seem to start this month so I removed it from the milestone.
