### ISSUE TITLE
vsce ls doesn't list all files that are packaged

### ISSUE THREAD

**Issue by serkonda7** [microsoft/vscode-vsce#770]
Output of `npx vsce ls` counting eight files:
```
CHANGELOG.md
images/icon_256x256.png
LICENSE.md
out/extension.js
out/language-configuration.json
out/vba.tmGrammar.json
package.json
README.md
```

Output of `npm run package` stating 10 files:
```
DONE  Packaged: redacted/vscode-vba/vscode-vba-0.7.0-dev.vsix (10 files, 27.26KB)
```

What additional two files are packaged here?

These numbers should match.

**Comment by joaomoreno** [comment]
A VSIX is nothing more than a ZIP file. Your can open it with any ZIP program. You'll find additional metadata files in there.

**Comment by serkonda7** [comment]
Thanks, have seen it now.
Still somewhat confusing.
