### ISSUE TITLE
`vsce publish` includes files from adjacent directories.

### ISSUE THREAD

**Issue by romainmenke** [microsoft/vscode-vsce#777]
Workspace outline :

```
'./' workspace A root
  - `./projects/1/` project 1
  - `./projects/2/` project 2
  - `./projects/3/` project 3
  - ...
'./vscode-extensions/' workspace B root
  - './vscode-extensions/node_modules' shared `node_modules`
  - './vscode-extensions/extension-1' extension 1
  - './vscode-extensions/extension-2' extension 2
  - ...
```

Each is a npm workspace with a single `package-lock.json` and a shared `node_modules` directory.

When we try to publish extension 1 it fails with : ` ERROR  invalid relative path: extension/../.DS_Store`

`vscode ls` reveals :

```
../.DS_Store
dist/extension.js
package.json
README.md
../extension-2/.eslintrc.js
../extension-2/.gitignore
...
```

So it tries to include extension 2 while publishing extension 1.

-----

I have no idea if `workspace A` is relevant in any way.
I wanted to provide an as complete picture of our setup as possible.

**Comment by romainmenke** [comment]
When I remove `workspace B root` and treat each extension as completely separate it works fine.

`vscode ls` :

```
dist/extension.js
package.json
README.md
```

**Comment by joaomoreno** [comment]
It's hard to understand the full steps here. Can you scaffold a project and put it in GitHub so I can run `vsce` against it and reproduce? Also, when you run `vsce`, which directory exactly are you running it from?

**Comment by romainmenke** [comment]
Minimal repro of our setup : https://github.com/romainmenke/vsce-workspace-bug-1

**Comment by joaomoreno** [comment]
I continue not to fully understand from where you run `vsce`. In your sample, I just ran it from `.vscode-no-workspaces/extensions/a` and it works:

![image](https://user-images.githubusercontent.com/22350/196885373-52c5dcfd-2e38-404f-8de4-f1ead7d912a9.png)

**Comment by romainmenke** [comment]
@joaomoreno Thank you for taking a look.
I am unsure how or why this was unclear :/
But please let me know how I can improve the readme on the repo.

To trigger the failure you follow these steps :

>Fails with workspaces :
>
>```bash
>cd .vscode/extensions/a
>npm install
>npm run vsce ls
>```

**Comment by joaomoreno** [comment]
Oh I completely ignored the README. Sorry about that.

**Comment by joaomoreno** [comment]
I still can't reproduce.

![image](https://user-images.githubusercontent.com/22350/196887996-97e47175-8cbe-4c46-a6b7-781179cb0e11.png)

But I notice you're using npm workspaces, which vsce doesn't support yet: https://github.com/microsoft/vscode-vsce/issues/580

**Comment by romainmenke** [comment]
Thanks for the reply and link to that issue.

Is it possible to have a more specific error message?

It took me a long time to figure out that workspaces were a factor and it didn't even occur to me that they were not supported at all (we've had them for some time now).

I don't mind that they aren't supported (yet) but if possible and low effort a good error message would be nice.

**Comment by joaomoreno** [comment]
It's hard to detect workspaces from `a`'s viewpoint. What is detected is the presence of symlinks. We could add a disclaimer _maybe you're using npm workspaces?_ to the error message.

**Comment by romainmenke** [comment]
If it is not possible to accurately detect workspaces it is likely better to do nothing.
Otherwise we risk making it confusing for other cases.

**Comment by hayemaxi** [comment]
as a workaround, you can add adjacent directories to your `.vscodeignore` file.
