### ISSUE TITLE
Support versioning from git

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode-vsce#778]
I noticed there's what looks like a placeholder for supporting version stamping using git information here:
https://github.com/microsoft/vscode-vsce/blob/8e193c9f074da4560ffdfcb18b8e80e0a343c167/src/package.ts#L369-L370

I wanted to offer that I already have an NPM package that can stamp package.json with a version computed from git history (using Nerdbank.GitVersioning). 

Using it is easy. Today, I run this before building the package with `vsce package`:

```
npm i -g nerdbank-gitversioning && nbgv cloud && nbgv-setversion
```

The `nbgv cloud` isn't necessary, but sets the cloud build number to match the version for easy association.

Anyway, if vsce were to depend on the `nerdbank-gitversioning` NPM package, it could use the node API to invoke the setversion function directly as part of the packaging.

**Comment by joaomoreno** [comment]
Given that you can invoke vsce as `vsce package [version]`, couldn't you do something like `vsce package $(nbgv-getversion)`?

**Comment by AArnott** [comment]
Yes, I believe that would also work.

**Comment by joaomoreno** [comment]
Let's prefer composition over kitchen-sinking, then. 👌
