### ISSUE TITLE
The library prepends the content base URL in front of the VSCode command links in the README file

### ISSUE THREAD

**Issue by nickImbirev** [microsoft/vscode-vsce#781]
Today, this is possible to make links to the VSCode commands in the README.md for the VSCode extension, like it is mentioned [here](https://stackoverflow.com/questions/68641160/is-it-possible-to-run-visual-studio-code-commands-from-markdown).

**AS IS:** When the link with the command is inserted in the README.md file, the vsce library will try to prepend the command link with the base content URL in front of it, which makes the command unreachable for the published extension.

**TO BE:** It would be great to avoid prepending these commands links, because they are not part of the external content that should be uploaded into the repository or somewhere else.. 

Additional point here: disabling the prepending process in general does not help, because I still need to have other links processed, but they contains links to the images or gif files, not the VSCode commands.

I tested it on the vsce 2.12.0 and MacOs Monterey 12.4 with VSCode 1.72.2.

**Comment by mjbvz** [comment]
We only support a single uri command in extension readmes, showing the release notes: https://github.com/microsoft/vscode/blob/845f524e35efa0084bf5ff3bc82f3aab7516e93a/src/vs/workbench/contrib/extensions/browser/extensionEditor.ts#L732

This won't work on the marketplace pages on web and I'm not sure what the use case of this command is. Rewriting command uris is probably wrong, but this also seems like a pretty niche use case

**Comment by joaomoreno** [comment]
Alright, closing this as out of scope, given it wouldn't work for any command other than showing the release notes.
