### ISSUE TITLE
vsce doesn't package npm libraries

### ISSUE THREAD

**Issue by Abbyyan** [Microsoft/vscode-vsce#796]
npm version: `8.11.0`
vsce version: `2.15.0`
I'm using `vsce package ` to package vsce extension into a vsix, and i add `axios` into `dependencies`, which looks like follows in `package.json`.
```json
 "dependencies": {
    "vscode-languageclient": "^5.2.1",
    "ws": "^6.2.1",
    "moment": "^2.17.0",
    "axios": "^0.27.2"
  },
```

I package it into a `vsix` and unzip the `vsix`, but i can't find `axios ` in the unzip dir. I didn't have a `.vscodeignore` file under the repo, but `axios` isn't been packaged into the `vsix`.
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/12140508/206183351-24579ae3-48a7-41c6-ac4e-6e082e95e987.png">

When i change to another mac, which has `npm == 7.3.0` and `vsce == 1.77.0` with the same code to package the `vsix`. The packaged vsix works well and i can find `axios` in the unzip dir. Two different situations really bother me a lot. 
Is there any change in the vsce package mehod please? Hope for your help. Thanks a lot

**Comment by joaomoreno** [comment]
What does `vsce ls` return?

**Comment by Abbyyan** [comment]
> vsce ls

`vsce ls` didn't show the `axios` package. Where it might be caused please?

**Comment by joaomoreno** [comment]
I need you to help me figure that out.

**Comment by Abbyyan** [comment]
1. check: add `axios` into `dependencies`(✅)
<img width="775" alt="image" src="https://user-images.githubusercontent.com/12140508/206206067-9794fa6b-f450-4a48-ade8-cf679de0d5e1.png">
2. `npm install` and `axios` is added into `node_modules` in the dev folder(✅)
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/12140508/206206576-d542dfe9-5e92-4eb8-a65f-2d3ea620bd9e.png">
3. check: don't add `.vscodeignore`(✅)
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/12140508/206206843-5d74f92a-2c84-4459-921f-68492e2a8b30.png">
4. run `vsce ls`
<img width="872" alt="image" src="https://user-images.githubusercontent.com/12140508/206207170-7799a58b-1538-44f2-bf66-262c9a73d916.png">
Any advise please? Thanks a lot

**Comment by joaomoreno** [comment]
vsce will ignore dev dependencies. So, if axios is a regular dependency, remove it from `devDependencies`. Same for `segment`.

**Comment by Abbyyan** [comment]
> vsce will ignore dev dependencies. So, if axios is a regular dependency, remove it from `devDependencies`. Same for `segment`.

After remove from `devDependencies`,it worked!! Thank you very much!
Is this a new feature please? Which puzzled me at first was that it would work on another machine.
Thanks for your help. It really helps me a lot

**Comment by joaomoreno** [comment]
Definitely not a new feature, this behavior has been there since a long long time.
