### ISSUE TITLE
Update approved badges url from VSMarketplaceBadges

### ISSUE THREAD

**Issue by equiman** [microsoft/vscode-vsce#799]
https://code.visualstudio.com/api/references/extension-manifest#approved-badges

The approved badges list includes the URL `vsmarketplacebadge.apphb.com` but his domain was changed to `https://vsmarketplacebadges.dev`

Is it possible to replace it to avoid this error when publishing with `vsce` command?

![image](https://user-images.githubusercontent.com/933393/206918563-31b5bf67-36c9-4a5c-afd4-258a567245d0.png)

**Comment by eamodio** [comment]
@joaomoreno @sandy081 Can we get this released? It looks like the marketplace is now blocking the old urls, and VSCE (until this goes out) won't allow the new ones.

**Comment by isidorn** [comment]
We have updated `vsce` so this should no longer be a problem.
@eamodio let us know if you still see an issue. Thanks for your understanding.

**Comment by estruyf** [comment]
@isidorn seems the issue on `vsce` got fixed, but there is still some validation issue on the marketplace.

I just tried to publish one of my extensions, and `vsce` mentioned it got published:

![image](https://user-images.githubusercontent.com/2900833/209325857-0c456add-e4bc-4c6b-a82a-ccbef44ec354.png)

A minute later, I got the following email:

![image](https://user-images.githubusercontent.com/2900833/209325929-1f2b8c56-12c7-486d-a5e4-b6e1313b187f.png)

The log file mentions:

```
Error processing 'eliostruyf.vscode-front-matter-beta' SVG reference in file '/extension/README.md'. Your reference to the SVG image ‘https://vsmarketplacebadge.apphb.com/version/eliostruyf.vscode-front-matter.svg’ is not supported.
```

**Comment by PKief** [comment]
@estruyf it seems that SVG images from https://vsmarketplacebadge.apphb.com are not longer working anyways. You've to replace them with this URL https://vsmarketplacebadges.dev/.

See this issue for reference:

https://github.com/cssho/VSMarketplaceBadge/issues/18#issuecomment-1284739771

**Comment by estruyf** [comment]
@PKief I know, but the same happens for the new one.

**Comment by equiman** [comment]
Did you try updating the `vsce` version?

**Comment by equiman** [comment]
Did you try updating the `vsce` version?

**Comment by estruyf** [comment]
@equiman it is on the marketplace, not the tool itself as the latest update indeed fixed publishing. It seems that the marketplace performs a similar check.

**Comment by estruyf** [comment]
It seems the issue was indeed on my end, it was a combination of tests and not using the correct `vsce` dependency. It seems `vsce` became `@vscode/vsce`, so needed to do an update in my GitHub action. Instead of `npx vsce`, now it needs to be `npx @vscode/vsce`.

So the marketplace seems to invalidate the extension only when the old URL is used, when the new one is used. All is fine.
