### ISSUE TITLE
API .d.ts is broken

### ISSUE THREAD

**Issue by tomgr** [microsoft/vscode-vsce#800]
Due to the recent change to api.ts to import IPublishOptions and IPackageOptions from publish and package, the api.d.ts file that is shipped with the npm package needs to import the publish and package files:
```
import { IPublishOptions as _IPublishOptions } from './publish';
import { IPackageOptions } from './package';
```
However, the publish.d.ts and package.d.ts files are not included in the shipped npm package (see https://www.npmjs.com/package/@vscode/vsce/v/2.15.0?activeTab=explore) because they are excluded in the .npmignore file which includes:
```
out/**/*.d.ts
!out/api.d.ts
```
This makes it difficult to use `@vscode/vsce` as a library.

I'm not sure what the intention is now - if you want to only export the required .d.ts files I guess you need to work out all the .d.ts files that are imported from api.d.ts file recursively, but this is a bit fragile. It might be best to remove this exclusion all together now?

**Comment by tomgr** [comment]
Thanks for the quick fix!

**Comment by lszomoru** [comment]
Verified through code review and author feedback.
