### ISSUE TITLE
Reliable way to publish multi-platform extension

### ISSUE THREAD

**Issue by cutsoy** [microsoft/vscode-vsce#802]
We're building an extension based on a LSP written in Rust and compiled for each platform individually. We end up with a folder of `*.vsix` files that we then publish using:

```
npx @vscode/vsce publish --packagePath $(find . -iname *.vsix)
```

Unfortunately, on more than one occasion this has failed due to the marketplace server returning an error code (ranging from random authorization errors to service unavailable to erroneously failing the virus scan).

The problem is that we can't re-run this command because "version already exists".

Unfortunately, `--skip-duplicate` also doesn't really work as expected, since it skips publishing (e.g. Windows) any platform if one platform already exists (e.g. Mac).

Is there any way to do this more reliably? Right now, we're stuck with a version that has binaries for only a few platforms and no way to upload the other platforms, apart from fixing it manually, which is a little annoying because it defeats the purpose of using CI/CD and the server failures happen quite often.

Regards,

Tim

**Comment by joaomoreno** [comment]
Can you reproduce this with 2.16.0? It contains [this change](https://github.com/microsoft/vscode-vsce/commit/ab8770ce20f2690cb8f73491d2666ba885c2b563) which, it not mistaken, should fix the issue.
