### ISSUE TITLE
[Extention Pack] The way to add "A extension on the private server" into "extensionPack/extensionDependencies"

### ISSUE THREAD

**Issue by prozanne** [microsoft/vscode-vsce#805]
**Dear. VS Code team**

Hi, I've been working for publishing some extensions on the private server for my co-workers.
Currently some dependent extensions("B,C and D") are required to install automatically when someone installs "A" extension.

```
FYI,
"A" extension : on the private server.
"B" extension : on the private server.
"C" extension : on the private server.
"D" extension : on the vscode Marketplace.
```

I found a way to add them("B,C and D") as values of "extensionPack/extensionDependencies" to the `package.json` of "A".
https://code.visualstudio.com/api/references/extension-manifest#extension-packs

But only "D" worked as I expected. (When I install "A", only "D" was installed automatically.)
Is there any way to install "B","C" bundled with "A"?
Only "extension ID" should be input for the values of "extensionPack/extensionDependencies"?

`
"Local path or ${privateHostUrl}/B.vsix" are not available instead of "extension ID"?
`

I hope I could find a good way to bundle a specific extension which is located in the private server too...
Thanks in advance.

**Comment by joaomoreno** [comment]
I'm sorry but I don't understand the scenario. We don't official support private servers. What is the error vsce gives you?

**Comment by prozanne** [comment]
Thanks for your reply.
I think I found wrong place to ask this question. It seems not related with "vsce".
But, I have no idea where can I get the answer.
Could you please let me know where this question should be...?

Here is my scenario,
I want to make a bundle extension pack which VS Code supports as "extensionPack/extensionDependencies".

I understand It's official way to make an extension pack.
In the package.json
`"extensionPack": ["vscode-icons-team.vscode-icons", "ms-vscode-remote.remote-wsl"]`

But I want to ask this format is available for my extensions which can not be released on VSCode Marketplace.
In the package.json
`"extensionPack": ["{THE LOCAL PATH OF B EXTENSION}", "{THE LOCAL PATH OF C EXTENSION}"]`

I saw "local path" is also worked when I use cli, not only for "extension ID".
`code --install-extension "local path"` not only for `code --install-extension "extension ID"`

Thanks for your help.

**Comment by joaomoreno** [comment]
No, this won't work unfortunately. The `extensionPack`/`extensionDependencies` properties work only with Markteplace extensions.
