### ISSUE TITLE
The user with identifier 'c0641ee7-6960-4381-8e18-32eb017d71ec' does not exist.

### ISSUE THREAD

**Issue by spgennard** [microsoft/vscode-vsce#810]
Any ideas why this is not working?

```
$ npx vsce publish -i cobol-9.1.11.vsix
 INFO  Publishing 'bitlang.cobol v9.1.11'...
 ERROR  The user with identifier 'c0641ee7-6960-4381-8e18-32eb017d71ec' does not exist.
```

**Comment by spgennard** [comment]
I had to use ```--noVerify`` to get it to work...

**Comment by pythoulon** [comment]
Same here. `vsce --version` = 2.15.0

**Comment by rgrunber** [comment]
I've run into this as well. I've seen this for two different extensions. In both cases, I'm attempting to publish a set of platform specific pre-releases, and the failure doesn't happen at the same spot. Sometimes 3 platform-specific extensions get published before failing on the 4th, other times it can fail on the first one. I was using 2.15.0, but I also tried 2.16.0 and noticed the same problem.

**Comment by CongJyu** [comment]
I also run into this problem when I try to login my developer account, and the identifier is the same as `c0641ee7-6960-4381-8e18-32eb017d71ec`.

Full command line below:

```
% vsce login CongJyu
https://marketplace.visualstudio.com/manage/publishers/
Personal Access Token for publisher 'CongJyu': ****************************************************

ERROR  The Personal Access Token verification has failed. Additional information:

Error: The user with identifier 'c0641ee7-6960-4381-8e18-32eb017d71ec' does not exist.

%
```

I don't have any idea about that.

**Comment by pythoulon** [comment]
> I also run into this problem when I try to login my developer account, and the identifier is the same as `c0641ee7-6960-4381-8e18-32eb017d71ec`.
> 
> Full command line below:
> 
> ```
> % vsce login CongJyu
> https://marketplace.visualstudio.com/manage/publishers/
> Personal Access Token for publisher 'CongJyu': ****************************************************
> 
> ERROR  The Personal Access Token verification has failed. Additional information:
> 
> Error: The user with identifier 'c0641ee7-6960-4381-8e18-32eb017d71ec' does not exist.
> 

Yes, same login problem... It may be related to the "service degradation" on the Marketplace that you mention...

**Comment by anupkmr03** [comment]
There was an issue with Authn/Authz  while communicating to our partner service and hence the issue.
We have now rolled out a fix and the issue seem to be mitigated.
Please let us know if you are still facing the issue.

**Comment by pythoulon** [comment]
Fixed for me. I was able to login and publish again.

**Comment by isidorn** [comment]
Great, thanks for letting us know.
I will go ahead and close this issue. If someone is still seeing this let us know and I can reopen this issue.
