### ISSUE TITLE
Can't publish vscode extension to market and get the message said "ERROR  TF400898: An Internal Error Occurred" always

### ISSUE THREAD

**Issue by KrabsWong** [microsoft/vscode-vsce#811]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 
  - 1.74.3
  - commitId: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
  - Electron: 19.1.8
  - Chromium: 102.0.5005.167
  - Node.js: 16.14.2
  - V8: 10.2.154.15-electron.0
  - OS: Darwin arm64 22.2.0
  - OS Version: macOS 13.1 (22C65)

Steps to Reproduce:

Follow the same step to publish an extension.

1. Direct to the root directory of the target extension.
2. Execute `vsce publish`
3. After the auto compile flow, get the error message.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/12368943/211996061-69f1d21e-cdd1-4cfb-a9c5-d5abdc1ca356.png">

`ERROR  TF400898: An Internal Error Occurred. Activity Id: 657c01c3-07b5-4464-9e5c-7266bab9e867.`

**Comment by estruyf** [comment]
Same on my end.

**Comment by KrabsWong** [comment]
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/12368943/212276307-31187569-c77f-45ed-85af-1acd1825673f.png">

Get the message from https://marketplace.visualstudio.com/, hope it can be fixed soon.

**Comment by mtorp** [comment]
The issue still persists after Microsoft fixed the 'service degradation', but now I'm at least able to publish extensions through the webpage and then later publish updates to those extensions using `vsce`.

If you need to publish an extension for multiple target platforms, just upload the first platform on the webpage and then publish for the remaining platforms using `vsce`.

**Comment by jifrivly** [comment]
I am experiencing the same.
But after publishing the first version through the web interface, CLI is working fine for updations.

**Comment by sandipchitale** [comment]
Same for me.

**Comment by tupizz** [comment]
Same for me

**Comment by anupkmr03** [comment]
@KrabsWong Can you please share your VSIX in which you were facing issues with CLI uploads? You can share your VSIX file on our support email VSMarketplace@microsoft.com.

**Comment by amit-kulkarni-in** [comment]
The above reported issue has been resolved by the marketplace team . Please let us know if you are able to publish extension without any failures, if failures persist please reach out to [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com) with your VSIX file. Apologies for the inconvenience.

**Comment by danielvaughn** [comment]
This is happening again for me, both via the cli as well as the web interface. Neither work.

**Comment by isidorn** [comment]
@danielvaughn  Since it also happens when go through the marketplace UI can you please file a new issue here https://github.com/microsoft/vsmarketplace

Thank you
