### ISSUE TITLE
ERROR: The following files have the same case insensitive path, which isn't supported by the VSIX format

### ISSUE THREAD

**Issue by nikmace** [microsoft/vscode-vsce#812]
We have the following **error** when trying to run `vsce package`:  The following files have the same case insensitive path, which isn't supported by the VSIX format. 

How can we understand **what is the problem here**? Where is that **error coming from**? What is **wrong with the package**?

This package is under `dependencies`. When we package the extension without the aforementioned package, all the `devDependecies` go into the `.vsix` file (??). When we put the aforementioned package inside `devDependencies` it's packaged in vsix but its dependent packages are not installed. 

One more thing to mention is that `vsce` **doesn't work correctly with monorepo**s. You have to ignore all other packages and monorepo files so `vsce package` does not include them in `.vsix`.

Here is the output:

![image](https://user-images.githubusercontent.com/39880364/212284928-16e29f0d-35cd-4ca2-a0c8-72f8764f9888.png)

Here is the package structure:

![image](https://user-images.githubusercontent.com/39880364/212285118-b88d9097-26f1-493d-a8c2-638e174eab3f.png)

**Comment by joaomoreno** [comment]
Are your sources open source? Could you point me to them, so I can repro the issue? The problem is that vsce is seeing duplicate files somehow.
