### ISSUE TITLE
How can I build versions of my plugin based on feature flags

### ISSUE THREAD

**Issue by avnerbarr** [microsoft/vscode-vsce#818]
I'm using webpack and want to implement a feature flag per these [intructions](https://webpack.js.org/plugins/define-plugin/#feature-flags).

In my `webpack.config` file I've added a simple check:

```
module.exports = (env) => {
  console.log("env.SANDBOX = '", env.SANDBOX, "'");
  if (env.SANDBOX) { ... } // do something here
};
```

I can verify that this value is being passed along

```
$ webpack --env SANDBOX
... logs  ...
env.SANDBOX = ' true ' <<<<. THE ECHO IS CORRECT
... more logs ...
```

In my `package.json` I've added a new script attempting to handle this case and I am not sure how to make it work:

```
// I believe that I need to customize the pre-publish command and not sure how to achieve that:
"vscode:prepublish": "yarn --frozen-lockfile && yarn clear-out && webpack --mode production", 
// tried like this
"vsce:package:sandbox": "export SANDBOX=true; vsce package",
// and like this
"vsce:package:sandbox": "SANDBOX=true vsce package",

// and tried to access the variable from the pre-publish in various ways (one example):
"vscode:prepublish": "echo $SANDBOX && yarn --frozen-lockfile && yarn clear-out && webpack --mode production", 

// or like this (modify the prepublish name to match...)?
"vscode:prepublish:sandbox": "yarn --frozen-lockfile && yarn clear-out && webpack --mode production --env SANDBOX",

```

**Comment by joaomoreno** [comment]
We have a great extension developer community over on [GitHub discussions](https://github.com/microsoft/vscode-discussions/discussions) and [Slack](https://aka.ms/vscode-dev-community) where extension authors help each other. This is a great place for you to ask questions and find support.

Happy Coding!
