### ISSUE TITLE
Support the galleryFlags properties so that an extension can be marked as Preview

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-vsce#82]
The package.json should support the property galleryFlags in the package.json so that an extension can be defines as `Preview`

```json
"galleryFlags": [
    "Preview",
    "Public"
],
```

This should then be translated into extension.vsixmanifest as:

```xml
“<GalleryFlags>Preview Public</GalleryFlags>” 
```

This results in the following rendering of the extension:

![image](https://cloud.githubusercontent.com/assets/172399/13776217/4d9ae796-eaa9-11e5-96f8-43395de5e3d4.png)

**Comment by SrTobi** [comment]
:+1:

**Comment by joaomoreno** [comment]
@egamma How about we keep it simpler and just parse whether you have a `preview` keyword (in the already existing `keywords` list) and map that to the gallery flags?

**Comment by egamma** [comment]
@joaomoreno I like simplicity. 

One drawback I can think of is that whenever the MarketPlace adds a new gallery flag, we have to change the vsce code to map keywords to gallery flags.

**Comment by joaomoreno** [comment]
Should be OK, I don't expect them to have many flags on top of the already existing *keywords* and *categories*.

**Comment by joaomoreno** [comment]
Went instead with a `"preview"` boolean flag. So this can generate a preview extension:

```json
{
    "name": "extension",
    "version": "0.0.1",
    "publisher": "johndoe",
    "engines": { "vscode": "^0.10.10" },
    "preview": true
}
```

I will also update the docs.
