### ISSUE TITLE
vsce package is appending `/**` to negated filenames taken from .vscodeignore 

### ISSUE THREAD

**Issue by pflannery** [microsoft/vscode-vsce#823]
vsce: v2.15.0

Example negated file issue : 
`!README.md` results in `!README.md/**` which then scans all sub directories and includes all `README.md` files in the package.

A workaround I found was to include a star after the negated filename `!README.md*` [workaround example](https://gitlab.com/versionlens/vscode-versionlens/-/blob/master/.vscodeignore)

[This is the line](https://github.com/microsoft/vscode-vsce/blob/main/src/package.ts#L1574) where it auto appends `/**` to single file names

**Comment by joaomoreno** [comment]
> !README.md results in !README.md/** which then scans all sub directories and includes all README.md files in the package.

That's odd. Can you show me a sample in which the bug reproduces?

**Comment by colin-grant-work** [comment]
FWIW, the link in the original post points to the blob of the `main` branch, which has changed in the meantime. I believe the location (with a permalink to current `main`) is [here](https://github.com/microsoft/vscode-vsce/blob/9478dbd11ea2e7adb23ec72923e889c7bb215263/src/package.ts#L1568).

**Comment by joaomoreno** [comment]
@colin-grant-work Can you reproduce this?

**Comment by colin-grant-work** [comment]
@joaomoreno, I have not reproduced this - I was looking around at other bugs and just noticed the code had moved around since this report.
