### ISSUE TITLE
Unable to use .cjs file as entrypoint

### ISSUE THREAD

**Issue by lucyydotp** [microsoft/vscode-vsce#824]
My extension is written using ES6 modules and as a result has `{"type": "module"}` set in package.json, which is translated to CJS at build time through esbuild. VSCode is picking up on the type:module and attempting to treat my CJS output file as ESM. To work around this, I save the bundle from esbuild with a `.cjs` extension, but that fails because vsce attempts to append `.js` to the end:
> Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':
>  extension/lib/main.cjs.js

**Comment by borkdude** [comment]
Running into the same problem

**Comment by lucyydotp** [comment]
> Running into the same problem

I've opened a PR, which I've currently got published to https://www.npmjs.com/package/vsce-cjs if it's helpful

**Comment by borkdude** [comment]
Thanks!

**Comment by borkdude** [comment]
@lucyydotp I found another workaround: put a `package.json` with `"type": "module"` in a subdirectory with the ES6 modules and then use a `.js` as CJS entrypoint in the parent directory without `"type": "module"`.
