### ISSUE TITLE
Can't package language extension

### ISSUE THREAD

**Issue by blakegearin** [microsoft/vscode-vsce#826]
```bash
$ vsce package
 ERROR  Manifest needs either a 'main' or 'browser' property, given it has a 'activationEvents' property.
```

My `package.json` doesn't have `activationEvents` as it's a language extension generated with [Yo Code](https://github.com/microsoft/vscode-generator-code#yo-code---extension-and-customization-generator)

Looks like the recent #809 is causing this to occur because of new implicit `activationEvents` checking (https://github.com/microsoft/vscode-vsce/blob/main/src/package.ts#L1214-L1244)

Unless I'm mistaken, a `main` or `browser` property isn't needed for this type of extension

Could address with some logic like this:

```ts
const hasLanguages = manifest.contributes?.languages;
const hasImplicitActivationEvents =
		manifest.contributes?.commands ||
		manifest.contributes?.authentication ||
		manifest.contributes?.customEditors ||
		manifest.contributes?.views;
...
if (
	!(hasLanguages && !hasActivationEvents) &&
	(
		hasActivationEvents || 
		(
			(engineVersion === '*' || semver.satisfies(parsedEngineVersion, '>=1.74', { includePrerelease: true })) &&
			hasImplicitActivationEvents
		)
	)
) {
	if (!hasMain && !hasBrowser) {
		throw new Error(
			"Manifest needs either a 'main' or 'browser' property, given it has a 'activationEvents' property."
		);
	}
}
```

**Comment by blakegearin** [comment]
Confirmed that downgrading to `2.16.0` allows `vsce package` to succeed.

**Comment by samubarb** [comment]
Hi, I have the same issue with `v2.17.0` and a language extension. Downgrading `vsce` to `v2.16.0` solved the publication issue also for me, thanks @blakegearin

It seems like also pure language contributions have at least one implicit `activationEvents` which is `onLanguage`. It may not play nice with the entrypoint (`"main"`/`"browser"`) constraint mechanism.

**Comment by ulugbekna** [comment]
For verification, I did: 

- I created a language extension with `yo code` -- the manifest doesn't have `activationEvents` 
- running `node ../vscode-vsce/vsce package` packages the extension successfully
