### ISSUE TITLE
publish fails for archives created with nix

### ISSUE THREAD

**Issue by hall** [microsoft/vscode-vsce#827]
Files created during a nix build are given [an `mtime` of 1s after the epoch](https://github.com/NixOS/nix/blob/b574c70ccbc0c22fa3c5df12c6246a10eff1a5bf/src/libstore/local-store.cc#L542) (for reproducibility); this appears to apply [only to files created from memory](https://github.com/microsoft/vscode-vsce/blob/2f376f35f2065c597e136b3369f1025518116d8c/src/package.ts#L1682) by `vsce` (e.g., `LICENSE.txt`, `package.json`, and the path to the `icon` file).

```
❯ unzip -l ~/draw-0.1.20.vsix
Archive:  /home/bryton/draw-0.1.20.vsix
  Length      Date    Time    Name
---------  ---------- -----   ----
     2528  02-04-2023 21:07   extension.vsixmanifest
      462  02-04-2023 21:07   [Content_Types].xml
     2915  02-04-2023 21:07   extension/CHANGELOG.md
    41063  01-01-2098 00:00   extension/docs/images/icon.png
    10888  01-01-2098 00:00   extension/LICENSE.txt
  1532147  02-04-2023 21:07   extension/main.js
     3878  01-01-2098 00:00   extension/package.json
     3098  02-04-2023 21:07   extension/README.md
---------                     -------
  1596979                     8 files
```

However, there is [a bug in the upstream yazl dependency](https://github.com/thejoshwolfe/yazl/issues/70) which results in an `mtime` of `01-01-2098` and therefore `vsce publish` fails with the following error (same as #797):

```
 ERROR  One or more entries have a modified date in the future.
```

One workaround is to `unzip`, `touch`, then re-`zip` the `vsix` file ([as I've done here](https://github.com/hall/draw/commit/2e16c4cde8d9756e1d15eb2aab9465ce208c840f)) (though I'm not certain why this is being enforced; it's not done on open-vsx.org, fwiw).

It appears `yazl` has been abandoned so I don't expect a fix to land there. It is possible to pass `mtime` as an option to `addBuffer` which _may_ be acceptable in this case if these files are always expected to have an `mtime` which matches something like `new Date()`.

Happy to test any possible solutions which the folks here deem acceptable. Also happy to close this and stick with the workaround as I'm fairly certain this effects a very small portion of your users.

**Comment by joaomoreno** [comment]
Interesting. I am curious... `[Content_Types].xml` is for sure a buffer backed file which ends up in `addBuffer`... why is that timestamp good?

**Comment by thejoshwolfe** [comment]
yazl 3.3.0 has been published which fixes the out-of-bounds date wraparound bug, and adds support for Info-ZIP style unix timestamps. The unix epoch should be possible to encode in yazl now.
