### ISSUE TITLE
Populate Keywords dynamically

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-vsce#83]
Now that keywords (tags) search are part of the marketplace UX (see items details page on the right or type "tags:<some tag>" into the search bar), we need to help extension publishers get their keywords into the manifest file. 

One idea is to scrape `activationEvents` and the `onLanguage` key. We could use the value (i.e. `python`) to dynamically add language specific keywords. 

- [x] if we detect any themes, we tag it with `theme`
- [x] if we detect any snippets, we tag it with `snippet`
- [x] if we detect any language, we tag it with `${ language }`
- [x] if we detect any `onLanguage` activation event, we tag it with `${ language }`

**Comment by joaomoreno** [comment]
@waderyan these shouldn't go toward the 5 limit, correct?

**Comment by waderyan** [comment]
Yes. The user should have 5 of their own keywords and then we auto generate as many as we want.

**Comment by joaomoreno** [comment]
Alright, what do you think about these:

- if we detect any themes, we tag it with `theme`
- if we detect any snippets, we tag it with `snippet`
- if we detect any `onLanguage` activation event, we tag it with `${ language }`

Think of any other?

**Comment by waderyan** [comment]
That looks good to me :) 

I'm going to work with the MP and see about getting something done for all the extensions already in the MP. I'm thinking we can run a quick script over the database and populate it.
