### ISSUE TITLE
vsce package with npm ERR

### ISSUE THREAD

**Issue by baikaishui01** [microsoft/vscode-vsce#831]
![image](https://user-images.githubusercontent.com/48601669/218623779-eec400e3-c93d-44b3-8891-016277d012b2.png)
versions: 
  vsce: 2.17.0
  npm: 9.2.0
  node: v14.19.3

it is show this error when i run  command `vsce package`,why?

**Comment by joaomoreno** [comment]
https://stackoverflow.com/questions/71152952/what-does-npm-err-code-elsproblems-mean
