### ISSUE TITLE
Error parsing JSON manifest translations file

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode-vsce#833]
Hi,

I have faced a small issue while packaging my extension with _translations_. The error was fairly easy to find, but it was a surprise  since no error occurred while developing (debugging) the extension.

My `package.nls.json` file had an extra comma, at the end of the file:

```json
{
    . . . 
    "pascal.commands.whatsNewContextMenu.title": "What's New",
    "pascal.commands.installDelphiThemes.title": "Pascal: Install Delphi Themes", // <- this one
}
```

I totally understand the JSON is not well formed, but I think it should be a consistent behavior between the extension development/debugging and the packaging process. Maybe the same validation should be made while debugging.

Thank you

**Comment by connor4312** [comment]
@joaomoreno it looks like vsce could use a publish to verify this 🙂
