### ISSUE TITLE
[Question] vsce prepublish before version bump ?

### ISSUE THREAD

**Issue by wenytang-ms** [microsoft/vscode-vsce#834]
Hi team, you build a nice tool for VS Code.
But I get some confusion in the process of using it recently.

`vsce package 2.0.1` will get a VSIX with version 2.0.1, although it is possible that the version number in package.json was 2.0.0.
The vscode-vsce help to do [**versionBump**](https://github.com/microsoft/vscode-vsce/blob/5ae00f5fa9fb8542d6b127da515b791b9e609eaa/src/package.ts#L1778) after **prepublish** which executes  "vscode:prepublish" script.

Take our project as an example, the package.json file is referenced in the source code, we need to get the package's name, version to collect BI data. so the package will run prepublish to build or compile the source code,  so the version of package.json which is 2.0.0 will be hardcoded.
Then vsce will leverage the compiled result to generate visx.
Finally, the verison of visx is 2.0.1, however, the code gets the version number 2.0.0 at runtime.

So I would like to know what is your consideration for this design. 
Is there any solution to resolve my problem?

**Comment by wenytang-ms** [comment]
I have also find your commit history, the original design is do versionBump before prepublish in this [commit](https://github.com/microsoft/vscode-vsce/commit/535fa75a9d33ad28a342ad68a7306d78ad889f81)
But you have changed the logic because of this [issue](https://github.com/microsoft/vscode-vsce/issues/187)
But are there other options for this issue？For example, adding backup logic？

**Comment by joaomoreno** [comment]
Maybe we need a new lifecycle script?

1. Pre-publish
2. Version bump
3. ??? <- here
4. Publish

Would this help?

**Comment by wenytang-ms** [comment]
What about add the backup logic?
Just like Lerna, Lerna will backup package.json to package.json.lerna_backup while running `lerna bootstrap` ?

**Comment by joaomoreno** [comment]
The problem with the backup solution is that `npm version` might also create a commit and might also create a tag. We'd need to revert those things as well, this isn't trivial.

**Comment by wenytang-ms** [comment]
Well, it's really tricky.
But I insist that the version numbers need to be aligned during the two stages.
Maybe you guys need to think about it, I can only handle it with some workaround at the moment.

**Comment by joaomoreno** [comment]
Given you have a functional workaround at the moment, we'll close this request for now. Thanks!
