### ISSUE TITLE
Packaging should lint manifest files with vscode's extension linter and show warnings & errors

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode-vsce#843]
Currently, we have an extension linter, which shows warnings & errors when an extension manifest file (package.json) is open. But an extension author _should open_ the manifest file to see those diagnostics. I think it's worth showing the warnings & errors when running `vsce package` 

This would notify extension authors about their manifest file problems & encourage to fix them. 

(this's problematic to implement because it would require the linter to be a standalone npm package, but the linter has dependenices on vscode core)

**Comment by joaomoreno** [comment]
Love this idea.

**Comment by benibenj** [comment]
Closing as I do not see this happen any time soon.
