### ISSUE TITLE
Unpublish specific version on VS Marketplace

### ISSUE THREAD

**Issue by amit-kulkarni-in** [microsoft/vscode-vsce#846]
VS Marketplace allows extension authors to upload the extensions through CLI (vsce command) and Gallery UI in the publisher manage page. Currently in both the scenarios we support deleting at the extension level but not at the extension version level. This has been one of the top asks from the extension author community in marketplace [github](https://github.com/microsoft/vsmarketplace/issues/235)

Below are usescases for deleting specific version :
**Use case 1**:  An author noticed the latest version of their extension includes a serious bug but cannot find its cause soon. Currently, end users download the broken version until the author fix the bug and publish a new version. If the feature described above is implemented, the author can unpublish the latest one soon and set about bug fix without hurrying.

**Use case 2**: We are doing beta releases, and we would like to unpublish previous beta versions that are not usable anymore anyway.

**Use case 3**: Extension author accidentally uploads the VSIX file with secrets. Wants to delete the specific version which has secrets.

**Current Implementation :**
Currently publisher doesn’t have an option to delete the specific version they have to reach out to  [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com) support alias to get the version deleted.

Some publishers have accidently used `vsce unpublish <extension name> <version>` thinking it would delete the specific version but have accidently deleted the complete extension ([Github issue](https://github.com/microsoft/vscode-vsce/issues/782) ) 

**Recommendation implementation :**

New CLI :
Due to the confusion and accidental delete possibilities of `vsce unpublish` command, can we have new CLI which allows only version to be deleted.
`vsce delete <extension name> -version <version number>`
Note that it is mandatory to provide version number.
@isidorn @prashantvc

**Comment by isidorn** [comment]
@amit-kulkarni-in thanks for opening this feature request and for nicely documenting it.

@joaomoreno it looks like there are Marketplace API to unpublish a specific version and we should consider surfacing this in `vsce` - since extensions authors really want this. We can discuss in more detail in our next sync.

**Comment by tooltitude-support** [comment]
It looks like it's not even in API, it's in officially documented and published API of Azure, not something internal to Microsoft: https://learn.microsoft.com/en-us/javascript/api/azure-devops-extension-api/galleryrestclient#azure-devops-extension-api-galleryrestclient-deleteextension

**Comment by tooltitude-support** [comment]
It looks like it's not even in API, it's in officially documented and published API of Azure Devlops, not something internal to Microsoft: https://learn.microsoft.com/en-us/javascript/api/azure-devops-extension-api/galleryrestclient#azure-devops-extension-api-galleryrestclient-deleteextension

cc @joaomoreno

**Comment by tooltitude-support** [comment]
P.S. I did add a new command to vsce code like other commands work. On invocation the error was:
```
  statusCode: 400,
  result: { count: 1, value: { Message: 'The request is invalid.' } },
```

**Comment by isidorn** [comment]
@tooltitude-support I suggest to open a new issue, so we do not loose your investigation.

**Comment by gee4vee** [comment]
Why is this not planned? Seems like a pretty important feature.

**Comment by voltechs** [comment]
Baffling. Microsoft continues to be the modern-day embodiment of [Bizarro](https://en.wikipedia.org/wiki/Bizarro). In what world is yanking a published extension version not table stakes for good software stewardship? Then again, I suppose we're the fools for thinking Microsoft cares about this concept. The concept likely doesn't even cross the veil of consciousness for them. Oh well. I guess I'll unpublished the entire extension and then republish the good versions.

<img width="594" height="74" alt="Image" src="https://github.com/user-attachments/assets/fa9c56ef-2942-4a57-b999-506fb584cd68" />

**Comment by FFengIll** [comment]
they think developer can unpublish all and do new publish...
