### ISSUE TITLE
document the meaning of `vsce show` output

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode-vsce#847]
`vsce show` provides some statistics about an extension.
That's retrieved from the undocumented marketplace api.

I was trying to guess based on the names (install, averagerating, ratingcount, trendingdaily/monthly/weekly, updateCount, weigthedRating, downloadCount), but as watching how they change over time, I am getting less sure about how to interpret those numbers. Are they computed with sliding window? Approximation? etc.

Please provide the meaning of each number and how they are measured.

**Comment by joaomoreno** [comment]
Better yet, why don't you contribute a PR which adds units to those alues?

**Comment by hyangah** [comment]
@joaomoreno I have no idea what these numbers are and how they are measured, and that's the motivation of filing this issue.  My understanding is that it's a private, preview API without documentation. So, only internal people have sufficient knowledge.

**Comment by joaomoreno** [comment]
Here are the units:

```
Statistics:
  install          39229.00 installs
  averagerating    4.82 out of 5 stars
  ratingcount      11.00 users have rated the extension
  trendingdaily    0.00 ???
  trendingmonthly  1.44 ???
  trendingweekly   0.32 ???
  updateCount      45322.00 updates
  weightedRating   4.62 ???
  downloadCount    156.00 ???
```

@isidorn Can you help fill the rest of the `???`, I am actually unsure of these.

**Comment by isidorn** [comment]
I do not know. I have pinged MP folk, maybe they will be able to help.

**Comment by bandantonio** [comment]
I would like to contribute a PR to address this issue. @isidorn do you have any updates on that?

> I do not know. I have pinged MP folk, maybe they will be able to help.

**Comment by isidorn** [comment]
No updates. I suggest to remove those stats from the output. They are just confusing until we get clarity here.

**Comment by tooltitude-support** [comment]
Easy way to get install count, and rating is very useful. Please, don't remove them.
