### ISSUE TITLE
vsce publish fails with `EISDIR` when run on build server

### ISSUE THREAD

**Issue by steven-r** [microsoft/vscode-vsce#849]
I try to publish a vsix package to the marketplace.

When running this as a github action, the publish command fails as `EISDIR` (the file is existing):

```
> Run npx vsce publish --pre-release --no-dependencies --packagePath $(find . -iname *.vsix)
  npx vsce publish --pre-release --no-dependencies --packagePath $(find . -iname *.vsix)
  shell: /usr/bin/bash -e {0}
  env:
    VSCE_PAT: ***
Error: EISDIR: illegal operation on a directory, read
Error: Process completed with exit code 1.
```

If I publish the package locally, the packaged file (downloaded as an artifact), succeeds:

```
writer-name-handler % vsce publish --pre-release --no-dependencies --skip-duplicate --packagePath ../../Downloads/writer-name-handler-2.0.2.vsix
 INFO  Publishing 'sreindl.writer-name-handler v2.0.2'...
 DONE  Version 2.0.2 is already published. Skipping publish.
```

Extract from package.json:

```
    "devDependencies": {
    ...
        "@vscode/vsce": "^2.18.0",
    ...
```

**Comment by joaomoreno** [comment]
What's the actual result of `$(find . -iname *.vsix)` in the CI?

**Comment by joaomoreno** [comment]
Is `./writer-name-handler-2.0.2.vsix` _by any weird reason_ a directory (instead of a file)?

**Comment by steven-r** [comment]
I can download the file (therefore it's not a dir) but I will try your approach (in github there should by only one vsix file).

**Comment by joaomoreno** [comment]
Let me know if that helps.

**Comment by steven-r** [comment]
After some more research and a couple of debug statements and the result was PEBKAC (problem exists between keyboard and chair): I named the folder the same as the filename due to a misunderstanding of the artefacts handling in GitHub.

Therefore, the find command returned a file and a folder. 

I fixed this now and everything works as expected.

Sorry for raising this.

**Comment by joaomoreno** [comment]
I guess we found the _weird reason_ 😄
