### ISSUE TITLE
Instructions for publishing an extension don't work

### ISSUE THREAD

**Issue by kstenerud** [microsoft/vscode-vsce#851]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Doesn't matter
- OS Version: Debian bullseye

Steps to Reproduce:

1. Install vsce per instructions at https://code.visualstudio.com/api/working-with-extensions/publishing-extension
2. `vsce login <publisher name>`
3. Type in your token

Result:

```
$ vsce login kstenerud
https://marketplace.visualstudio.com/manage/publishers/
Personal Access Token for publisher 'kstenerud': ****************************************************

 ERROR  The Personal Access Token verification has failed. Additional information:

Error: Access Denied: d5bbde41-7360-68aa-a18d-1aedc36a400e needs the following permission(s) on the resource /kstenerud to perform this action: View user permissions on a resource
```

This happens even if I give the token full access.

**Comment by joaomoreno** [comment]
@isidorn Do we need different steps? Can you follow up with the MP?

**Comment by isidorn** [comment]
@kstenerud can you reproduce the issue if you give the token explicit right to the marketplace. So set Scopes to Custom defined and choose the Marketplace > Manage scope. You will have to scroll down in the UI to find this.

I am asking because I hit a similar issue last week, and this fixed it for me.
Let me know if this is indeed the case, and we can clarify this in docs.

**Comment by kstenerud** [comment]
Yup, that's the first thing I tried (basically following the instructions). I only tried giving all permissions after that didn't work.

**Comment by nicu-chiciuc** [comment]
It seems that I have the same issue. I updated this extension on March 26: https://marketplace.visualstudio.com/items?itemName=nicu.automatic-jsonc

But now I can't seem to publish nor login anymore. I created a new organization in Azure but I can't login even into the new organization.

I don't remember having to even create an Azure organization when I first created the extension. 

It's very confusing.

**Comment by bandantonio** [comment]
@kstenerud The instructions were updated, please try following them again and let us know about the results. Thank you.

**Comment by clarkttfu** [comment]
Use the Publisher ID, lower case string inside the round brackets, neither "User Id" (UUID prompt when you hover over the email address) nor the Publisher Name.

<img width="1234" alt="image" src="https://github.com/microsoft/vscode-vsce/assets/385536/feeec5ca-4551-4456-8e52-035bfc2f265c">
