### ISSUE TITLE
vsce package skips files with no file extension

### ISSUE THREAD

**Issue by lacomc** [microsoft/vscode-vsce#853]
**UPDATED INFO IN COMMENTS**

I have a build where we're trying to create a vsix package that requires some non-code files to be included in the package for later reference. These files have no file extension. When I locally run `yarn vsce package`, the files are included, but when it's run via an AzureDevOps CI build, the files are not included. Additionally, when I try running `yarn vsce ls` and then `yarn vsce package` in the same CI build, the files are listed by the ls command but still not included in the package. I've also tried adding `!<filename>` to our .vscodeignore file, and this still doesn't cause them to be packaged in the CI build.

How can I get the CI build to pick up these files?

**Comment by lacomc** [comment]
After a bit more testing, I can see that the files are not skipped when they have file extensions. Renaming one of the files to <original name>.txt caused the file to be picked up and included in the vsix. 

The issue still does not reproduce locally, only in my CI build.

**Comment by joaomoreno** [comment]
Hi @lacomc, can you point me to your CI? Feel free to reach out in Teams.
