### ISSUE TITLE
Create GitHub releases whenever releasing vsce

### ISSUE THREAD

**Issue by Marcono1234** [microsoft/vscode-vsce#862]
Hello,
the [GitHub releases](https://github.com/microsoft/vscode-vsce/releases) of this project are outdated; the latest entry is for version 2.15.0, but the latest version is currently 2.19.0.

Is this intentional? Is there some other changelog / release notes document I overlooked?

As mentioned in previous similar issues a changelog makes it easier for users to understand what changed between the versions; checking the commits can be tedious especially if commits might have no user facing effect, or if commits messages are unclear to users.

It looks like previously creation of the GitHub releases was automated (see #541 and #710), but that was dropped by #791.

**Comment by joaomoreno** [comment]
We've moved away from semantic version which was creating these releases automatically. We need to figure out how to proceed from here.

**Comment by seanpoulter-foci** [comment]
Can we help @joaomoreno? I'd be happy to talk through options. If I understand this correctly:

* Releases are no longer created, just tagged.
* There is no changelog published anywhere.

This makes it hard for consumers to know when features are added, or when to upgarde. For example, I had to review the diff to spot we've added a flag since 2.19.0.

**Comment by joaomoreno** [comment]
This is my fault. I should do better here at updating the GH release whenever we put a new build out. Will make sure this is done from now on.

**Comment by ssbarnea** [comment]
@joaomoreno I guess that ticket was marked as completed too soon ;)

Releases are being made and still not updated on github, is not fun not to know what is released. No changelog and having to read the git changelog is not fun at all.

**Comment by benibenj** [comment]
We are creating github releases again starting from todays update
