### ISSUE TITLE
xml2js dependency vulnerability; maintainer please run `npm publish`

### ISSUE THREAD

**Issue by dvtate** [microsoft/vscode-vsce#865]
Please update the package to fix this dependency warning
![image](https://github.com/microsoft/vscode-vsce/assets/15305612/53e9764c-2a87-4937-84a0-d022a4db527a)

**Comment by Sven-Seyfert** [comment]
Just as a hint:
In TAG v2.19.0 it's already fixed (package.json is adjusted). I guess we just wait for a new release then the vulnerability issue is fixed 🤞 . Thanks for the effort.

Best regards
Sven

**Comment by AKurkina** [comment]
Also waiting for new release to fix my problem with dependency warning

**Comment by dvtate** [comment]
CC. @joaomoreno @sandy081

**Comment by AKurkina** [comment]
@Sven-Seyfert could you please inform us about new release dates?

**Comment by Sven-Seyfert** [comment]
> @Sven-Seyfert could you please inform us about new release dates?

Funny @AKurkina, I am not a Microsoft developer or a maintainer of this repository (project) 😅 . I just had a look into the [newer TAG versions](https://github.com/microsoft/vscode-vsce/compare/v2.18.0...v2.19.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R58) of this repo. In other words, I also wait for a official statement of the next planned release. This would be nice and helpful 🤝 .

**Comment by dvtate** [comment]
It seems they moved the package. Install `@vscode/vsce`
![image](https://github.com/microsoft/vscode-vsce/assets/15305612/1556cb21-6e8a-42c1-8ecc-f9155b763696)

**Comment by dvtate** [comment]
It seems they moved the package. Install `@vscode/vsce`
![image](https://github.com/microsoft/vscode-vsce/assets/15305612/1556cb21-6e8a-42c1-8ecc-f9155b763696)

**Comment by Sven-Seyfert** [comment]
Thank you for mention it @dvtate , this gives me the newer version 2.19.0 inluding the fix 👍 . I am still wondering why there is no newer release? Anyway, bye.
