### ISSUE TITLE
LICENSE.txt is actually not detected as license

### ISSUE THREAD

**Issue by serkonda7** [microsoft/vscode-vsce#866]
With vsce 2.19.0

1. Clone https://github.com/tiabeast/vscode-bait
2. `npm install`
3. `npm run package`

See this as result. However a `LICENSE.txt` is present
![image](https://github.com/microsoft/vscode-vsce/assets/40118727/7ffea517-a4c2-42eb-b2ce-da07b57fe1d5)

**Comment by joaomoreno** [comment]
You're ignoring it: https://github.com/tiabeast/vscode-bait/blob/83b2e0d31110ce9616f0d100612905444f33a7f6/.vscodeignore#LL1C18-L1C18

**Comment by serkonda7** [comment]
Oh,  my bad. Thank you very much for pointing this out
