### ISSUE TITLE
publish option --skip-duplicate doesn't consider target platforms

### ISSUE THREAD

**Issue by mbehr1** [microsoft/vscode-vsce#868]
If I want to release for multiple target platforms but use skipDuplicate to be able to rerun e.g. in case the marketplace had a timeout during release for some targets this fails after the first version due to:

https://github.com/microsoft/vscode-vsce/blob/c2e71d5bcee680b31d009cf17423d4fb64c1883c/src/publish.ts#L179

I think this line needs a similar and condition like ```sameVersion.some(v => v.targetPlatform === options.target)```.

Currently with skipDuplicate only one target platform will be released which is imho wrong.

**Comment by drewbrokke** [comment]
@mbehr1 I'll give this one a shot. I ran into the same issue today.

**Comment by drewbrokke** [comment]
@joaomoreno is there a test case that will also need updating with this one?

**Comment by roblourens** [comment]
@joaomoreno should we build from source to verify or do you want to publish a beta?

**Comment by joaomoreno** [comment]
Sorry about that, just published v2.20.0.
