### ISSUE TITLE
Vsce package does not include nodes after packaging_ The. bin directory node_modules caused an error. How should I include it in the package?

### ISSUE THREAD

**Issue by tanyo520** [microsoft/vscode-vsce#869]
Vsce package does not include nodes after packaging_ The. bin directory under modules caused an error. How should I include it in the package?

**Comment by tanyo520** [comment]
.vscodeignore  
!node_modules/.bin/**

Adding it doesn't seem to work either

**Comment by joaomoreno** [comment]
Did you resolve this issue?
