### ISSUE TITLE
vsce package - Error: Command failed: node ./node_modules/vscode/bin/compile

### ISSUE THREAD

**Issue by stanislavromanov** [Microsoft/vscode-vsce#87]
I'm trying to package the vsce on my build and cannot do it because of this error. It works fine on my local OSX machine. I tried to install `vscode` as global but it didn't change anything.

The simple error is `Error: Command failed: node ./node_modules/vscode/bin/compile`

This is what actually happens under the hood:
```
src/cs-preview/coffeeScriptPreview.ts(3,25): error TS2307: Cannot find module 'vscode'.
src/cs-preview/coffeeScriptPreview.ts(4,96): error TS2307: Cannot find module 'vscode'.
src/cs-preview/coffeeScriptPreviewContentProvider.ts(3,25): error TS2307: Cannot find module 'vscode'.
src/cs-preview/coffeeScriptPreviewContentProvider.ts(5,83): error TS2307: Cannot find module 'vscode'.
src/vscode/windowService.ts(3,25): error TS2307: Cannot find module 'vscode'.
src/vscode/windowService.ts(4,104): error TS2307: Cannot find module 'vscode'.
src/vscode/workspaceService.ts(3,25): error TS2307: Cannot find module 'vscode'.
src/vscode/workspaceService.ts(4,107): error TS2307: Cannot find module 'vscode'.
src/extension.ts(3,25): error TS2307: Cannot find module 'vscode'.
src/extension.ts(4,55): error TS2307: Cannot find module 'vscode'.
test/coffeeScriptPreviewContentProvider.test.ts(4,25): error TS2307: Cannot find module 'vscode'.
test/coffeeScriptPreviewContentProvider.test.ts(9,103): error TS2307: Cannot find module 'vscode'.
test/coffeescript-preview.test.ts(4,25): error TS2307: Cannot find module 'vscode'.
test/coffeescript-preview.test.ts(9,103): error TS2307: Cannot find module 'vscode'.
```

.gitlab-ci-yml
```
image: ubuntu:16.04

before_script:
  - apt-get update && apt-get -y upgrade
  - apt-get -y install xvfb curl build-essential
  - export DISPLAY=:99
  - Xvfb :99 -ac &
  - sleep 3
  - curl -sL https://deb.nodesource.com/setup_5.x | bash -
  - apt-get -y install nodejs
  - npm update -g
  - npm install vsce -g
  - npm install
  - npm ls -g --depth=0
  - npm ls --depth=0

test:
  script: vsce package
```

Here are the logs: https://gitlab.com/stanislavromanov/vscode-icedcoffeescript-preview/builds/1254271

**Comment by joaomoreno** [comment]
Are your sources public in some repo? Can I take a look?

**Comment by stanislavromanov** [comment]
@joaomoreno  Yea, of course. https://gitlab.com/stanislavromanov/vscode-icedcoffeescript-preview

**Comment by joaomoreno** [comment]
@bpasero Any hints? Seems to be related to the `vscode` module.

**Comment by bpasero** [comment]
@stanislavromanov your extension works fine for me when I run `npm run compile` from the command line after checking it out and running `npm install`. Are you saying it fails for you there already?

**Comment by stanislavromanov** [comment]
@bpasero Yea it works fine on my local machine. However fails on the ci integration with fresh ubuntu install. I wonder if it's something related to the vsce that's why I also posted the build steps

**Comment by stanislavromanov** [comment]
Anyway I just registered runner on my own server so the builds now pass.
