### ISSUE TITLE
The `vsce` tool on package or publish should be validating semver validity

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-vsce#871]
I know that https://github.com/microsoft/vsmarketplace/issues/50 refers to the marketplace supporting full SemVer, but this issue is about ensuring that the toolchain used to package/publish match the expected Marketplace.  Today you can have 'proper' semver in your versioning (1.0.2-beta.g893fd) and vsce will gladly package and attempt to publish.  In fact there is a `semver.valid()` check (https://github.com/Microsoft/vscode-vsce/blob/main/src/validation.ts#L35) that does this.  But knowing that the marketplace will not support this, it is giving false hopes that all the pipeline is valid until the very last step.

Until/unless Marketplace supports full semver, then `vsce` should change to ensure that versions being used can _**actually**_ get published.  Today, it is not helping that validity.

There are a few issues from 3-5 years ago on this, but the problem still remains...and regardless of the mismatch of support of the Marketplace, the `vsce` tool is incorrectly allowing a package and publish attempt all the way until the end knowing that it is NOT going to be successful.  The `semver.valid()` check should be modified to look for the unsupported semver aspects and block.

**Comment by seanpoulter** [comment]
Would you welcome a PR to change the validation @joaomoreno?

The warning in the marketplace says the version must be on to four numbers from 0 to 2,147,483,647. It does not allow a tag like `-beta.g893fd` mentioned above.

**Comment by sandy081** [comment]
Sure, PR is welcome. But, we should still allow packaging the extension with complete semver version. Because there could be authors packaging the VSIX and sharing it with others and using the full semver version. This can be supported by a flag but the question is what should be the default.

**Comment by benibenj** [comment]
@timheuer packaging with pre-release versioning is still allowed and used by some people so we don't want to take that away, but we can add the check earlier on when using `publish`.

**Comment by seanpoulter** [comment]
> so we don't want to take that away

In that case, I'd like to propose a "VS Code Marketplace" mode/strategy/target.
