### ISSUE TITLE
Publish each version of extension separately

### ISSUE THREAD

**Issue by spywhere** [Microsoft/vscode-vsce#88]
\*\* This might not exactly related to the VSCE but this is the component that I think related to the marketplace most.

Upon https://github.com/Microsoft/vscode/issues/6289, I think VSCE need to publish the extension separately to the marketplace. As each version can be installed independently.

Moreover, marketplace (or any source that VSCode use to query extensions) should support the installation of specific extension version.

**Comment by joaomoreno** [comment]
I don't understand what you ask of `vsce` here.

`vsce` will let you publish several versions of your extension. Each version of your extension has a fixed dependency restriction towards VS Code (eg `^1.0.0`).
