### ISSUE TITLE
[bug] The following files have the same case insensitive path, which isn't supported by the VSIX format

### ISSUE THREAD

**Issue by dongwa** [microsoft/vscode-vsce#880]
When I run `vsce package` command,get an error like:

![image](https://github.com/microsoft/vscode-vsce/assets/38457491/8d63ae63-8b52-4769-ba76-8ab46606c46d)

Why limit css file, my extension have some webview need them

my vsce version is  2.19.0:
![image](https://github.com/microsoft/vscode-vsce/assets/38457491/7264069b-7f60-4d2c-b431-1a44921409a7)

**Comment by dongwa** [comment]
os platform is ubuntu:20.04

**Comment by joaomoreno** [comment]
@dongwa The problem is that your have two pairs of files with the same case-insensitive name. From each pair, delete one of them.
