### ISSUE TITLE
Passing a path to the vsce package command

### ISSUE THREAD

**Issue by iownbey** [microsoft/vscode-vsce#882]
Am I missing something, or is there no way to tell `vsce` to use a path other than the current working directory when packaging an extension? If not, then this is a request to add that. (I could probably throw a PR together at some point if vsce is missing this functionality)

**Comment by joaomoreno** [comment]
This goes against the philosophy of "do one thing well".

If you are scripting this, it's easily achieved with:

```
(cd dir; vsce)
```
