### ISSUE TITLE
Exit code 1 from VSCE (without a log)

### ISSUE THREAD

**Issue by katuak** [microsoft/vscode-vsce#888]
Hi!

I am getting exit code 1 from VSCE in a CI. I am not getting any logs. I am not sure what to do:
```
vsce login *** > ***
  shell: /usr/bin/bash -e {0}
  
Error: Process completed with exit code 1.
```
GitHub actions marks *** as a secret (publisher id and token)

Full log: https://github.com/katuak/vscode-language-pack-ca/actions/runs/5767181477/job/15636454345

Thanks!

**Comment by joaomoreno** [comment]
Please use the `VSCE_PAT` variable to login to the Marketplace: https://code.visualstudio.com/api/working-with-extensions/continuous-integration#automated-publishing
