### ISSUE TITLE
How to package node_modules\.bin\babel?

### ISSUE THREAD

**Issue by JaymzZh** [microsoft/vscode-vsce#889]
Is there a way to package file ` node_modules\.bin\babel` ?

other dependencies included, but did'nt contians` .bin` folder

**dependencies:**
![image](https://github.com/microsoft/vscode-vsce/assets/5069316/596850c7-9e00-420e-aa5c-e7ca12fe2f24)

**result:**
![image](https://github.com/microsoft/vscode-vsce/assets/5069316/c50b6ed3-c5ec-48d3-8c58-78e612d87652)
![image](https://github.com/microsoft/vscode-vsce/assets/5069316/cd97df1b-1303-4803-880d-ffc4155e1abb)

**Comment by JaymzZh** [comment]
the babel contain bin field,  although `yarn list --prod --json` can list it, but didn't got the dependency of file `.bin/babel`

![image](https://github.com/microsoft/vscode-vsce/assets/5069316/df3c6381-924f-41bc-b8d9-8db64d0c8454)
![image](https://github.com/microsoft/vscode-vsce/assets/5069316/e4ffb76f-93a6-4ed2-82d3-dc20653db331)

**Comment by joaomoreno** [comment]
The `.bin` folder isn't a dependency, it's an artifact of the root package. VSCE doesn't package them, not should it, IMO. Can you find a workaround to what you're trying to do?
