### ISSUE TITLE
How to publish shell scripts 

### ISSUE THREAD

**Issue by dibyendumajumdar** [Microsoft/vscode-vsce#89]
Hi

For my VSCode Debug Adapter extension I need to deliver some shell scripts in the extension bin folder. How can I ensure that the execute permission on these scripts will be set so that the extension can be launched by VSCode?

Thanks and Regards

**Comment by joaomoreno** [comment]
I just validated that this works. I published a new extension with an executable file and installed it within the product: the file was still executable.

Since executable bits do not work in Windows, just make sure not to publish it from a Windows machine, but from a *nix one.
