### ISSUE TITLE
Add an option to skip engines validation

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-vsce#891]
The Playright folks asked for an option to skip engines validation. They intend to feature-detect the newer APIs they depend on, so I think some `--allow-older-engines` option would be a good addition.

I took a stab (a small stab, more of a poke really) at implementing this, but the code path where validation happens in `readManifest` currently doesn't take any extra options and it's also used by other commands like `verify-pat` that don't take validation options in general.

**Comment by joaomoreno** [comment]
Have they tried using `*` as the engine version of `vscode`?

**Comment by connor4312** [comment]
@pavelfeldman ^
