### ISSUE TITLE
Unable to login PPE publisher account

### ISSUE THREAD

**Issue by drewgillies** [microsoft/vscode-vsce#893]
vsce version: 2.15.0

Repro:
- Create a PAT for use in Marketplace PPE environment https://marketplace.vsallin.net - permissions are Manage and Publish for Marketplace, for all organizations
- Set environment variable VSCE_MARKETPLACE_URL to https://marketplace.vsallin.net
- In a new command prompt, run `vsce login <publisher>`. When prompted for PAT, paste it in.
Expected: successful login
Actual: `Error: Failed request: (401)`

**Comment by joaomoreno** [comment]
This looks like a MP pre-prod issue, since VSCE is reaching out to the right place.

**Comment by sandy081** [comment]
It seems Prod and PPE are two different environments and even publisher IDs are different. That means, I have to create the publisher ID I used for Prod in the PPE. I got the 401 even after doing that. So, I suspect there is some backend (api) thing that is invalidating this.
