### ISSUE TITLE
Support nested `.vscodeignore` files

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode-vsce#896]
The `vsce package` command seems to only notice a `.vscodeignore` file at the root of the package. This is cumbersome and can lead to merge conflicts in a large extension and team. 

Can `vsce` be enhanced to support distributing such files around the repo, the way `.gitignore` can?

**Comment by benibenj** [comment]
@AArnott would [#867](https://github.com/microsoft/vscode-vsce/issues/867) possibly be a better solution in your case? It's an allow list instead of an ignore list. If not, could you go a bit more into detail why nested `.vscodeignore` files would be helpful for you?
