### ISSUE TITLE
Include whether version is pre-release in `vsce --show` output 

### ISSUE THREAD

**Issue by ob-uk** [microsoft/vscode-vsce#899]
Hi all, 

`vsce --show` ends up showing me all the versions of the extension, including the pre-release ones. Is there a way I can infer which version is pre-release vs release?

**Comment by hediet** [comment]
Does not sem to work:

![Code_-_Insiders_rqSBNh9tIF](https://github.com/microsoft/vscode-vsce/assets/2931520/c59b0fc4-eb29-42b9-8223-94eac42b4b44)
