### ISSUE TITLE
Auto-increment package version?

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-vsce#9]
From @lukehoban:

One small but nice thing that Atom’s publishing does is to auto-increment version number based on a version increment flag and commit/tag/push that in the repo before packaging.

This is definitely more opinionated – but makes it really convenient to re-publish frequently, and avoids accidentally re-publishing without incrementing version number.

Here's a snippet from the APM docs that talks about the behaviour.

```
Usage: apm publish [<newversion> | major | minor | patch | build]
       apm publish --tag <tagname>
       apm publish --rename <new-name>

Publish a new version of the package in the current working directory.

If a new version or version increment is specified, then a new Git tag is
created and the package.json file is updated with that new version before
it is published to the apm registry. The HEAD branch and the new tag are
pushed up to the remote repository automatically using this option.
...
```

Would it makes sense to add something similar for to `vsce`'s publish command?

**Comment by unional** [comment]
Definitely would love to have this feature.  I was looking for it. :)

**Comment by SrTobi** [comment]
:+1:

**Comment by joaomoreno** [comment]
Added the possibility for you to do this:

```
vsce publish
vsce publish major
vsce publish minor
vsce publish patch
vsce publish 2.2.1
```

**Comment by SrTobi** [comment]
:+1:

**Comment by gregvanl** [comment]
Entered doc issue https://github.com/Microsoft/vscode-docs/issues/197 to update vsce documentation.
