### ISSUE TITLE
Login Segfaults

### ISSUE THREAD

**Issue by dan-fritchman** [microsoft/vscode-vsce#902]
My attempts to `vsce login` produce this "failed to open credential store" warning, immediately followed by a segfault. 

```
$ vsce login gen-alpha-xtor
 WARNING  Failed to open credential store. Falling back to storing secrets clear-text in: /home/dan/.vsce
https://marketplace.visualstudio.com/manage/publishers/
Personal Access Token for publisher 'gen-alpha-xtor': ****************************************************

Segmentation fault
```

```
$ vsce --version
2.15.0
```

This is on RedHat Linux 7 / CentOS 7.  

```
$ uname -a
Linux instance-3 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

I know, probably not your preferred platform. But the point of my extension is enabling access to somebody *else's* library which *only* works on that OS.

**Comment by joaomoreno** [comment]
Two options:

1. Install libsecret: `sudo yum install libsecret -y`
2. Use the file secret store: `export VSCE_STORE=file`

**Comment by dan-fritchman** [comment]
(Slow response but - that works thanks!)

**Comment by dan-fritchman** [comment]
Clarifying: 

* `VSCE_STORE=file` works
* Installing `libsecret` does not
