### ISSUE TITLE
`dependencies: true` does not work at all

### ISSUE THREAD

**Issue by JounQin** [microsoft/vscode-vsce#914]
https://github.com/microsoft/vscode/issues/200433

![image](https://github.com/microsoft/vscode/assets/8336744/801dbf92-25ff-48bd-85af-a76b1f354ac1)

It says `dependencies` will just work as node `dependencies`, but it actually doesn't and never work.

![image](https://github.com/microsoft/vscode/assets/8336744/de536a97-ccfe-40a3-b39d-a528aead67ec)

For now, we have to bundle all dependencies manually.

**Comment by joaomoreno** [comment]
Hi @JounQin. You are ignoring `node_modules` to be included in the VSIX:

https://github.com/idahogurl/vs-code-prettier-eslint/blob/5c6b2e6ab74ca8ef5706deca558a6899d6c80e82/.vscodeignore#L8

For next time, please provide more details, including a link to your sources. It will make the support process easier and faster.

**Comment by JounQin** [comment]
I think the document could be documented, mostly `node_modules` will be ignored for any frontend project?

**Comment by joaomoreno** [comment]
A VS Code extension isn't quite a frontend project.

**Comment by JounQin** [comment]
Yeah, I understand your point, but ignoring `node_modules` is very commonly used, so the document should mention it, I believe no one like you knows I have to list `node_modules/dep` to make  it bundle free.
