### ISSUE TITLE
Support `--ignore-other-target-folders`

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-vsce#916]
When using `vsce package` or `vsce publish` with `--target` it would be nice to have a `--ignore-other-target-folders` which automatically and recursively ignores all folders named the same as all other targets.

This allows extension authors to have:

```
package.json
linux-x64/file.txt
darwin-arm64/file.txt
web/file.txt
```

And with `vsce publish --target linux-x64 --ignore-other-target-folders`, only the following files would be included:

```
package.json
linux-x64/file.txt
```

**Comment by sandy081** [comment]
@joaomoreno Looks like these changes are not available in latest vsce module

<img width="727" alt="image" src="https://github.com/microsoft/vscode-vsce/assets/10746682/1791f18c-cabd-4940-a584-b93f41c5ce25">

**Comment by connor4312** [comment]
Verified using the `next` tagged-version

**Comment by dfgordon** [comment]
With vsce 3.1 the option is offered, but maybe doesn't work?
`vsce package --target linux-x64 --ignore-other-target-folders`
is accepted, but still includes all the files, if we believe the file tree and file count that gets written to the console. Size of the VSIX is within 1-2 bytes no matter what target is chosen. Test was done on Windows 11.
