### ISSUE TITLE
cannot publish no request found.

### ISSUE THREAD

**Issue by web-dave** [Microsoft/vscode-vsce#92]
> vsce publish
Executing prepublish script 'node ./node_modules/vscode/bin/compile'...
Publishing web-dave.ng2-dg@0.0.2...
Error: Failed Request: Not Found(404) -

no hints. whats wrong? user is known, other Extensions work fine.

**Comment by joaomoreno** [comment]
Are those sources the latest `master` branch in web-dave/ng2-dg?

**Comment by joaomoreno** [comment]
I can reproduce. Let me forward this to the right people.

**Comment by joaomoreno** [comment]
Never mind, I can reproduce.

**Comment by joaomoreno** [comment]
@pradeepna We seem to be getting a 404 without any error message when publishing this extension... Any idea why?

You can reproduce by cloning https://github.com/web-dave/ng2-dg.git, modifying `package.json` by adding `typescript` to the list of dependencies and changing the publisher name to yours and trying to publish.

**Comment by joaomoreno** [comment]
Just confirmed with the Marketplace people: extensions are limited to 20MB.

Is there any way you can reduce the dependencies of your extension? You can see how large the current package is by running `vsce package`, it will produce a `.vsix` file. You're currently hitting over 30MB.

**Comment by web-dave** [comment]
THX for your help/hint

**Comment by joaomoreno** [comment]
Also, the Marketplace team will work on providing an error message in that case.
