### ISSUE TITLE
Retry on API request timeout

### ISSUE THREAD

**Issue by radeksimko** [microsoft/vscode-vsce#926]
## Background

Currently when the connection between where `vsce` is running and the Marketplace API times out, the publishing fails. This becomes especially problematic if packages for multiple platforms are being published at the same time, e.g.

```
vsce publish --pre-release --no-git-tag-version --packagePath $(find . -iname *.vsix)
```

(where `*.vsix` can match 8 files)

We ran into this recently in https://github.com/hashicorp/vscode-terraform/actions/runs/7540203435/job/20524327288#step:3:22

```
Publishing 'hashicorp.terraform (darwin-x64) v2.29.2024011611'...
Extension URL (might take a few minutes): https://marketplace.visualstudio.com/items?itemName=hashicorp.terraform
Hub URL: https://marketplace.visualstudio.com/manage/publishers/hashicorp/extensions/terraform/hub
Published hashicorp.terraform (darwin-x64) v2.29.2024011611.
Publishing 'hashicorp.terraform (web) v2.29.2024011611'...
Extension URL (might take a few minutes): https://marketplace.visualstudio.com/items?itemName=hashicorp.terraform
Hub URL: https://marketplace.visualstudio.com/manage/publishers/hashicorp/extensions/terraform/hub
Published hashicorp.terraform (web) v2.29.2024011611.
Publishing 'hashicorp.terraform (linux-arm64) v2.29.2024011611'...
Extension URL (might take a few minutes): https://marketplace.visualstudio.com/items?itemName=hashicorp.terraform
Hub URL: https://marketplace.visualstudio.com/manage/publishers/hashicorp/extensions/terraform/hub
Published hashicorp.terraform (linux-arm64) v2.29.2024011611.
Publishing 'hashicorp.terraform (linux-x64) v2.29.2024011611'...
Error: Request timeout: /_apis/gallery/publishers/hashicorp/extensions/terraform
Error: Process completed with exit code 1.
```

It leaves the extension in a half-published state, which is not ideal.

The easiest fix is to run this again with `--skip-duplicates` but it would be great if there was no need for such retry in the first place.

## Proposal

Have vsce retry on API failures like timeout automatically a few times with some backoff in between.

e.g. retry 3 times with ~5-10 seconds in between?

**Comment by joaomoreno** [comment]
Sounds good. Would you like to contribute a PR to add [cockatiel](https://www.npmjs.com/package/cockatiel) to perform this for us?

**Comment by eleanorjboyd** [comment]
This bug has been fixed in the latest release of [VS Code Insiders](https://code.visualstudio.com/insiders/)!

@radeksimko, you can help us out by commenting /verified if things are now working as expected.

Happy Coding!
