### ISSUE TITLE
vsce 2.23.0 dropped support for yarn v2 pnp

### ISSUE THREAD

**Issue by paulober** [microsoft/vscode-vsce#928]
Since version 2.23.0 I get errors like this one if I run `vsce package` for a yarn v2 pnp based project:
```
ERROR  Extension manifest not found: /path/to/my/project/node_modules/a-package/package.json
```
Versions prior to 2.23.0 supported yarn v2 pnp and knew that there isn't a node_modules with this approach. But the new update breaks this feature.

**Comment by paulober** [comment]
@joaomoreno Hello, I guess you're some kind of maintainer of this repository at MS. 
Is there any chance this gets fixed in the near future?

**Comment by joaomoreno** [comment]
@paulober , vsce 2.24.0 is out, can you see if that helps? Thanks for letting us know.

**Comment by paulober** [comment]
@joaomoreno 

> @paulober , vsce 2.24.0 is out, can you see if that helps? Thanks for letting us know.

Thanks this solved the issue for me.

**Comment by eleanorjboyd** [comment]
Thanks @paulober for verifying! Happy coding 🎉
