### ISSUE TITLE
vsce package ERROR

### ISSUE THREAD

**Issue by talison-cardoso** [microsoft/vscode-vsce#933]
Yes, I already saw that there is an issue with this same problem. But I couldn't figure out how it was resolved. And I urgently need to generate this 'package'. Help me please.

![Screenshot from 2024-02-10 11-54-19](https://github.com/microsoft/vscode-vsce/assets/132726516/5f343cfa-dd32-486d-8558-33fff937e807)

I have already reinstalled vsce, cloned the repository again and had no success. I don't know what else I can do to solve this :(

`vsce --version`  2.23.0
`node --version` v20.11.0

**Comment by paulober** [comment]
You probably defined an icon path in your package.json icon property that doesn't exist relative to your package.json.

**Comment by TylerLeonhardt** [comment]
@joaomoreno verification steps?

**Comment by joaomoreno** [comment]
@talison-cardoso, vsce 2.24.0 is out, can you see if that helps?

**Comment by talison-cardoso** [comment]
It is not possible even after the update (**vsce 2.24.0**). The strange thing is that I have already done all the necessary procedures and have not been successful in my OS.

But I solved the problem by cloning the extension on another OS and it worked perfectly.

Thank you very much for your feedback. Success!!!
