### ISSUE TITLE
vsce 2.23.0 incorrectly reports missing entrypoints

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-vsce#935]
vsce@2.23.0 seems like it can no longer package remote tunnels ([build pipeline](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=258520&view=logs&s=4d39c4cf-1711-5036-705e-ac02510e89c1&j=a4799567-7142-5b25-e045-e6f6b97005c3))

`npx @vscode/vsce@2.22.0 package` works, but `npx @vscode/vsce@2.23.0 package` fails, stating:

```
 ERROR  Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':
  extension/dist/node/extension.js,
  extension/dist/web/extension.js
```

However, those files do exist and [aren't ignored](https://github.com/microsoft/vscode-remote-tunnels/blob/main/extension/.vscodeignore). vsce is being run within one package in an npm workspace. This can also be reproduced locally, though note that you need to authenticate with the devdiv npm feed to successfully `npm install`.

**Comment by joaomoreno** [comment]
I'm really not sure how this was ever working before, since npm workspaces were never fully supported: https://github.com/microsoft/vscode-vsce/issues/580

**Comment by connor4312** [comment]
> I'm really not sure how this was ever working before, since npm workspaces were never fully supported:

The extension bundles everything and runs with --no-dependencies, so nothing workspace-specific was ever needed

**Comment by joaomoreno** [comment]
Ahhh I missed that. Good! 👏
