### ISSUE TITLE
Error: Item has already been added.

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode-vsce#939]
Run vsce publish -i y3-helper-0.2.8.vsix -p ***
Publishing 'sumneko.y3-helper v0.2.8'...
Error: Item has already been added. Key in dictionary: 'extension/template/csv_template/??????/base_info.csv'  Key being added: 'extension/template/csv_template/??????/base_info.csv'
Error: Process completed with exit code 1.

vsix: https://github.com/y3-editor/y3-helper/actions/runs/8259481877/artifacts/1321013557

**Comment by joaomoreno** [comment]
Can you provide the _full_ output of the build?

**Comment by sumneko** [comment]
This is the full output: https://github.com/y3-editor/y3-helper/actions/runs/8259481877/job/22593457066

However after I reruned this job, the issue has gone: https://github.com/y3-editor/y3-helper/actions/runs/8259481877/job/22714533609

**Comment by sumneko** [comment]
It apears again: https://github.com/y3-editor/y3-helper/actions/runs/8700759320/job/23862341213
