### ISSUE TITLE
Which node version does vsce work on?

### ISSUE THREAD

**Issue by amvanbaren** [microsoft/vscode-vsce#944]
The [README](https://github.com/microsoft/vscode-vsce/blob/main/README.md#requirements) says `at least 18.x.x`, while the [package.json](https://github.com/microsoft/vscode-vsce/blob/main/package.json#L38) says `>= 14`

**Comment by benibenj** [comment]
We recommend to use at least version 18 as it is likely that the engine version will be increased. Theoretically, node 16 would work but we don't recommend setting up a pipeline with that dependency as it might change soon.
