### ISSUE TITLE
Is there any reason that vsce package does not package any package.nls.json file?

### ISSUE THREAD

**Issue by travis1111** [microsoft/vscode-vsce#951]
I tried the l10n sample it works, `package.nls.json` is packaged in the `vsix` file.
But for some reason, the `package.nls.json` does not get packaged in my extension's `vsix` file.
What are the reasons?
I checked the json file is valid. 

Thanks

**Comment by senyai** [comment]
Maybe it is masked by a line in your `.vscodeignore`?

**Comment by benibenj** [comment]
Have you figured it out? Did you check if your `.vscodeignore` file was ignoring it?
