### ISSUE TITLE
Opinion on new 2.26.0 azure option

### ISSUE THREAD

**Issue by senyai** [microsoft/vscode-vsce#968]
Hi! After updating to 2.26.0, my `npm update` said that it `added 42 packages`. Not cool. Maybe it's time to use `esbuild` or maybe it's all fine and it's just me.

**Comment by joaomoreno** [comment]
I believe this is OK. VSCE is a CLI tool, not meant for shipping in production. Size doesn't matter much. But thanks for keeping a keen eye on things.
