### ISSUE TITLE
Windows, error "spawn EINVAL" when publishing

### ISSUE THREAD

**Issue by larshp** [microsoft/vscode-vsce#969]
Running node 20.12.2 + vsce 2.26.0 on windows, and publishing it gives error "spawn EINWAL"

I guess it executes `npm.cmd`

see https://github.com/nodejs/node/issues/52554 and https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

workaround is to add `{ shell: true }`

https://github.com/microsoft/vscode-vsce/blob/main/src/package.ts#L409

workaround: downgrading to node 20.12.1

**Comment by joaomoreno** [comment]
Yup, we started hitting this in our very own CI since almost a week.

@benibenj Can you take a look?
