### ISSUE TITLE
Support relative image paths in README.md

### ISSUE THREAD

**Issue by skolmer** [Microsoft/vscode-vsce#97]
If I have an image in my repository like `images/imageA.jpg` and create a relative reference in my README.md like `![My Image](images/imageA.jpg)` the path is resolved to `https://github.com/[repo ]/blob/master/images/imageA.jpg` but should be `https://raw.githubusercontent.com/[repo]/master/images/imageA.jpg`. 
Related to #85

**Comment by joaomoreno** [comment]
Wanna try submitting a PR on this? 👍

**Comment by skolmer** [comment]
I have checked the code and tested it with my own readme. Relative image paths are working in general. In my case I have linked images that are failing. `[![Image](/image/test.jpg)](http://someurl)` is resolved to `[![Image](https://github.com/username/repository/raw/master/image/test.jpg)](http:/shouldnottouchthis/)`
I will create a PR later this week to resolve the issue

**Comment by skolmer** [comment]
This was easier to solve than I thought. Here you go #98
