### ISSUE TITLE
vsce reports a package is published before it's actually visible to VSCode

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/vscode-vsce#975]
It can take several minutes for a new published version to become visible in whatever APIs VSCode uses to look up the package.  This gets annoying, since I never have this problem with `npm publish`, once it finishes, I've always been able to install the new published version right away.

I assume this is probably an inherent weakness of some kind of CDN system Microsoft is using for VSCode extensions.  But is there any way `vsce publish` could just wait until the published package is actually visible?

**Comment by benibenj** [comment]
This will be due to caching and CDNs of the marketplace. The only think we could potentially provide is a flag which can be set that polls the marketplace until the packet is visible after publishing. Could you elaborate on how this could be helpful for you?

**Comment by jedwards1211** [comment]
I'm sorry, I was in a gripey mood.  it just feels annoying to not know when my updated package is going to actually show up when I'm iterating on something.  Really just a minor annoyance, but I was thinking, npm isn't like this, so it doesn't have to be this way

**Comment by benibenj** [comment]
Closing as there us no plan to change anything here. 

FYI we have the `vsce show EXTENSION_ID` command which allows you to fetch metadata about the extension on the marketplace
