### ISSUE TITLE
File called README.md is always included

### ISSUE THREAD

**Issue by OscarAblinger** [microsoft/vscode-vsce#978]
We are developing an extension in a private repository. Naturally we have a README file that explains how to build it etc.. Not really useful as the front page for the extension, so instead we have a separate one for that.

When packaging it, I noticed that the README.md file is always included in the resulting .vsix file, even though I explicitely excluded it in the .vscodeignore file:

```
*
*/**
# also tried it explicitely
README.md
```

This is the case even when the readme is specified with `--readme-path`.

I found that this behaviour was introduced in PR #556.
While it was clearly intentionally added, I feel like this behaviour should definitely be considered a bug. If I ignore something, it should be ignored.
If I need the readme file, then I should have to include it in the specified files (or in this case not ignore it).

**Comment by benibenj** [comment]
You are right, at least when `--readme-path` is specified, the `readme.md` file should be able to be ignored.

**Comment by subdavis** [comment]
Looks like there's a bug on the VS Code side as well related to this.

* before installation from marketplace, the readme specified by `--readme-path` is used.
* once the extension is installed, the default `README.md` which should not have been bundled is used.

Even if the solution here is to remove it from the bundle, something else is also broken.

**Comment by benibenj** [comment]
I created a fix for this, could you try the newest pre-release version of vsce ([2.31.1-1](https://www.npmjs.com/package/@vscode/vsce/v/2.31.1-1)) to verify that this works as expected?
