### ISSUE TITLE
ERROR  No translation found for %abc%

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode-vsce#981]
vsce v2.26.1 raises `ERROR  No translation found for %abc%` when executing `vsce package`.

Steps to reproduce:

1. Add the following to `package.json` of the extension:

```json
	"contributes": {
		"configuration": {
			"title": "Hello World",
			"type": "object",
			"properties": {
				"someString": {
					"type": "string",
					"default": "%abc%"
				}
			}
		}
	},
```

2.  Execute `vsce package`.

vsce should not validate the default values of configurations, which can be any value.

**Comment by benibenj** [comment]
It seems like translations are validated even when there is no NLS file. I changed it such that NLS validation only happens when a NLS file is present
