### ISSUE TITLE
vsce publish success but no new bits updated in vscode extension marketplace

### ISSUE THREAD

**Issue by wenytang-ms** [microsoft/vscode-vsce#985]
Hi, this is my publish pipeline defined in GitHub
https://github.com/OfficeDev/teams-toolkit/blob/2a41b1464928a66a0aa02671b4be64c5da80ab92/.github/workflows/vscode-marketplace.yml#L85

And i triggered the publish pipeline and it shows the pipeline run successful
https://github.com/OfficeDev/teams-toolkit/actions/runs/9298056908/job/25589253598

But the vscode extension marketplace show no any new version here
https://marketplace.visualstudio.com/items?itemName=TeamsDevApp.ms-teams-vscode-extension

could you help to take a look in? thanks

**Comment by wenytang-ms** [comment]
hi, i have tried again, and show that `AbortController is not defined`
have any idea? 
```
Run npx @vscode/vsce publish --azure-credential --packagePath *.vsix --noVerify
  npx @vscode/vsce publish --azure-credential --packagePath *.vsix --noVerify
  shell: /usr/bin/bash -e {0}
AbortController is not defined
Error: Process completed with exit code 1.
```

**Comment by johnsoncodehk** [comment]
I seem to have the same problem. As a temporary solution, you can go to https://marketplace.visualstudio.com/manage/publishers to manually upload a new version.

<img width="772" alt="螢幕截圖 2024-06-23 下午11 55 05" src="https://github.com/microsoft/vscode-vsce/assets/16279759/305dbec5-8ad0-4557-9c1e-2fe06877fc2d">

**Comment by benibenj** [comment]
@johnsoncodehk Can you let us know what vsce arguments you used when publishing?
