### ISSUE TITLE
vsce package is broken (again)

### ISSUE THREAD

**Issue by complyue** [microsoft/vscode-vsce#989]
Regression of #929 ?

```sh
% vsce --version
2.26.1
% vsce package
 ERROR  Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':
  extension/out/extension.js
```

`extension/out/extension.js` there an apparent signature.

**Comment by benibenj** [comment]
We have a newer version (2.27). Can you check if you still see this with that version?

**Comment by complyue** [comment]
@benibenj 

Using https://github.com/koka-lang/koka/tree/dev/support/vscode/koka.language-koka

```bash
$ vsce -V
2.27.0
$ vsce package
 ERROR  Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':
  extension/out/extension.js
$ 
```

**Comment by joaomoreno** [comment]
@complyue VSCE can't find `extension/out/extension.js`. Did you forget to compile the TypeScript sources? What does `vsce ls` return?

**Comment by complyue** [comment]
> Did you forget to compile the TypeScript sources? What does `vsce ls` return?

There does exist `out/extension.js`, vsce seems to insist on an extra `extension/` prefix, which may due to workspace support (see #929), which may still be buggy on non-workspace cases so far.

**Comment by joaomoreno** [comment]
What does `vsce ls` return?

**Comment by complyue** [comment]
```bash
% vsce ls
images/codelens.png
images/impliciteq.png
images/inlayhints-off.png
images/inlayhints.png
images/koka-logo-filled-dark.svg
images/koka-logo-filled-light.svg
images/koka-logo-filled.png
images/koka-logo-filled.svg
package.json
README.md
syntaxes/koka.json
whatsnew.md
```

**Comment by joaomoreno** [comment]
I don't see `out/extension.js`, are you sure it's in disk? What does `tree` return?

**Comment by complyue** [comment]
No this file, it's open source and you can verify if in doubt: https://github.com/koka-lang/koka/tree/dev/support/vscode/koka.language-koka

**Comment by benibenj** [comment]
I figured out what is going wrong here. You are using the `files` property in the `package.json` file. This property is an include list of all files/directories which should be packaged. This is why the files in the image folder are listed with `vsce ls` as you added ` "images/"` to the files list but files in the `out` folder are not added it's not included in the `files` property.
