### ISSUE TITLE
Do not allow http images in README.md

### ISSUE THREAD

**Issue by skolmer** [Microsoft/vscode-vsce#99]
For security reasons vsce should not import http images to the marketplace (or replace http image urls with https?)
![screen](https://cloud.githubusercontent.com/assets/2427106/16192425/7e347ade-36e9-11e6-82c6-2ae01c71cb5b.jpg)

**Comment by carlosjs23** [comment]
I think the marketplace site is who should handle this, a suggestion would be to implement for example: [camo proxy](https://github.com/atmos/camo) .

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode-vsce/blob/b9a110bbddc24b78791ff279354a4c07fb707212/src/package.ts#L404
