### ISSUE TITLE
Does vsce support an OAuth Token to access the MarketPlace?

### ISSUE THREAD

**Issue by trevors20** [microsoft/vscode-vsce#992]
Hi.  I am looking into replacing my PAT that I used to publish to the MarketPlace using the vsce tooling.
I am thinking of replacing the PAT with an OAuth token that I would obtain using an ADO Federated Service Connection.

Will the vsce tooling work with this type of OAuth token?  Any special switches that I would need to send to vsce in order for it to work or anything like that?

Thanks much!

**Comment by benibenj** [comment]
/duplicate [#1004](https://github.com/microsoft/vscode-vsce/issues/1004)
Open
