### ISSUE TITLE
Support signing related features

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-vsce#993]
Support following signing related features

- Generate the extension manifest from the extension vsix: `vsce generate-manifest --packagePath <package-path> --out <manifest-output-path>`
- Publish the extension with signed manifest: `vsce publish --packagePath <package-path> --manifestPath <manifest-path> --signaturePath <signature-path>`

**Comment by connor4312** [comment]
@sandy081 vsce needs to be published still

**Comment by connor4312** [comment]
I'm not clear on how to generate the `--signaturePath`, the --help docs are also not super helpful (maybe signing info lives on the vscode docs eventually)

**Comment by sandy081** [comment]
@connor4312 vsce does not support signing the manifest, one has to sign the manifest separately and pass it vsce for publishing. This is limited only feature for now. 

I am marking this as verified since our pipelines are successfully generating the manifest, signing it and publish them using vsce.
