### ISSUE TITLE
Print packaged extension contents on package/publish

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-vsce#995]
Let's be inspired by `esbuild` and print out what is actually being packaged.
This should be printed out both on `vsce package` and `vsce publish`. We could even have a nice ⚠ on items that are larger than some limit. Only top level files/folders can be printed.

The goal is to make it easier for extensions authors to figure out what is actually being packaged as part of their extension. So they can avoid accidentally packaging something.

![Image](https://github.com/microsoft/vscode-vsce/assets/1926584/73910f5c-b285-4f3c-971b-1d4c4bcbd001)

fyi @joaomoreno

**Comment by joaomoreno** [comment]
Addition to the idea: we should also print out which inclusion/exclusion rules were used or missing during file collection (ie `.vscodeignore`, `files` prop).

**Comment by benibenj** [comment]
![Image](https://github.com/user-attachments/assets/244cae0b-aec1-4ab4-8342-1c4cc4afdb6b)

**Comment by isidorn** [comment]
Works great, thanks a lot for this!

![Image](https://github.com/user-attachments/assets/10fa59fa-6f8c-488b-b8c5-e6d5e7541245)
